# Cluster CA Certificate Trust Module
#
# Configures NixOS to trust self-signed CA certificates from local Kubernetes clusters.
# This is required for HTTPS access to cluster services (Gitea, etc.) that use
# cluster-generated certificates.
#
# The CA certificate is persistent and stored in Azure Key Vault.
# It's valid for 10 years and doesn't change on cluster recreation.
#
# Usage:
#   services.clusterCerts = {
#     enable = true;
#     # Certificate content is inlined - no external file needed
#   };

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.clusterCerts;

  # Persistent CA certificate for *.cnoe.localtest.me
  # Generated by: stacks/deployment/scripts/persistent-secrets/setup-persistent-certs.sh
  # Stored in: Azure Key Vault (IDPBUILDER-CA-CRT)
  # Valid: 2026-01-07 to 2036-01-05 (10 years)
  # This is a proper CA certificate (CA:TRUE) that signs server certificates
  persistentCaCert = ''
    -----BEGIN CERTIFICATE-----
    MIIGLzCCBBegAwIBAgIUD+PQqrSsss28Hntp4OJdzK97Mm0wDQYJKoZIhvcNAQEL
    BQAwgZ4xCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQH
    DA1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKDBZDTk9FIExvY2FsIERldmVsb3BtZW50
    MR0wGwYDVQQLDBRQbGF0Zm9ybSBFbmdpbmVlcmluZzEiMCAGA1UEAwwZQ05PRSBM
    b2NhbCBEZXZlbG9wbWVudCBDQTAeFw0yNjAxMDcwODQ1MDJaFw0zNjAxMDUwODQ1
    MDJaMIGeMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UE
    BwwNU2FuIEZyYW5jaXNjbzEfMB0GA1UECgwWQ05PRSBMb2NhbCBEZXZlbG9wbWVu
    dDEdMBsGA1UECwwUUGxhdGZvcm0gRW5naW5lZXJpbmcxIjAgBgNVBAMMGUNOT0Ug
    TG9jYWwgRGV2ZWxvcG1lbnQgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQDAsSgTE3yaf4nrWD0h5eZJAKDnvmeR/vAK1l6S0yGsgerVtnW/pr3Z7fwa
    tiUP0oKgGbsbqU0kdRk6bzN0rJHSoYhm0aPnRSevga9pcF/tXBGMC1Mr/rbCSwiO
    4CVU7cvGqh9YXh7m/kU675hHDRKHz7tx7nYGcbPFWfz9AjUTC/k+JOC3NkfeNtrF
    DY9L5KJc272ugQpHgFJRRhIWq5IvUl/oI0cISf3hvF+atJsRo9Keb3JlRcqLfaiV
    s8BuA+lUPjuMp7sAYIyrPfb5A9yKrT0K83fGBjdmgt3YxUlwRbVBOb+bPyp7hZVn
    YCBVaPf9TBc8hMms3anY2y8Ng7qtvq1/ccaUcZR6j/Pt5SXLVxR91LY4+tOBfGNn
    gnL8pYM7/peeZOLMaU+lxu/io/HcBEjbx3YbC16660WY3cBwSUTFQWZYtXrIH1l8
    rsmdEgpnRqMVAn6PJLLABTWeGIYIk3dMffjCPqkD8WbYYygiVB917t2w+g/SwXPS
    nGMy8xj9T1upDWkKRkF5SxVvCFOjBpSg/sXBDw41W81guOzmP75LCD6o5qLjAaTK
    0SLeq2AxQtBbJId1Fm0LYt/UJv64o3WvlUfoFdCd2AGQRlLshczpa8MbM6UtAS78
    cxqTYylzkGp8APKM5iX40juY9fJGH6HeOBNO1ViUMIKBNlgI0QIDAQABo2MwYTAP
    BgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUxY3oHpbt
    RCr54K/RGNOzoBCkkzQwHwYDVR0jBBgwFoAUxY3oHpbtRCr54K/RGNOzoBCkkzQw
    DQYJKoZIhvcNAQELBQADggIBACKVRgns/3SbU4Jq+Zkyc8Z8YbG3TW1ZAQf/uodH
    Dtb204SgJbj2qBW0AuzpcRymVtQbfTLGRpomHdBbdz3ebr7oXmVMTGtDTrUpvb4q
    QP+5w5P3+kWirXUAxZHxqGrjM9XQazcR9DAWIf5oXGrZrU7C72vCdqePEvfCiqJb
    yjqt0s1cWmG7ydgbwMGiiXeCO9V1m+7SgTfOhEGqbcPUFbstoneOGzp0eWmVn9VM
    a8hHBrkf0SVvNAYEbfNvYy5m2fRv2YJ+cPv2NmQ9/MTXNZmN9T+s3T6Slku57IYc
    vygihWGL48i5CxUeGADlp8KgPw1bNFieI1gW+Z/pRSmJQqaoHLAT8bXrAh7BOPA/
    eqSIjEl/LZQ90XfiXCrw+nRIvDSrMyBy6nhAI2DULgtzbtsBaHmB7Lm/IRQf1h71
    4J0Bl3wRysJwHxTLYMiUvL63pZqebout5AMolOtdooog62kIRwaPtQDtC8utBF1/
    8EeAFrOLgVEso70tavV6Ekgpy4Ms5U3e8/HPMWckmUyVxJ0dZqdoVsAgH1v63fkb
    rKSg3nDAqaXrr6BkaJShGr/I4RwMdoHkYI5TXCcLdCVHn8oU7V//YDY1QUIzOQVk
    yVUj3gMPxXbYQQsV5saBRfmS6QGhFjaOR+XHJNocxjR1dIC2CDDUIS1/Suykz0A9
    CBn6
    -----END CERTIFICATE-----
  '';

  # Persistent self-signed CA for *.tail286401.ts.net (private-tailnet HTTPS, no
  # Let's Encrypt). Signs the workflow-builder LB sidecar wildcard on dev/ryzen
  # (and staging/future). Generated once + stored in Azure Key Vault
  # (TAILNET-DEV-CA-CRT); 10-year, stable across cluster recreation.
  tailnetDevCaCert = ''
    -----BEGIN CERTIFICATE-----
    MIIFdjCCA16gAwIBAgIUba+MPqKH7zUFilKgJcYaXrKJK5MwDQYJKoZIhvcNAQEL
    BQAwQTEXMBUGA1UECgwOUGl0dGFtcGFsbGlPcmcxJjAkBgNVBAMMHVBpdHRhbXBh
    bGxpT3JnIFRhaWxuZXQgRGV2IENBMB4XDTI2MDUzMDE1NDQzMVoXDTM2MDUyNzE1
    NDQzMVowQTEXMBUGA1UECgwOUGl0dGFtcGFsbGlPcmcxJjAkBgNVBAMMHVBpdHRh
    bXBhbGxpT3JnIFRhaWxuZXQgRGV2IENBMIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
    MIICCgKCAgEA1g8V91eREP/2PaHy7/h4uQHyCGZgch9HiMpGwzla6XoDinKo24Nt
    tHP/S4DlPuFUw7EwMtZJMUe8AzC47+vDlk9KTW2uAbVQGYksIs5TlL9B7W58o4qO
    dVFPHwlqnEuOtwEYAQYNk6p65jr81KdtFCF8MexM/+uQ8eKKwinMbmxf+2JVV1Km
    eWKJ2UI0jWiJvntDAXxC2JcWU/Z6nfU00fMjglkPWhStYe9Pm1XFEQZy33sUfNW8
    MfzirC830YWJwnrhRKuott9lIM6H6z1YX0UykJGD7zXu3Ldw8udCKQFaPokWr++P
    yFOFJ5vWolcGzX2EJRp2gMdl4JiLPvKEl5JPL1ibWzgOQWxevHOiMd59fG9OwQ7W
    dB/xw5j1GIf+abT2+jcDag1OnXZq6m3Lc1P5/9QWUYb6/zOTVNBu0UzOXXwGIijM
    60VnlUZ/MX3o+B9oOU1ujhqWwgvBBMZHvxgp45gPbXmvA9Hs77scHq2lgBRQ9jqY
    xCexAJWL7QtnU9O1MsI6WKM8ZTO195VcYZH7L4X5i7rKbt+g7reO9HTYZpucEqpW
    1Pl75YdCy+bvL9gx5JunJgScOyoxI0z6Yg4O5Ti72B9Iyyz4oejAbMkMnYa+tbMw
    h26HC1A3vzF43PE5Z+KPMiHIp9vRtYagPHvLuuHqjoWpnb/AEXjUB3MCAwEAAaNm
    MGQwHQYDVR0OBBYEFIZlA6b8ifeekApmFYpA72bXiEY7MB8GA1UdIwQYMBaAFIZl
    A6b8ifeekApmFYpA72bXiEY7MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/
    BAQDAgEGMA0GCSqGSIb3DQEBCwUAA4ICAQCPy1Fo4MGwfBXHqB1s+bqa7fEfPkH6
    5egG8IxQWP46hKTpgktYv2ldMtFz+Rpft4guUI80RO6a2xx7xxSEErS+pBtVIW51
    OKmoTlELKDJD3Ij9pnAzNWQAqyGgkn2PIpymuGjZPYHvvp2oL4ZuI+BH2+YCshpw
    Ka/C09ivrxWvZAKnerqgZyt9DkhhNkxJGZmypd7m4/5Vj0nfKy5phS1aphUvRLAd
    /oa4ec07tDWgRZKmTJhtW73JN6sUiXJ6Ii/KcygRGbkCYUdJi+ub+/qymLCime1F
    13PXKpqcJQdb1FG2SvG8Of8Z6icIlm4TILZ8uWZ0m9xPCfcxatPXPQr1qk13YMbd
    dg+zFj6qELPSpsp6R5Iu4rYSyFRJq08TLP6eP8HajlwFitxHlTsTV7iG2Scc5LtE
    2+xfjfk64n8Zam96Vx8qXIcGtjf38rkCDMMFa+i11SIegT4SyqVF6J6m6HyQNc+0
    qDgec6hohglCD3Xwqm6jy1MCFfD/FcqMPGqckZ57Uw+B9zNff19jj3iJ3cGRc0nr
    +488OsT2xVqVZWgCQIY+o31om08OHxNy9N9F397LtGux5nj0a4jkXfHLEIMzE6z1
    vX7liabqI9knR/D0DRXlpf0RTv9mddqpb8Pt0pAC+yYS2P8OCWCBDdVeE91/Ftpb
    OVc1x3Hlkbq2mA==
    -----END CERTIFICATE-----
  '';
in {
  options.services.clusterCerts = {
    enable = mkEnableOption "Trust local Kubernetes cluster CA certificates";
  };

  config = mkIf cfg.enable {
    # Add the cluster CA to the system trust store
    # This allows curl, git, and other tools to trust HTTPS connections
    # to services using cluster-issued certificates (e.g., Gitea)
    security.pki.certificates = [ persistentCaCert tailnetDevCaCert ];

    # CRITICAL: Configure Nix daemon to use the system CA bundle
    # By default, Nix fetchers use pkgs.cacert directly, which doesn't include
    # custom certificates from security.pki.certificates
    # See: https://github.com/NixOS/nixpkgs/issues/101119
    nix.settings.ssl-cert-file = "/etc/ssl/certs/ca-certificates.crt";

    # Also set for systemd service environment (belt and suspenders)
    systemd.services.nix-daemon.environment.NIX_SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
  };
}
