# Cluster CA Certificate Trust Module
#
# Configures NixOS to trust self-signed CA certificates from local Kubernetes clusters.
# This is required for Nix to fetch from binary caches (like Attic) that use HTTPS
# with cluster-generated certificates.
#
# The CA certificate is persistent and stored in Azure Key Vault.
# It's valid for 10 years and doesn't change on cluster recreation.
#
# Usage:
#   services.clusterCerts = {
#     enable = true;
#     # Certificate content is inlined - no external file needed
#   };

{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.clusterCerts;

  # Persistent CA certificate for *.cnoe.localtest.me
  # Generated by: stacks/deployment/scripts/persistent-secrets/setup-persistent-certs.sh
  # Stored in: Azure Key Vault (IDPBUILDER-CA-CRT)
  # Valid: 2026-01-05 to 2036-01-03 (10 years)
  persistentCaCert = ''
    -----BEGIN CERTIFICATE-----
    MIIGSTCCBDGgAwIBAgIUX/slhAz/ZWHiv3hTn6xtSoxV9bEwDQYJKoZIhvcNAQEL
    BQAwgZgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQH
    DA1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKDBZDTk9FIExvY2FsIERldmVsb3BtZW50
    MR0wGwYDVQQLDBRQbGF0Zm9ybSBFbmdpbmVlcmluZzEcMBoGA1UEAwwTKi5jbm9l
    LmxvY2FsdGVzdC5tZTAeFw0yNjAxMDUyMzE4MzVaFw0zNjAxMDMyMzE4MzVaMIGY
    MQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2Fu
    IEZyYW5jaXNjbzEfMB0GA1UECgwWQ05PRSBMb2NhbCBEZXZlbG9wbWVudDEdMBsG
    A1UECwwUUGxhdGZvcm0gRW5naW5lZXJpbmcxHDAaBgNVBAMMEyouY25vZS5sb2Nh
    bHRlc3QubWUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCandEnCYoW
    +XW0OepqdgD+ddgUKFrRU4pmHO4Xerkt4m19A7xJbim9f4Ma7hvJ9pkSzrDqjmXI
    ygsxnlBVvrs00pxg3Smf5rFhVuDk08Oa06QF/eM4T5RXbU0+pBYc5fjcW2TiL+00
    /mzsa5r6gPFXQQI4LJ6BxMRd+5oza7EmX1GDZHwsLsEzpXpL6Ylz89i0A4WvDF5w
    +yniSU+09wWKJy4QuS01WP8fWMxvIJLdZIi8+QlVVEOAm2DDBXuIal85uDB+qbXs
    kxOGcfpfbKz4WPfNVQnABcU7TtF2Bzmp3LnMNpY7RnVQDBVH+8Af6QcbVUH2omk9
    Xb3bV/L3pzTceY5zBPdxevgcDqrJYIR/sNfZM39XliaGTiufO4ksXZfUT8eIq53B
    uOE2qNWYR09BGv970OdJoDSjGdHrMlw1sdNKsZ94btNsEyRwDp3YY2JHpjfCI+Ou
    BWJkbxM3ybmdLvVAXllxMdsmawB4in7wYi6arPhKfv+88CsiaiuHSZyU86ZDf9ia
    61hFf/7suqAk1KRQld6A6G33E1PwVcLjr7TbmLzBvmnasdFR4o6Nuuo7ICXE2koT
    QnQflrwm8vY2lho0hWr0Z5IGLSF4bHyRldSyI2eXTUt04VZGLgLYWLpl2mEEywjO
    8EcVgQ22WwOvrHr1c7OzMg3wkb4FWchvGwIDAQABo4GIMIGFMAsGA1UdDwQEAwIE
    sDATBgNVHSUEDDAKBggrBgEFBQcDATBCBgNVHREEOzA5ghFjbm9lLmxvY2FsdGVz
    dC5tZYITKi5jbm9lLmxvY2FsdGVzdC5tZYIJbG9jYWxob3N0hwR/AAABMB0GA1Ud
    DgQWBBQrUbvGmvhBPpb8Hl63wEdYKeI6RTANBgkqhkiG9w0BAQsFAAOCAgEAk3ia
    glywSaYex9p99Vcc7XSYHeivmlA3aloWtJ7C7qm17Sjoj1JyAP7x8+jIhowXvXkS
    Nj5g4+FABaPHTb/Tcgm8Gy+nHRzxi9WABlE85czsCixDPztf9ruUNRAqmTGm/g62
    NvCGzFQgQqC2ZSDEx6PIoRp8Q+cZ6e+lFaw7qyK+SScY84/A0WBwJyxAe91zjVfG
    uVKcz/ExhZ8oZzPy3AEt4aIU1N8PRq/YHFurue51MvVUWbeewbgWph+0hqdU+uOg
    Z+8ZfpwsY8Mc4PSJlKUSO82wqQm/SJY14u04wgiIjGi7LukLuzFiLp7uGA5X+VVH
    Yp0+HgHd22HC6TmykMCHCdn3p8TEfQORV762/hgTAKhBCMimjYfKRonRq2vSdRSY
    zdfhMF/Je+E5BVOiouJtJralYl/t4g+i5VCgMIrvTbC/jPIiwR6vpd9bHbYIbnNb
    FBsXFVgiHt9kRK9cfSZt8e9Fl5I7Pyel6cgaHu2u81iaqFocpaOGi3/6FtN3jxso
    xZY+V36Sr/sO2GGRaTEdiUdvZZUYaR24OjSqoopb2Lnn0hlYkpuJB1DdR5HhzlT+
    N2bZncLY88QycS9fabW3oXK1hmVbkFCDExaUXVRJfPE0fzppxZ3Y/F0ACkxl7iUG
    MyGL6lBG2tB0xLLcrgsuCDMFi3y6tn+hGvnDkSE=
    -----END CERTIFICATE-----
  '';
in {
  options.services.clusterCerts = {
    enable = mkEnableOption "Trust local Kubernetes cluster CA certificates";
  };

  config = mkIf cfg.enable {
    # Add the cluster CA to the system trust store
    # This allows curl, git, and other tools to trust HTTPS connections
    # to services using cluster-issued certificates (e.g., Attic, Gitea)
    security.pki.certificates = [ persistentCaCert ];

    # CRITICAL: Configure Nix daemon to use the system CA bundle
    # By default, Nix fetchers use pkgs.cacert directly, which doesn't include
    # custom certificates from security.pki.certificates
    # See: https://github.com/NixOS/nixpkgs/issues/101119
    nix.settings.ssl-cert-file = "/etc/ssl/certs/ca-certificates.crt";

    # Also set for systemd service environment (belt and suspenders)
    systemd.services.nix-daemon.environment.NIX_SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt";
  };
}
