# Feature 129: Grafana Alloy - Unified OpenTelemetry Collector
#
# Receives OTLP telemetry on port 4318 and forwards it to the hub Kubernetes
# observability stack (otel-collector) over Tailscale. Optional node-exporter
# metrics and journald logs can be forwarded to Mimir/Loki when those endpoints
# are configured (both default empty — the hub K8s otel-collector is the
# canonical sink).
#
# NOTE: The per-CLI MLflow trace routing, Arize Phoenix export, Beyla span
# filtering, and spanmetrics connector were removed in 2026-07 — they had no
# producers after the OTEL interceptor retirement (commit 9093519b) and the
# spanmetrics connector was erroring every 60s into an empty metrics sink.
# AI-session state is now tracked natively via herdr, not OTEL.
#
# Architecture:
#   Clients → Alloy :4318 → [batch] → hub K8s OTEL Collector (Tailscale)
#   System  → node exporter → Alloy → Mimir (when mimirEndpoint set)
#   Journald → Alloy → Loki (when lokiEndpoint set)
#
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.grafana-alloy;

  # Generate journal source blocks for each configured unit
  journalSourceBlocks = concatMapStringsSep "\n\n" (unit:
    let
      # Convert unit name to valid identifier (replace dots and hyphens)
      safeName = replaceStrings ["-" "."] ["_" "_"] (removeSuffix ".service" unit);
      serviceName = removeSuffix ".service" unit;
    in ''
      loki.source.journal "${safeName}" {
        path    = "/var/log/journal"
        matches = "_SYSTEMD_UNIT=${unit}"

        labels = {
          job     = "systemd-journal",
          service = "${serviceName}",
        }

        forward_to = [loki.relabel.add_host.receiver]
      }''
  ) cfg.journaldUnits;

  # Generate the complete Alloy configuration
  alloyConfig = pkgs.writeText "alloy-config.alloy" ''
    // Grafana Alloy Configuration
    // Generated by NixOS module: Feature 129
    // DO NOT EDIT - managed by nixos-rebuild

    // =============================================================================
    // Live Debugging - Enable debug UI at http://localhost:12345
    // =============================================================================

    livedebugging {
      enabled = true
    }

    // =============================================================================
    // OTLP Receiver - Receives telemetry from apps and other OTLP producers
    // =============================================================================

    otelcol.receiver.otlp "default" {
      http {
        endpoint = "0.0.0.0:${toString cfg.otlpPort}"
      }

      output {
        metrics = [otelcol.processor.batch.default.input]
        logs    = [otelcol.processor.batch.default.input]
        traces  = [otelcol.processor.transform.enrich_spans.input]
      }
    }

    // =============================================================================
    // Transform Processor - Backfill host.name so the hub can discriminate hosts
    // =============================================================================

    otelcol.processor.transform "enrich_spans" {
      error_mode = "ignore"

      trace_statements {
        context = "resource"
        statements = [
          // Backfill host.name resource attribute when the emitter omitted it.
          "set(attributes[\"host.name\"], \"${config.networking.hostName}\") where attributes[\"host.name\"] == nil",
        ]
      }

      output {
        traces = [otelcol.processor.batch.default.input]
      }
    }

    // =============================================================================
    // Batch Processor - Buffer and batch telemetry for efficiency
    // =============================================================================

    otelcol.processor.batch "default" {
      send_batch_size     = 1000
      timeout             = "10s"
      send_batch_max_size = 2000  // Memory limit ~100MB worth of telemetry

      output {
        metrics = [
          ${optionalString (cfg.mimirEndpoint != "") "otelcol.exporter.prometheus.mimir.input,"}
        ]
        logs = [
          otelcol.exporter.otlphttp.k8s.input,
        ]
        traces = [
          otelcol.exporter.otlphttp.k8s.input,
        ]
      }
    }

    // =============================================================================
    // Exporters - Send to remote K8s and optional metrics sink
    // =============================================================================

    ${optionalString (cfg.mimirEndpoint != "") ''
    // Bridge: OTLP Metrics -> Prometheus Remote Write
    otelcol.exporter.prometheus "mimir" {
      forward_to = [prometheus.remote_write.k8s.receiver]
    }
    ''}

    // Remote: Kubernetes OTEL Collector via Tailscale
    otelcol.exporter.otlphttp "k8s" {
      client {
        endpoint = "${cfg.k8sEndpoint}"
        headers = {
          "X-Scope-OrgID" = "anonymous",
        }
      }

      retry_on_failure {
        enabled          = true
        initial_interval = "5s"
        max_interval     = "30s"
        max_elapsed_time = "5m"
      }

      sending_queue {
        enabled       = true
        num_consumers = 10
        queue_size    = 5000
      }
    }

    ${optionalString (cfg.enableNodeExporter && cfg.mimirEndpoint != "") ''
    // =============================================================================
    // Node Exporter - System metrics (CPU, memory, disk, network)
    // Requires both enableNodeExporter AND a non-empty mimirEndpoint —
    // collection without a forward target would just consume CPU for nothing.
    // =============================================================================

    prometheus.exporter.unix "default" {
      // Default collectors: cpu, diskstats, filesystem, loadavg, meminfo, netdev, etc.
    }

    prometheus.scrape "node" {
      targets    = prometheus.exporter.unix.default.targets
      forward_to = [prometheus.remote_write.k8s.receiver]

      scrape_interval = "15s"
    }

    prometheus.remote_write "k8s" {
      endpoint {
        url = "${cfg.mimirEndpoint}/api/v1/push"
        send_exemplars = true
        headers = {
          "X-Scope-OrgID" = "anonymous",
        }
      }
    }
    ''}

    ${optionalString (cfg.enableJournald && cfg.lokiEndpoint != "") ''
    // =============================================================================
    // Journald - Log collection from systemd services
    // Requires both enableJournald AND a non-empty lokiEndpoint — collection
    // without a forward target would just buffer journald reads for nothing.
    // =============================================================================

    ${journalSourceBlocks}

    // Add hostname to all logs
    loki.relabel "add_host" {
      forward_to = [loki.write.k8s.receiver]

      rule {
        source_labels = ["__journal__hostname"]
        target_label  = "host"
      }

      rule {
        source_labels = ["__journal_priority_keyword"]
        target_label  = "level"
      }
    }

    loki.write "k8s" {
      endpoint {
        url = "${cfg.lokiEndpoint}/loki/api/v1/push"
        headers = {
          "X-Scope-OrgID" = "anonymous",
        }
      }
    }
    ''}
  '';
in
{
  options.services.grafana-alloy = {
    enable = mkEnableOption "Grafana Alloy telemetry collector";

    package = mkOption {
      type = types.package;
      default = pkgs.grafana-alloy;
      description = "Grafana Alloy package to use";
    };

    configFile = mkOption {
      type = types.nullOr types.path;
      default = null;
      description = "Path to custom Alloy configuration file. If null, generates from options.";
    };

    otlpPort = mkOption {
      type = types.port;
      default = 4318;
      description = "OTLP HTTP receiver port (standard: 4318)";
    };

    k8sEndpoint = mkOption {
      type = types.str;
      # The hub cluster is the canonical observability sink: it runs the
      # central otel-collector + otel-clickhouse + grafana + tempo stack
      # that spokes already forward to via clickhouse-hub-egress. Routing
      # host Alloy at the hub-side Tailscale LoadBalancer bypasses the
      # spokes entirely. Plain HTTP on 4318 because this is a Tailscale
      # LoadBalancer Service (WireGuard already encrypts the link), not an
      # Ingress.
      default = "http://otel-collector-hub.tail286401.ts.net:4318";
      description = "Kubernetes OTEL collector endpoint (Tailscale LoadBalancer Service on hub).";
    };

    lokiEndpoint = mkOption {
      type = types.str;
      default = "";
      description = ''
        Loki push endpoint for journald log forwarding. Empty default means
        logs are not forwarded — set explicitly when a reachable Loki is
        available on the tailnet (e.g. the hub LGTM stack).
      '';
    };

    mimirEndpoint = mkOption {
      type = types.str;
      default = "";
      description = ''
        Mimir remote_write endpoint for node-exporter metrics. Empty default
        means metrics are not forwarded. Set explicitly when a reachable Mimir
        is available on the tailnet.
      '';
    };

    enableNodeExporter = mkOption {
      type = types.bool;
      default = true;
      description = "Enable system metrics collection via node exporter (only renders when mimirEndpoint is set)";
    };

    enableJournald = mkOption {
      type = types.bool;
      default = true;
      description = "Enable journald log collection (only renders when lokiEndpoint is set)";
    };

    journaldUnits = mkOption {
      type = types.listOf types.str;
      default = [
        "i3-project-daemon.service"
        "grafana-alloy.service"
      ];
      description = "Systemd units to collect logs from (when lokiEndpoint is set)";
    };

    stopTimeout = mkOption {
      type = types.str;
      default = "10s";
      description = ''
        Maximum time to wait for Alloy to shutdown gracefully. A shorter
        timeout (10-30s) is recommended since data loss on shutdown is
        generally acceptable.
      '';
    };
  };

  config = mkIf cfg.enable {
    # Ensure package is available
    environment.systemPackages = [ cfg.package ];

    # Install configuration file
    environment.etc."alloy/config.alloy".source =
      if cfg.configFile != null then cfg.configFile else alloyConfig;

    # Systemd service for Grafana Alloy
    systemd.services.grafana-alloy = {
      description = "Grafana Alloy - OpenTelemetry Collector";
      documentation = [ "https://grafana.com/docs/alloy/" ];

      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "simple";
        ExecStart = "${cfg.package}/bin/alloy run /etc/alloy/config.alloy";
        Restart = "always";
        RestartSec = "5s";

        # Limit shutdown wait time - telemetry data loss on reboot is acceptable
        TimeoutStopSec = cfg.stopTimeout;

        # Security hardening
        DynamicUser = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        NoNewPrivileges = true;

        # Need read access to journald
        SupplementaryGroups = [ "systemd-journal" ];
        ReadOnlyPaths = [ "/var/log/journal" ];

        # Working directory for any state
        StateDirectory = "grafana-alloy";
        WorkingDirectory = "/var/lib/grafana-alloy";

        # Memory limit per spec (200MB)
        MemoryMax = "200M";
      };
    };

    # cfg.otlpPort=4318 is local-only by design. No tailnet exposure is needed.
  };
}
