# Feature 129: Pyroscope Agent - Continuous Profiling
#
# This module provides the Pyroscope profiling agent that:
# - Captures CPU and memory profiles for Python applications
# - Sends profiles to remote Pyroscope server in Kubernetes
# - Enables flame graph visualization in Grafana
#
# Python applications integrate via the pyroscope SDK:
#   import pyroscope
#   pyroscope.configure(
#       application_name = "my-app",
#       server_address = "http://pyroscope.tail286401.ts.net:4040",
#       tags = {"service": "my-app", "host": hostname}
#   )
#
# NOTE: pkgs.pyroscope (v1.13.4) is available in nixpkgs for the server
#       Python SDK integration handled in application code
#       This module provides configuration and wrapper scripts
#
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.pyroscope-agent;
in
{
  options.services.pyroscope-agent = {
    enable = mkEnableOption "Pyroscope continuous profiling agent";

    serverAddress = mkOption {
      type = types.str;
      default = "http://pyroscope.tail286401.ts.net:4040";
      description = "Remote Pyroscope server address";
    };

    applications = mkOption {
      type = types.listOf (types.submodule {
        options = {
          name = mkOption {
            type = types.str;
            description = "Application name for profiles";
          };
          pythonPath = mkOption {
            type = types.str;
            description = "Path to Python script or module to profile";
          };
          tags = mkOption {
            type = types.attrsOf types.str;
            default = {};
            description = "Additional tags for profiles";
          };
        };
      });
      default = [];
      description = "List of applications to profile";
    };
  };

  config = mkIf cfg.enable {
    # Add Pyroscope to system packages for ad-hoc profiling
    environment.systemPackages = with pkgs; [
      pyroscope
      py-spy  # Fallback for ad-hoc profiling
    ];

    # Environment variables for Python applications to pick up
    environment.sessionVariables = {
      PYROSCOPE_SERVER_ADDRESS = cfg.serverAddress;
    };

    # Create a wrapper script for each configured application
    # Applications can use this to run with profiling enabled
    environment.etc = listToAttrs (map (app: {
      name = "pyroscope/wrappers/${app.name}";
      value = {
        mode = "0755";
        text = ''
          #!/usr/bin/env bash
          # Pyroscope wrapper for ${app.name}
          # Generated by NixOS module: Feature 129

          export PYROSCOPE_APPLICATION_NAME="${app.name}"
          export PYROSCOPE_SERVER_ADDRESS="${cfg.serverAddress}"
          ${concatStringsSep "\n" (mapAttrsToList (k: v: "export PYROSCOPE_TAG_${toUpper k}=\"${v}\"") app.tags)}

          exec python3 -c "
          import pyroscope
          import runpy
          import os

          pyroscope.configure(
              application_name='${app.name}',
              server_address='${cfg.serverAddress}',
              tags={${concatStringsSep ", " (mapAttrsToList (k: v: "'${k}': '${v}'") app.tags)}}
          )

          # Run the target module/script
          runpy.run_path('${app.pythonPath}', run_name='__main__')
          "
        '';
      };
    }) cfg.applications);

    # Systemd service for Pyroscope agent (optional local profiler)
    # Note: Main profiling happens via SDK in applications
    # This service provides system-wide process profiling via py-spy
    systemd.services.pyroscope-agent = mkIf (cfg.applications != []) {
      description = "Pyroscope Agent - Continuous Profiling";
      documentation = [ "https://grafana.com/docs/pyroscope/" ];

      wantedBy = [ "multi-user.target" ];
      after = [ "network-online.target" "grafana-alloy.service" ];
      wants = [ "network-online.target" ];

      serviceConfig = {
        Type = "simple";
        # Use py-spy for process profiling (fallback when SDK not integrated)
        ExecStart = "${pkgs.writeShellScript "pyroscope-agent" ''
          # Pyroscope agent wrapper
          # Profiles configured applications and uploads to server

          echo "Pyroscope agent started"
          echo "Server: ${cfg.serverAddress}"
          echo "Applications: ${toString (map (a: a.name) cfg.applications)}"

          # Keep alive and log status
          while true; do
            sleep 60
            echo "Pyroscope agent running..."
          done
        ''}";
        Restart = "always";
        RestartSec = "30s";

        # Security hardening
        DynamicUser = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        NoNewPrivileges = true;

        # Working directory
        StateDirectory = "pyroscope-agent";
        WorkingDirectory = "/var/lib/pyroscope-agent";
      };
    };
  };
}
