# Simple NixOS configuration for Hetzner Cloud
{ config, lib, pkgs, ... }:

{
  imports = [
    # This will be generated by nixos-generate-config
    ./hardware-configuration.nix
  ];

  # Boot loader
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  
  # Use predictable interface names (eth0)
  boot.kernelParams = [ "net.ifnames=0" ];

  # Hostname
  networking.hostName = "nixos-hetzner";
  
  # Simple DHCP for all interfaces (works perfectly with Hetzner)
  networking.useDHCP = true;

  # Time zone
  time.timeZone = "UTC";

  # Enable SSH
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "prohibit-password";
      PasswordAuthentication = false;
    };
  };

  # Firewall
  networking.firewall = {
    enable = true;
    allowedTCPPorts = [ 22 ];
  };

  # Root user SSH key (for initial access)
  users.users.root = {
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzhOKvFTkdSY8/WpeOxd7ZTII7I+klKhiIJxRdMfM5+ vpittamp@devcontainer"
    ];
  };

  # Your user account
  users.users.vpittamp = {
    isNormalUser = true;
    description = "Vinod Pittampalli";
    extraGroups = [ "wheel" ];
    openssh.authorizedKeys.keys = [
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDzhOKvFTkdSY8/WpeOxd7ZTII7I+klKhiIJxRdMfM5+ vpittamp@devcontainer"
    ];
  };

  # Allow sudo without password for wheel group
  security.sudo.wheelNeedsPassword = false;

  # Basic packages
  environment.systemPackages = with pkgs; [
    vim
    git
    wget
    curl
    tmux
    htop
    tailscale
  ];

  # Enable Tailscale
  services.tailscale = {
    enable = true;
    openFirewall = true;
  };

  # Enable flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  # This value determines the NixOS release with which your system is compatible
  system.stateVersion = "25.05";
}