# Ultra-minimal NixOS configuration for M1 MacBook Pro
# Absolute minimum to get a bootable system
# No Tailscale, minimal packages, basic functionality only
{ config, lib, pkgs, ... }:

{
  imports = [
    # Hardware configuration generated by installer
    ./hardware-configuration.nix
  ];

  # Boot - minimal settings
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;
  boot.plymouth.enable = false;
  
  # System version
  system.stateVersion = "25.11";

  # Basic networking
  networking.hostName = "nixos-m1";
  networking.useDHCP = lib.mkDefault true;

  # Time zone
  time.timeZone = "America/Los_Angeles";

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";

  # User account
  users.users.vpittamp = {
    isNormalUser = true;
    description = "Vinod Pittampalli";
    extraGroups = [ "wheel" ];
    initialPassword = "changeme";
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Absolute minimum packages
  environment.systemPackages = with pkgs; [
    vim
    wget
    curl
  ];

  # Enable OpenSSH only
  services.openssh = {
    enable = true;
    settings = {
      PermitRootLogin = "yes";
      PasswordAuthentication = true;
    };
  };

  # Basic sudo
  security.sudo.enable = true;
}