# Ultra-minimal NixOS configuration for M1 MacBook Pro
# Based on installer-generated configuration to avoid compatibility issues
# This is the safest configuration to get a bootable system
{ config, lib, pkgs, ... }:

{
  imports = [
    # Hardware configuration generated by installer
    ./hardware-configuration.nix
  ];

  # Boot configuration - minimal and safe
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = false;
  
  # Disable anything that might cause issues
  boot.plymouth.enable = false;
  boot.kernelParams = [ "nomodeset" ];  # Disable graphics mode setting
  
  # Use standard kernel package
  boot.kernelPackages = pkgs.linuxPackages;

  # Basic networking
  networking.hostName = "nixos-m1";
  networking.useDHCP = lib.mkDefault true;

  # Time zone
  time.timeZone = "America/Los_Angeles";

  # Locale
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_NAME = "en_US.UTF-8";
    LC_NUMERIC = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_TELEPHONE = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
  };

  # Console
  console.keyMap = "us";

  # User account
  users.users.vpittamp = {
    isNormalUser = true;
    description = "Vinod Pittampalli";
    extraGroups = [ "wheel" ];
    # Set initial password
    initialPassword = "changeme";
  };

  # Allow unfree packages
  nixpkgs.config.allowUnfree = true;

  # Minimal system packages - only essentials
  environment.systemPackages = with pkgs; [
    vim
    wget
  ];

  # Enable OpenSSH daemon
  services.openssh.enable = true;
  
  # Enable Tailscale
  services.tailscale.enable = true;

  # System state version - DO NOT CHANGE
  system.stateVersion = "25.11";
}