openapi: 3.0.3
info:
  title: i3pm Repository Discovery API
  description: |
    CLI and IPC API for structured git repository management with bare repos
    and sibling worktrees. Part of Feature 100.
  version: 1.0.0
  contact:
    name: Feature 100
    url: /specs/100-automate-project-and/

servers:
  - url: unix:///run/i3-project-daemon/daemon.sock
    description: i3pm daemon Unix socket (JSON-RPC)

paths:
  /clone:
    post:
      operationId: clone
      summary: Clone repository with bare setup
      description: |
        Clone a GitHub repository using bare clone pattern with automatic
        main worktree creation.

        CLI: `i3pm clone <url>`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CloneRequest'
            examples:
              ssh:
                summary: SSH URL
                value:
                  url: "git@github.com:vpittamp/nixos.git"
              https:
                summary: HTTPS URL
                value:
                  url: "https://github.com/PittampalliOrg/api.git"
      responses:
        '200':
          description: Clone successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloneResponse'
        '400':
          description: Invalid URL or repository already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /discover:
    post:
      operationId: discover
      summary: Discover all repositories and worktrees
      description: |
        Scan configured account directories for bare repositories and
        their worktrees. Updates the repository cache.

        CLI: `i3pm discover`
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiscoverRequest'
      responses:
        '200':
          description: Discovery complete
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiscoverResponse'

  /repo/list:
    get:
      operationId: listRepositories
      summary: List all discovered repositories
      description: |
        Return all repositories discovered in configured account directories.

        CLI: `i3pm repo list`
      parameters:
        - name: account
          in: query
          description: Filter by account name
          schema:
            type: string
      responses:
        '200':
          description: List of repositories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RepositoryListResponse'

  /repo/{account}/{repo}:
    get:
      operationId: getRepository
      summary: Get repository details
      description: |
        Get detailed information about a specific repository including
        all worktrees.

        CLI: `i3pm repo get vpittamp/nixos`
      parameters:
        - name: account
          in: path
          required: true
          schema:
            type: string
        - name: repo
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Repository details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BareRepository'
        '404':
          description: Repository not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /worktree/create:
    post:
      operationId: createWorktree
      summary: Create a new worktree
      description: |
        Create a new worktree as sibling to main in the current repository
        context. Must be run from within a worktree directory.

        CLI: `i3pm worktree create 100-feature`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorktreeCreateRequest'
      responses:
        '200':
          description: Worktree created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorktreeCreateResponse'
        '400':
          description: Invalid branch name or worktree already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /worktree/list:
    get:
      operationId: listWorktrees
      summary: List worktrees for a repository
      description: |
        List all worktrees for the current or specified repository.

        CLI: `i3pm worktree list [repo]`
      parameters:
        - name: repo
          in: query
          description: Repository qualified name (e.g., vpittamp/nixos)
          schema:
            type: string
      responses:
        '200':
          description: List of worktrees
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorktreeListResponse'

  /worktree/remove:
    delete:
      operationId: removeWorktree
      summary: Remove a worktree
      description: |
        Remove a worktree from the repository. Fails if worktree has
        uncommitted changes unless force=true.

        CLI: `i3pm worktree remove 100-feature [--force]`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorktreeRemoveRequest'
      responses:
        '200':
          description: Worktree removed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorktreeRemoveResponse'
        '400':
          description: Worktree has uncommitted changes or is main worktree
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /account/list:
    get:
      operationId: listAccounts
      summary: List configured accounts
      description: |
        List all configured GitHub accounts with their base directories.

        CLI: `i3pm account list`
      responses:
        '200':
          description: List of accounts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountListResponse'

  /account/add:
    post:
      operationId: addAccount
      summary: Add a new account
      description: |
        Add a new GitHub account configuration.

        CLI: `i3pm account add vpittamp ~/repos/vpittamp`
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountConfig'
      responses:
        '200':
          description: Account added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConfig'

components:
  schemas:
    CloneRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          description: GitHub repository URL (SSH or HTTPS)
          example: "git@github.com:vpittamp/nixos.git"
        account:
          type: string
          description: Override account detection (optional)

    CloneResponse:
      type: object
      properties:
        success:
          type: boolean
        repository:
          $ref: '#/components/schemas/BareRepository'
        path:
          type: string
          description: Path to created repository
        main_worktree:
          type: string
          description: Path to main worktree

    DiscoverRequest:
      type: object
      properties:
        accounts:
          type: array
          items:
            type: string
          description: Limit discovery to specific accounts

    DiscoverResponse:
      type: object
      properties:
        success:
          type: boolean
        discovered:
          type: integer
          description: Total items discovered
        repos:
          type: integer
          description: Number of repositories
        worktrees:
          type: integer
          description: Number of worktrees
        duration_ms:
          type: integer
          description: Discovery duration in milliseconds

    RepositoryListResponse:
      type: object
      properties:
        repositories:
          type: array
          items:
            $ref: '#/components/schemas/BareRepository'
        total:
          type: integer

    BareRepository:
      type: object
      required:
        - account
        - name
        - path
        - remote_url
      properties:
        account:
          type: string
          description: GitHub account name
        name:
          type: string
          description: Repository name
        qualified_name:
          type: string
          description: Full qualified name (account/repo)
          example: "vpittamp/nixos"
        path:
          type: string
          description: Repository container path
        remote_url:
          type: string
          description: Git remote origin URL
        default_branch:
          type: string
          description: Default branch name
          default: "main"
        worktrees:
          type: array
          items:
            $ref: '#/components/schemas/Worktree'
        discovered_at:
          type: string
          format: date-time

    Worktree:
      type: object
      required:
        - branch
        - path
      properties:
        branch:
          type: string
          description: Branch name
        path:
          type: string
          description: Worktree directory path
        commit:
          type: string
          description: Current commit hash (short)
        is_clean:
          type: boolean
          description: No uncommitted changes
        ahead:
          type: integer
          description: Commits ahead of remote
          default: 0
        behind:
          type: integer
          description: Commits behind remote
          default: 0
        is_main:
          type: boolean
          description: Is the main/master worktree

    WorktreeCreateRequest:
      type: object
      required:
        - branch
      properties:
        branch:
          type: string
          description: Branch name for new worktree
          example: "100-feature"
        from:
          type: string
          description: Base branch to create from
          default: "main"
        repo:
          type: string
          description: Repository qualified name (auto-detect if in worktree)

    WorktreeCreateResponse:
      type: object
      properties:
        success:
          type: boolean
        worktree:
          $ref: '#/components/schemas/Worktree'
        path:
          type: string
          description: Path to created worktree

    WorktreeListResponse:
      type: object
      properties:
        repository:
          type: string
          description: Repository qualified name
        worktrees:
          type: array
          items:
            $ref: '#/components/schemas/Worktree'

    WorktreeRemoveRequest:
      type: object
      required:
        - branch
      properties:
        branch:
          type: string
          description: Branch name of worktree to remove
        repo:
          type: string
          description: Repository qualified name
        force:
          type: boolean
          description: Force removal even with uncommitted changes
          default: false

    WorktreeRemoveResponse:
      type: object
      properties:
        success:
          type: boolean
        removed:
          type: string
          description: Path that was removed

    AccountConfig:
      type: object
      required:
        - name
        - path
      properties:
        name:
          type: string
          description: GitHub account/org name
          example: "vpittamp"
        path:
          type: string
          description: Base directory path
          example: "~/repos/vpittamp"
        is_default:
          type: boolean
          description: Default account for clone
          default: false
        ssh_host:
          type: string
          description: SSH host alias
          default: "github.com"

    AccountListResponse:
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/AccountConfig'

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
          enum:
            - INVALID_URL
            - REPO_EXISTS
            - REPO_NOT_FOUND
            - WORKTREE_EXISTS
            - WORKTREE_DIRTY
            - CANNOT_REMOVE_MAIN
            - ACCOUNT_NOT_FOUND
