#!/usr/bin/env python3
"""Turn a live Home Assistant into a jev function catalog.

The desktop catalog is generated by Nix, because the things it names — the
installed applications, the theme set, the shell's surfaces — change only when
the system is rebuilt. A house does not work that way. Lights are paired and
unpaired, a TV goes unavailable when it is unplugged, a script is added in the
UI at four in the afternoon. So this catalog is generated at *runtime* from
`/api/states` and written as a spec fragment the dispatcher merges.

The shape is exactly the shape Nix produces: a function is a description, an
argv template, and closed sets. Only the moment the options become known is
different.

Two things the entity list will not give you for free:

  Covers are named "Shade 5 Top", which says nothing about where they are —
  the room is in the entity_id (`cover.living_room_shade_5_top`) and nowhere
  else. So descriptions are built from both. They also come in rail pairs, one
  window per two entities; see `rail_pairs` for why that is split apart rather
  than offered as ten flat choices.

  Half the media players are duplicates or unplugged. An option the model can
  pick but the house cannot act on is worse than no option, so anything
  unavailable is left out.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from jev_api import JevError, hass_token

# Read-only domains, and the ones whose entities are machine plumbing rather
# than anything a person asks for out loud. `button.*` here is almost entirely
# "Shade 4 Calibrate" and "Shade 4 Identify".
SKIP_NAME = re.compile(r"\b(calibrate|identify|firmware|update|restart|reboot)\b", re.IGNORECASE)

# A top-down/bottom-up shade is one window and two entities: "Shade 1 Bottom"
# rises from the sill, "Shade 1 Top" comes down from the head. Both answer to
# "shade 1", so offering all ten as flat choices made "open shade 1" a coin
# flip between two options that mean almost the same thing — and a split
# distribution is exactly what the confidence gate stops the bar on, on a
# sentence that was never ambiguous to the person who said it.
RAIL = re.compile(r"^(?P<stem>.+)_(?P<rail>top|bottom)$")

# The rail word trailing a friendly name, so "Shade 1 Bottom" can be asked
# about as the whole window rather than one of its halves.
TRAILING_RAIL = re.compile(r"\s*\b(top|bottom)\b\s*$", re.IGNORECASE)

# Rooms, recovered from the entity_id because the friendly names do not always
# carry them. Longest first so `master_bedroom` wins over `bedroom`.
AREA_WORDS = [
    "master_bedroom", "living_room", "dining_room", "guest_room",
    "bathroom", "bedroom", "kitchen", "entrance", "hallway", "office",
    "garage", "basement", "patio", "porch",
]


def base_url() -> str:
    return (os.environ.get("HASS_URL") or "http://homeassistant.local:8123").rstrip("/")


def states() -> list[dict[str, Any]]:
    request = urllib.request.Request(
        f"{base_url()}/api/states",
        headers={"Authorization": f"Bearer {hass_token()}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as exc:
        raise JevError(f"Home Assistant returned HTTP {exc.code}") from None
    except urllib.error.URLError as exc:
        raise JevError(f"could not reach Home Assistant at {base_url()}: {exc.reason}") from None


def area_of(entity_id: str) -> str:
    slug = entity_id.split(".", 1)[1]
    for word in AREA_WORDS:
        if slug.startswith(word + "_") or slug == word:
            return word.replace("_", " ")
    return ""


def describe(entity: dict[str, Any]) -> str:
    """What the option says to the model.

    Friendly name plus the room when the name does not already contain it, so
    "Shade 5 Top" becomes "Shade 5 Top, in the living room" and "Kitchen Main
    Lights" is left alone rather than becoming "Kitchen Main Lights, in the
    kitchen".
    """
    entity_id = entity["entity_id"]
    name = (entity.get("attributes") or {}).get("friendly_name") or entity_id.split(".", 1)[1]
    area = area_of(entity_id)
    if area and area.split()[-1].lower() not in name.lower():
        return f"{name}, in the {area}"
    return name


def usable(entity: dict[str, Any]) -> bool:
    state = str(entity.get("state") or "").lower()
    if state in ("unavailable", "unknown"):
        return False
    name = (entity.get("attributes") or {}).get("friendly_name") or ""
    return not SKIP_NAME.search(name)


def options_for(entities: list[dict[str, Any]], domain: str) -> dict[str, Any]:
    rows = {}
    for entity in entities:
        if not entity["entity_id"].startswith(domain + ".") or not usable(entity):
            continue
        rows[entity["entity_id"]] = {"description": describe(entity)}
    return rows


def areas_with(entities: list[dict[str, Any]], domain: str) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for entity in entities:
        if not entity["entity_id"].startswith(domain + ".") or not usable(entity):
            continue
        area = area_of(entity["entity_id"])
        if area:
            grouped.setdefault(area, []).append(entity["entity_id"])
    return grouped


def rail_pairs(
    entities: list[dict[str, Any]]
) -> tuple[dict[str, dict[str, dict[str, Any]]], list[dict[str, Any]]]:
    """Covers split into rail-paired shades and everything else.

    A stem counts as a shade only when BOTH rails are present, because the argv
    composes `<stem>_<rail>`: a stem missing its partner would compose an entity
    id that does not exist, which is the one thing a closed set is supposed to
    make impossible. A lone rail is therefore demoted to an ordinary cover and
    named in full, and a house of plain blinds produces no shade functions at
    all rather than a broken one.
    """
    stems: dict[str, dict[str, dict[str, Any]]] = {}
    singles: list[dict[str, Any]] = []
    for entity in entities:
        entity_id = entity["entity_id"]
        if not entity_id.startswith("cover.") or not usable(entity):
            continue
        match = RAIL.match(entity_id)
        if match:
            stems.setdefault(match["stem"], {})[match["rail"]] = entity
        else:
            singles.append(entity)

    paired: dict[str, dict[str, dict[str, Any]]] = {}
    for stem, rails in sorted(stems.items()):
        if "top" in rails and "bottom" in rails:
            paired[stem] = rails
        else:
            singles.extend(rails.values())
    return paired, singles


def describe_shade(stem: str, rails: dict[str, dict[str, Any]]) -> str:
    """What one whole shade — both rails — is called.

    The friendly name belongs to a rail ("Shade 1 Bottom"), so the rail word is
    dropped: the choice is naming a window, and the rail is a separate question.
    """
    bottom = rails["bottom"]
    name = (bottom.get("attributes") or {}).get("friendly_name") or stem.split(".", 1)[1]
    name = TRAILING_RAIL.sub("", name).strip() or name
    area = area_of(stem)
    if area and area.split()[-1].lower() not in name.lower():
        return f"{name}, in the {area}"
    return name


def build(entities: list[dict[str, Any]], call_bin: str) -> dict[str, Any]:
    functions: dict[str, Any] = {}

    def fn(name, summary, description, argv, arguments=None, confirm=False):
        functions[name] = {
            "summary": summary, "description": description, "argv": argv,
            "arguments": arguments or {}, "confirm": confirm,
        }

    lights = options_for(entities, "light")
    if lights:
        fn("set_light", "Turn one light on or off",
           "Switch a single named light or group of bulbs on or off. Use this when the "
           "user names a particular light or a particular room's lights.",
           [call_bin, "light", "%state%", "%light%"],
           {"light": {"type": "choice", "question": "Which light did they name?",
                      "options": lights},
            "state": {"type": "choice",
                      "question": "Do they want the light on or off?",
                      "options": {"turn_on": {"description": "on, lit, bright, switch it on"},
                                  "turn_off": {"description": "off, out, dark, kill it, switch it off"},
                                  "toggle": {"description": "flip it, whichever way it is now"}}}})

        fn("dim_light", "Set a light to a brightness",
           "Put a named light at a particular brightness rather than simply on or off — "
           "dim, low, half, bright, full.",
           [call_bin, "light", "turn_on", "%light%", "brightness_pct=%level%"],
           {"light": {"type": "choice", "question": "Which light did they name?",
                      "options": lights},
            "level": {"type": "choice",
                      "question": "How bright do they want it?",
                      "options": {"10": {"description": "very dim, barely on, night light"},
                                  "30": {"description": "dim, low, soft"},
                                  "50": {"description": "half, medium"},
                                  "75": {"description": "bright"},
                                  "100": {"description": "full, all the way up, as bright as it goes"}}}})

    light_areas = areas_with(entities, "light")
    if light_areas:
        fn("set_room_lights", "Turn every light in a room on or off",
           "Switch all of the lights in a whole room at once — the kitchen lights, the "
           "bedroom lights — rather than one named fitting.",
           [call_bin, "light", "%state%", "%room%"],
           {"room": {"type": "choice",
                     "question": "Which room's lights are they talking about?",
                     "options": {area: {"description": f"every light in the {area}",
                                        "value": ids}
                                 for area, ids in sorted(light_areas.items())}},
            "state": {"type": "choice", "question": "On or off?",
                      "options": {"turn_on": {"description": "on, lit, bright"},
                                  "turn_off": {"description": "off, out, dark"},
                                  "toggle": {"description": "flip them"}}}})

        fn("all_lights_off", "Turn off every light in the house",
           "Switch off all the lights everywhere at once — lights out, turn everything "
           "off, goodnight. Not for a single room.",
           [call_bin, "light", "turn_off", "all"])

    switches = options_for(entities, "switch")
    if switches:
        fn("set_switch", "Turn a switch on or off",
           "Switch something that is not a light on or off — a plug, a fan, a mute "
           "control, a mode.",
           [call_bin, "switch", "%state%", "%switch%"],
           {"switch": {"type": "choice", "question": "Which switch did they name?",
                       "options": switches},
            "state": {"type": "choice", "question": "On or off?",
                      "options": {"turn_on": {"description": "on, enable, start it"},
                                  "turn_off": {"description": "off, disable, stop it"},
                                  "toggle": {"description": "flip it"}}}})

    # ---- window coverings ------------------------------------------------
    # Three things the flat "pick one of ten entities" shape got wrong, and
    # what replaces each:
    #
    #   "open shade 1" had to choose between Shade 1 Top and Shade 1 Bottom on
    #   descriptions that differ by one word. Identity and rail are now two
    #   questions: which shade (unambiguous — the numbers are unique house-wide)
    #   and, separately, whether the sentence named a rail at all. It usually
    #   did not, and the default that stands is the bottom rail, which is what
    #   "the shade" means to the person saying it.
    #
    #   "open shade 1 to 25%" could not be said at all — the only actions were
    #   open, close and stop, though every one of these reports SET_POSITION.
    #   Height is its own function for the same reason `dim_light` is separate
    #   from `set_light`: an action argument that silently changes which service
    #   is called is a coupling two answers have to agree on.
    #
    #   Room-wide commands moved both rails, so "open the living room shades"
    #   also raised the upper halves nobody asked about.
    paired, singles = rail_pairs(entities)

    # Shared by both shade functions. `default` is a *value*, not an option key
    # — it is substituted into the argv untouched — so it spells the suffix.
    rail = {
        "type": "choice",
        "question": "Did they mean the lower half of the shade or the upper half?",
        "options": {
            "bottom": {"value": "_bottom",
                       "description": "The lower half, which rises from the window sill. This is "
                                      "the one a bare 'shade 3' means, with no rail named"},
            "top": {"value": "_top",
                    "description": "The upper half, which comes down from the top of the window. "
                                   "Only when the command says top or upper"},
        },
        "stated": "Does the command actually say top or bottom — upper or lower — "
                  "rather than just naming the shade?",
        "default": "_bottom",
    }

    # Round numbers people say out loud, as structured criteria: TypeSafe
    # accepts an object per option and reserves none of its field names, which
    # is the documented way to separate options that sit next to each other in
    # meaning.
    #
    # Levels were chosen by measuring, not by taste. A 10 percent level reads
    # as the same vague "barely open" idea as 25 and split the user's own
    # example — "open shade 1 to 25%" — 0.62/0.37, then 0.52/0.47 once both
    # descriptions led with their numeral, and still only reached 0.60 with
    # `not_for` clauses holding them apart. Dropping it and folding "a crack"
    # into the quarter puts that sentence at 0.89 and lifts 75 percent from
    # 0.77 to 0.85. 90 survives the same test at 0.69 because "nearly all the
    # way up" and "fully open" are further apart than a crack and a quarter.
    #
    # A closed set cannot spell 43%, so the question asks for the nearest
    # instead of pretending otherwise. TypeSafe's Score primitive would
    # interpolate it — its probability-weighted mean across ordered levels is
    # very nearly a percentage — but the fraction it returns measures the
    # model's *uncertainty between adjacent levels*, not a quantity someone
    # asked for, and reading it as a position would mean exempting this
    # argument from the confidence gate every other one obeys. A shade 7% off
    # is not worth that hole.
    position = {
        "type": "choice",
        "question": "How far open should the shade end up? Pick the nearest.",
        "options": {
            "0": {"description": {
                "what": "Fully closed, all the way down, the window completely covered",
                "examples": ["shut the shade", "all the way down", "close it completely"]}},
            "25": {"description": {
                "what": "A quarter of the way up — also a crack, barely open. Around 25 percent",
                "examples": ["25%", "a quarter of the way", "to 25 percent",
                             "just a crack", "barely open"]}},
            "50": {"description": {
                "what": "Halfway — half open, the middle. Around 50 percent",
                "not_for": "75 percent, which is three quarters; a stray 5 elsewhere in the "
                           "sentence, such as a shade's number, is not the position",
                "examples": ["halfway", "half open", "50%", "to the middle"]}},
            "75": {"description": {
                "what": "Three quarters of the way up. Around 75 percent",
                "not_for": "Half open, which is 50, or nearly all the way up, which is nearer 90",
                "examples": ["75%", "to 75 percent", "three quarters of the way",
                             "open shade 5 to 75%", "mostly open"]}},
            "90": {"description": {
                "what": "Nearly all the way up, but not fully. Around 90 percent",
                "not_for": "Three quarters, which is nearer 75, or fully open, which is 100",
                "examples": ["90%", "nearly all the way up", "almost fully open"]}},
            "100": {"description": {
                "what": "Fully open, all the way up, the window uncovered",
                "examples": ["all the way up", "wide open", "100 percent", "fully open"]}},
        },
    }

    # The exclusions have to be symmetric. With one only on `stop`, "stop shade
    # 1" still went to `close` at 0.59 — "shut it" reads as a plausible gloss of
    # "stop it", and nothing on the close side said otherwise. Each option now
    # names what it is not, which is what separates a command about ending up
    # covered from one about interrupting movement.
    move_actions = {
        "type": "choice",
        "question": "What should the shade do?",
        "options": {
            "open_cover": {"description": {
                "what": "Raise it all the way up, uncovering the window",
                "not_for": "Halting a shade that is already moving, which is stop",
                "examples": ["open it", "put it up", "raise shade 1", "let the light in"]}},
            "close_cover": {"description": {
                "what": "Lower it all the way down, covering the window",
                "not_for": "Halting a shade that is already moving, which is stop — closing is "
                           "about where it ends up, not about interrupting it",
                "examples": ["close it", "put it down", "shut the shade", "block the light"]}},
            "stop_cover": {"description": {
                "what": "Halt a shade that is moving right now and leave it wherever it has "
                        "got to, neither open nor shut",
                "not_for": "Lowering or closing the shade; stopping names the interruption, "
                           "not the end position",
                "examples": ["stop", "stop shade 1", "halt it", "stop the shade there",
                             "that is far enough"]}},
        },
    }

    if paired:
        shades = {stem: {"description": describe_shade(stem, rails)}
                  for stem, rails in paired.items()}
        which_shade = {"type": "choice", "question": "Which shade did they name?",
                       "options": shades}

        fn("move_shade", "Open or close a shade",
           "Raise, lower or stop one named shade — open shade 1, close shade 3, stop "
           "it there. Use this when the command names no particular height.",
           [call_bin, "cover", "%action%", "%shade%%rail%"],
           {"shade": which_shade, "rail": rail, "action": move_actions})

        fn("set_shade_position", "Set a shade to a particular height",
           "Put one named shade at a particular height rather than fully open or shut "
           "— open shade 1 to 25 percent, put shade 3 halfway, bring shade 2 down to a "
           "quarter. Use this whenever a fraction or a percentage is named.",
           [call_bin, "cover", "set_cover_position", "%shade%%rail%", "position=%position%"],
           {"shade": which_shade, "rail": rail, "position": position})

    if singles:
        # Anything without a rail partner: a plain blind, a curtain, or half a
        # shade whose other rail is unavailable. Named in full, no rail question.
        covers = {entity["entity_id"]: {"description": describe(entity)}
                  for entity in sorted(singles, key=lambda e: e["entity_id"])}
        which_cover = {"type": "choice", "question": "Which blind or curtain did they mean?",
                       "options": covers}

        fn("move_cover", "Open or close a blind or curtain",
           "Raise, lower or stop a window covering that is one piece — a roller blind, "
           "a curtain — rather than a two-rail shade.",
           [call_bin, "cover", "%action%", "%cover%"],
           {"cover": which_cover, "action": move_actions})

        fn("set_cover_position", "Set a blind or curtain to a particular height",
           "Put a one-piece window covering at a particular height rather than fully "
           "open or shut.",
           [call_bin, "cover", "set_cover_position", "%cover%", "position=%position%"],
           {"cover": which_cover, "position": position})

    # Room-wide. The targets are the bottom rails plus any one-piece covers:
    # "open the living room shades" means the halves that cover the window, not
    # the upper ones. A top rail is reached by naming its shade, which is the
    # same rule the single-shade functions follow. (The rail cannot be a
    # separate argument here the way it is above, because a room expands to a
    # list of entity ids and a list cannot be composed inside a token.)
    cover_areas: dict[str, list[str]] = {}
    for stem, rails in paired.items():
        area = area_of(stem)
        if area:
            cover_areas.setdefault(area, []).append(rails["bottom"]["entity_id"])
    for entity in singles:
        area = area_of(entity["entity_id"])
        if area:
            cover_areas.setdefault(area, []).append(entity["entity_id"])

    if cover_areas:
        which_room = {"type": "choice", "question": "Which room's shades?",
                      "options": {area: {"description": f"every shade in the {area}",
                                         "value": sorted(ids)}
                                  for area, ids in sorted(cover_areas.items())}}

        fn("move_room_covers", "Open or close every shade in a room",
           "Raise or lower all of the shades in a whole room at once, rather than one "
           "named shade.",
           [call_bin, "cover", "%action%", "%room%"],
           {"room": which_room, "action": move_actions})

        fn("set_room_cover_position", "Set every shade in a room to a height",
           "Put all of a room's shades at the same particular height — the living room "
           "shades halfway, the bedroom shades to a quarter.",
           [call_bin, "cover", "set_cover_position", "%room%", "position=%position%"],
           {"room": which_room, "position": position})

    players = options_for(entities, "media_player")
    if players:
        fn("control_media_player", "Control a TV or speaker",
           "Act on something that plays — a television, a speaker, a streaming box: "
           "pause it, skip on, turn it off, change its volume.",
           [call_bin, "media_player", "%action%", "%player%"],
           {"player": {"type": "choice", "question": "Which TV or speaker did they name?",
                       "options": players},
            "action": {"type": "choice", "question": "What should it do?",
                       "options": {
                           "media_play_pause": {"description": "pause, resume, play, stop for a moment"},
                           "media_next_track": {"description": "skip, next, move on"},
                           "media_previous_track": {"description": "back, previous, play that again"},
                           "volume_up": {"description": "louder, turn it up"},
                           "volume_down": {"description": "quieter, turn it down"},
                           "turn_off": {"description": "switch it off entirely"},
                           "turn_on": {"description": "switch it on"}}}})

    scripts = options_for(entities, "script")
    if scripts:
        fn("run_home_script", "Run a saved Home Assistant script",
           "Run one of the saved routines in the house — sending a key to a TV, "
           "notifying a phone, a multi-step sequence someone saved.",
           [call_bin, "script", "turn_on", "%script%"],
           {"script": {"type": "choice", "question": "Which saved routine did they ask for?",
                       "options": scripts}})

    scenes = options_for(entities, "scene")
    if scenes:
        fn("activate_scene", "Set a scene",
           "Put the house into a named arrangement of lights and devices — movie night, "
           "bedtime, dinner.",
           [call_bin, "scene", "turn_on", "%scene%"],
           {"scene": {"type": "choice", "question": "Which scene did they name?",
                      "options": scenes}})

    climates = options_for(entities, "climate")
    if climates:
        fn("set_thermostat_mode", "Change what the heating or cooling is doing",
           "Put the thermostat into heating, cooling, or off. Use this when no "
           "temperature is named.",
           [call_bin, "climate", "set_hvac_mode", "%thermostat%", "hvac_mode=%mode%"],
           {"thermostat": {"type": "choice", "question": "Which thermostat?",
                           "options": climates},
            "mode": {"type": "choice", "question": "Heating, cooling, or off?",
                     "options": {"heat": {"description": "heat, warmer, put the heating on"},
                                 "cool": {"description": "cool, colder, put the air conditioning on"},
                                 "off": {"description": "off, stop heating and cooling"},
                                 "heat_cool": {"description": "automatic, let it decide, keep it comfortable"}}}})

        fn("set_temperature", "Set the thermostat to a temperature",
           "Put the thermostat at a named temperature rather than changing its mode.",
           [call_bin, "climate", "set_temperature", "%thermostat%", "temperature=%degrees%"],
           {"thermostat": {"type": "choice", "question": "Which thermostat?",
                           "options": climates},
            "degrees": {"type": "choice",
                        "question": "What temperature did they ask for, in Fahrenheit?",
                        "options": {str(d): {"description": f"{d} degrees"}
                                    for d in (62, 65, 68, 70, 72, 74, 76, 78)}}})

    return {"version": 1, "source": "home-assistant", "functions": functions}


def cmd_refresh(args: argparse.Namespace) -> int:
    entities = states()
    fragment = build(entities, args.call_bin)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(".tmp")
    temporary.write_text(json.dumps(fragment, indent=1))
    os.replace(temporary, out)
    total = sum(len(f.get("arguments") or {}) for f in fragment["functions"].values())
    print(f"{len(fragment['functions'])} functions, {total} arguments -> {out}")
    if not args.quiet:
        for name, f in sorted(fragment["functions"].items()):
            sizes = ", ".join(f"{a}:{len(m.get('options') or {})}"
                              for a, m in (f.get("arguments") or {}).items())
            print(f"  {name:<24}{f['summary']}" + (f"   [{sizes}]" if sizes else ""))
    return 0


def cmd_entities(args: argparse.Namespace) -> int:
    entities = states()
    kept = [e for e in entities if usable(e)]
    print(f"{len(entities)} entities, {len(kept)} usable")
    for entity in sorted(kept, key=lambda e: e["entity_id"]):
        domain = entity["entity_id"].split(".", 1)[0]
        if args.domain and domain != args.domain:
            continue
        print(f"  {entity['entity_id']:<48}{describe(entity)[:46]:<48}{entity['state'][:14]}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ha-catalog",
        description="Generate a jev function catalog from a live Home Assistant.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    node = sub.add_parser("refresh", help="rebuild the spec fragment from the live house")
    node.add_argument("--out", default=os.environ.get("HA_FRAGMENT") or "ha.json")
    node.add_argument("--call-bin", default=os.environ.get("HA_CALL_BIN") or "ha-call")
    node.add_argument("--quiet", action="store_true")
    node.set_defaults(func=cmd_refresh)

    node = sub.add_parser("entities", help="list what the house exposes")
    node.add_argument("--domain")
    node.set_defaults(func=cmd_entities)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except JevError as exc:
        print(f"ha-catalog: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
