#!/usr/bin/env python3
"""Turn a live Home Assistant into a jev function catalog.

The desktop catalog is generated by Nix, because the things it names — the
installed applications, the theme set, the shell's surfaces — change only when
the system is rebuilt. A house does not work that way. Lights are paired and
unpaired, a TV goes unavailable when it is unplugged, a script is added in the
UI at four in the afternoon. So this catalog is generated at *runtime* from
`/api/states` and written as a spec fragment the dispatcher merges.

The shape is exactly the shape Nix produces: a function is a description, an
argv template, and closed sets. Only the moment the options become known is
different.

Two things the entity list will not give you for free:

  Covers are named "Shade 5 Top", which says nothing about where they are —
  the room is in the entity_id (`cover.living_room_shade_5_top`) and nowhere
  else. So descriptions are built from both.

  Half the media players are duplicates or unplugged. An option the model can
  pick but the house cannot act on is worse than no option, so anything
  unavailable is left out.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

from jev_api import JevError, hass_token

# Read-only domains, and the ones whose entities are machine plumbing rather
# than anything a person asks for out loud. `button.*` here is almost entirely
# "Shade 4 Calibrate" and "Shade 4 Identify".
SKIP_NAME = re.compile(r"\b(calibrate|identify|firmware|update|restart|reboot)\b", re.IGNORECASE)

# Rooms, recovered from the entity_id because the friendly names do not always
# carry them. Longest first so `master_bedroom` wins over `bedroom`.
AREA_WORDS = [
    "master_bedroom", "living_room", "dining_room", "guest_room",
    "bathroom", "bedroom", "kitchen", "entrance", "hallway", "office",
    "garage", "basement", "patio", "porch",
]


def base_url() -> str:
    return (os.environ.get("HASS_URL") or "http://homeassistant.local:8123").rstrip("/")


def states() -> list[dict[str, Any]]:
    request = urllib.request.Request(
        f"{base_url()}/api/states",
        headers={"Authorization": f"Bearer {hass_token()}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            return json.loads(response.read().decode())
    except urllib.error.HTTPError as exc:
        raise JevError(f"Home Assistant returned HTTP {exc.code}") from None
    except urllib.error.URLError as exc:
        raise JevError(f"could not reach Home Assistant at {base_url()}: {exc.reason}") from None


def area_of(entity_id: str) -> str:
    slug = entity_id.split(".", 1)[1]
    for word in AREA_WORDS:
        if slug.startswith(word + "_") or slug == word:
            return word.replace("_", " ")
    return ""


def describe(entity: dict[str, Any]) -> str:
    """What the option says to the model.

    Friendly name plus the room when the name does not already contain it, so
    "Shade 5 Top" becomes "Shade 5 Top, in the living room" and "Kitchen Main
    Lights" is left alone rather than becoming "Kitchen Main Lights, in the
    kitchen".
    """
    entity_id = entity["entity_id"]
    name = (entity.get("attributes") or {}).get("friendly_name") or entity_id.split(".", 1)[1]
    area = area_of(entity_id)
    if area and area.split()[-1].lower() not in name.lower():
        return f"{name}, in the {area}"
    return name


def usable(entity: dict[str, Any]) -> bool:
    state = str(entity.get("state") or "").lower()
    if state in ("unavailable", "unknown"):
        return False
    name = (entity.get("attributes") or {}).get("friendly_name") or ""
    return not SKIP_NAME.search(name)


def options_for(entities: list[dict[str, Any]], domain: str) -> dict[str, Any]:
    rows = {}
    for entity in entities:
        if not entity["entity_id"].startswith(domain + ".") or not usable(entity):
            continue
        rows[entity["entity_id"]] = {"description": describe(entity)}
    return rows


def areas_with(entities: list[dict[str, Any]], domain: str) -> dict[str, list[str]]:
    grouped: dict[str, list[str]] = {}
    for entity in entities:
        if not entity["entity_id"].startswith(domain + ".") or not usable(entity):
            continue
        area = area_of(entity["entity_id"])
        if area:
            grouped.setdefault(area, []).append(entity["entity_id"])
    return grouped


def build(entities: list[dict[str, Any]], call_bin: str) -> dict[str, Any]:
    functions: dict[str, Any] = {}

    def fn(name, summary, description, argv, arguments=None, confirm=False):
        functions[name] = {
            "summary": summary, "description": description, "argv": argv,
            "arguments": arguments or {}, "confirm": confirm,
        }

    lights = options_for(entities, "light")
    if lights:
        fn("set_light", "Turn one light on or off",
           "Switch a single named light or group of bulbs on or off. Use this when the "
           "user names a particular light or a particular room's lights.",
           [call_bin, "light", "%state%", "%light%"],
           {"light": {"type": "choice", "question": "Which light did they name?",
                      "options": lights},
            "state": {"type": "choice",
                      "question": "Do they want the light on or off?",
                      "options": {"turn_on": {"description": "on, lit, bright, switch it on"},
                                  "turn_off": {"description": "off, out, dark, kill it, switch it off"},
                                  "toggle": {"description": "flip it, whichever way it is now"}}}})

        fn("dim_light", "Set a light to a brightness",
           "Put a named light at a particular brightness rather than simply on or off — "
           "dim, low, half, bright, full.",
           [call_bin, "light", "turn_on", "%light%", "brightness_pct=%level%"],
           {"light": {"type": "choice", "question": "Which light did they name?",
                      "options": lights},
            "level": {"type": "choice",
                      "question": "How bright do they want it?",
                      "options": {"10": {"description": "very dim, barely on, night light"},
                                  "30": {"description": "dim, low, soft"},
                                  "50": {"description": "half, medium"},
                                  "75": {"description": "bright"},
                                  "100": {"description": "full, all the way up, as bright as it goes"}}}})

    light_areas = areas_with(entities, "light")
    if light_areas:
        fn("set_room_lights", "Turn every light in a room on or off",
           "Switch all of the lights in a whole room at once — the kitchen lights, the "
           "bedroom lights — rather than one named fitting.",
           [call_bin, "light", "%state%", "%room%"],
           {"room": {"type": "choice",
                     "question": "Which room's lights are they talking about?",
                     "options": {area: {"description": f"every light in the {area}",
                                        "value": ids}
                                 for area, ids in sorted(light_areas.items())}},
            "state": {"type": "choice", "question": "On or off?",
                      "options": {"turn_on": {"description": "on, lit, bright"},
                                  "turn_off": {"description": "off, out, dark"},
                                  "toggle": {"description": "flip them"}}}})

        fn("all_lights_off", "Turn off every light in the house",
           "Switch off all the lights everywhere at once — lights out, turn everything "
           "off, goodnight. Not for a single room.",
           [call_bin, "light", "turn_off", "all"])

    switches = options_for(entities, "switch")
    if switches:
        fn("set_switch", "Turn a switch on or off",
           "Switch something that is not a light on or off — a plug, a fan, a mute "
           "control, a mode.",
           [call_bin, "switch", "%state%", "%switch%"],
           {"switch": {"type": "choice", "question": "Which switch did they name?",
                       "options": switches},
            "state": {"type": "choice", "question": "On or off?",
                      "options": {"turn_on": {"description": "on, enable, start it"},
                                  "turn_off": {"description": "off, disable, stop it"},
                                  "toggle": {"description": "flip it"}}}})

    covers = options_for(entities, "cover")
    if covers:
        fn("move_cover", "Open or close a blind or shade",
           "Raise, lower or stop a window covering — a shade, a blind, a curtain.",
           [call_bin, "cover", "%action%", "%cover%"],
           {"cover": {"type": "choice", "question": "Which shade or blind did they mean?",
                      "options": covers},
            "action": {"type": "choice", "question": "Should it go up, down, or stop?",
                       "options": {"open_cover": {"description": "open, up, raise, let the light in"},
                                   "close_cover": {"description": "close, down, lower, shut it"},
                                   "stop_cover": {"description": "stop, halt it where it is"}}}})

    cover_areas = areas_with(entities, "cover")
    if cover_areas:
        fn("move_room_covers", "Open or close every blind in a room",
           "Raise or lower all of the shades in a whole room at once, rather than one "
           "named shade.",
           [call_bin, "cover", "%action%", "%room%"],
           {"room": {"type": "choice", "question": "Which room's shades?",
                     "options": {area: {"description": f"every shade in the {area}",
                                        "value": ids}
                                 for area, ids in sorted(cover_areas.items())}},
            "action": {"type": "choice", "question": "Up or down?",
                       "options": {"open_cover": {"description": "open, up, raise"},
                                   "close_cover": {"description": "close, down, lower"},
                                   "stop_cover": {"description": "stop them"}}}})

    players = options_for(entities, "media_player")
    if players:
        fn("control_media_player", "Control a TV or speaker",
           "Act on something that plays — a television, a speaker, a streaming box: "
           "pause it, skip on, turn it off, change its volume.",
           [call_bin, "media_player", "%action%", "%player%"],
           {"player": {"type": "choice", "question": "Which TV or speaker did they name?",
                       "options": players},
            "action": {"type": "choice", "question": "What should it do?",
                       "options": {
                           "media_play_pause": {"description": "pause, resume, play, stop for a moment"},
                           "media_next_track": {"description": "skip, next, move on"},
                           "media_previous_track": {"description": "back, previous, play that again"},
                           "volume_up": {"description": "louder, turn it up"},
                           "volume_down": {"description": "quieter, turn it down"},
                           "turn_off": {"description": "switch it off entirely"},
                           "turn_on": {"description": "switch it on"}}}})

    scripts = options_for(entities, "script")
    if scripts:
        fn("run_home_script", "Run a saved Home Assistant script",
           "Run one of the saved routines in the house — sending a key to a TV, "
           "notifying a phone, a multi-step sequence someone saved.",
           [call_bin, "script", "turn_on", "%script%"],
           {"script": {"type": "choice", "question": "Which saved routine did they ask for?",
                       "options": scripts}})

    scenes = options_for(entities, "scene")
    if scenes:
        fn("activate_scene", "Set a scene",
           "Put the house into a named arrangement of lights and devices — movie night, "
           "bedtime, dinner.",
           [call_bin, "scene", "turn_on", "%scene%"],
           {"scene": {"type": "choice", "question": "Which scene did they name?",
                      "options": scenes}})

    climates = options_for(entities, "climate")
    if climates:
        fn("set_thermostat_mode", "Change what the heating or cooling is doing",
           "Put the thermostat into heating, cooling, or off. Use this when no "
           "temperature is named.",
           [call_bin, "climate", "set_hvac_mode", "%thermostat%", "hvac_mode=%mode%"],
           {"thermostat": {"type": "choice", "question": "Which thermostat?",
                           "options": climates},
            "mode": {"type": "choice", "question": "Heating, cooling, or off?",
                     "options": {"heat": {"description": "heat, warmer, put the heating on"},
                                 "cool": {"description": "cool, colder, put the air conditioning on"},
                                 "off": {"description": "off, stop heating and cooling"},
                                 "heat_cool": {"description": "automatic, let it decide, keep it comfortable"}}}})

        fn("set_temperature", "Set the thermostat to a temperature",
           "Put the thermostat at a named temperature rather than changing its mode.",
           [call_bin, "climate", "set_temperature", "%thermostat%", "temperature=%degrees%"],
           {"thermostat": {"type": "choice", "question": "Which thermostat?",
                           "options": climates},
            "degrees": {"type": "choice",
                        "question": "What temperature did they ask for, in Fahrenheit?",
                        "options": {str(d): {"description": f"{d} degrees"}
                                    for d in (62, 65, 68, 70, 72, 74, 76, 78)}}})

    return {"version": 1, "source": "home-assistant", "functions": functions}


def cmd_refresh(args: argparse.Namespace) -> int:
    entities = states()
    fragment = build(entities, args.call_bin)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    temporary = out.with_suffix(".tmp")
    temporary.write_text(json.dumps(fragment, indent=1))
    os.replace(temporary, out)
    total = sum(len(f.get("arguments") or {}) for f in fragment["functions"].values())
    print(f"{len(fragment['functions'])} functions, {total} arguments -> {out}")
    if not args.quiet:
        for name, f in sorted(fragment["functions"].items()):
            sizes = ", ".join(f"{a}:{len(m.get('options') or {})}"
                              for a, m in (f.get("arguments") or {}).items())
            print(f"  {name:<24}{f['summary']}" + (f"   [{sizes}]" if sizes else ""))
    return 0


def cmd_entities(args: argparse.Namespace) -> int:
    entities = states()
    kept = [e for e in entities if usable(e)]
    print(f"{len(entities)} entities, {len(kept)} usable")
    for entity in sorted(kept, key=lambda e: e["entity_id"]):
        domain = entity["entity_id"].split(".", 1)[0]
        if args.domain and domain != args.domain:
            continue
        print(f"  {entity['entity_id']:<48}{describe(entity)[:46]:<48}{entity['state'][:14]}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="ha-catalog",
        description="Generate a jev function catalog from a live Home Assistant.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    node = sub.add_parser("refresh", help="rebuild the spec fragment from the live house")
    node.add_argument("--out", default=os.environ.get("HA_FRAGMENT") or "ha.json")
    node.add_argument("--call-bin", default=os.environ.get("HA_CALL_BIN") or "ha-call")
    node.add_argument("--quiet", action="store_true")
    node.set_defaults(func=cmd_refresh)

    node = sub.add_parser("entities", help="list what the house exposes")
    node.add_argument("--domain")
    node.set_defaults(func=cmd_entities)

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except JevError as exc:
        print(f"ha-catalog: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
