#!/usr/bin/env python3
"""Natural-language desktop commands, dispatched through TypeSafe's jev.

One sentence in, one typed function call out. The function catalog is
generated by Nix (``catalog.nix`` → ``spec.json``) from the same sources sway
and the runtime shell already use — the app registry, the theme set, the
runtime-shell surface ids — so a function cannot name an app that is not
installed or a theme that does not exist.

The whole exchange with the API is a single request. Every function's
closed-set arguments are asked at once alongside one routing question, and
only the chosen function's answers are read. That is TypeSafe's documented
function-calling shape (docs.typesafe.ai "Function calling"): the extra
questions are answered speculatively and thrown away, which costs tokens but
never a second round trip — and round trips are what a command bar feels.

Nothing here generates text. Every value that reaches a command comes from a
list Nix wrote, so the worst a bad answer can do is run the wrong one of our
own commands, not an arbitrary one.
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

from jev_api import JevError, api_key, evaluate, noul_confidence, state_dir

# The routing question's escape hatch. Without an explicit "none of these"
# option a Choice must pick something, and it would pick confidently: the
# distribution is normalised over the options we give it, so "what is the
# weather" would land on whichever action is least unlike it. An option the
# router can choose instead is the difference between a shrug and a wrong
# window being closed.
NO_MATCH = "__none__"
ROUTE = "__route__"


# --------------------------------------------------------------------------
# configuration


def spec_path() -> Path:
    raw = os.environ.get("JEV_SPEC")
    if not raw:
        raise JevError("JEV_SPEC is unset; this build is missing its function catalog")
    return Path(raw)


def fragment_dir() -> Path:
    raw = os.environ.get("JEV_FRAGMENT_DIR")
    if raw:
        return Path(raw)
    state = os.environ.get("XDG_STATE_HOME") or f"{Path.home()}/.local/state"
    return Path(state) / "jev/fragments"


def load_spec() -> dict[str, Any]:
    """The Nix-generated catalog, plus any runtime fragments.

    Some option sets cannot be baked at build time because they change without
    a rebuild — the lights in a house, for instance, which appear and vanish as
    devices are paired. Those are written as fragments by a generator that
    queries the live system, and merged here. The shape is identical; only the
    moment the options are known differs.
    """
    path = spec_path()
    try:
        spec = json.loads(path.read_text())
    except FileNotFoundError:
        raise JevError(f"function catalog not found at {path}") from None
    except json.JSONDecodeError as exc:
        raise JevError(f"function catalog at {path} is not valid JSON: {exc}") from None

    directory = fragment_dir()
    if not directory.is_dir():
        return spec
    for entry in sorted(directory.glob("*.json")):
        try:
            fragment = json.loads(entry.read_text())
        except (OSError, json.JSONDecodeError):
            # A broken fragment must not take the built-in catalog down with
            # it: the desktop commands keep working, the lights do not.
            print(f"jev: ignoring unreadable fragment {entry.name}", file=sys.stderr)
            continue
        spec["functions"].update(fragment.get("functions") or {})
    return spec


# --------------------------------------------------------------------------
# question construction


def build_questions(spec: dict[str, Any]) -> dict[str, Any]:
    """Every question this catalog can ask, in one map.

    Ids are ``<function>.<argument>`` for a value and ``<function>.<argument>?``
    for the yes/no that decides whether the command said anything about it at
    all. The ids are ours alone — TypeSafe does not see them (per the API
    reference, keys are not used in inference) — so they can be structural.
    """
    functions = spec["functions"]
    route_criteria = {
        name: fn.get("description") or fn.get("summary") or name
        for name, fn in functions.items()
    }
    route_criteria[NO_MATCH] = (
        "The command asks for something none of the actions above can do, or is "
        "not a request to change anything about the desktop at all."
    )

    questions: dict[str, Any] = {
        ROUTE: {
            "type": "choice",
            "instructions": spec.get("routeQuestion")
                or "What is the user asking their desktop to do?",
            "criteria": route_criteria,
        }
    }

    for name, fn in functions.items():
        for arg, meta in (fn.get("arguments") or {}).items():
            qid = f"{name}.{arg}"
            if meta["type"] == "flag":
                questions[qid] = {
                    "type": "noul",
                    "instructions": meta["question"],
                    "criteria": {
                        "true": meta.get("whenTrue") or "the command asks for this",
                        "false": meta.get("whenFalse") or "the command does not ask for this",
                    },
                }
            else:
                questions[qid] = {
                    "type": "choice",
                    "instructions": meta["question"],
                    "criteria": {
                        option: body.get("description") or option
                        for option, body in meta["options"].items()
                    },
                }
            stated = meta.get("stated")
            if stated:
                questions[f"{qid}?"] = {"type": "noul", "instructions": stated}

    return questions


# --------------------------------------------------------------------------
# reading the answers back


def resolve_arguments(
    fn: dict[str, Any], name: str, answers: dict[str, Any]
) -> tuple[dict[str, Any], list[dict[str, Any]]]:
    values: dict[str, Any] = {}
    detail: list[dict[str, Any]] = []

    for arg, meta in (fn.get("arguments") or {}).items():
        qid = f"{name}.{arg}"
        answer = answers.get(qid)
        if answer is None:
            raise JevError(f"TypeSafe did not answer {qid}")

        omitted = False
        stated_probability = None
        if meta.get("stated"):
            gate = answers.get(f"{qid}?")
            if gate is None:
                raise JevError(f"TypeSafe did not answer {qid}?")
            gate_p = float(gate["noul"])
            if gate_p < 0.5:
                omitted = True
                values[arg] = meta.get("default")
                detail.append(
                    {
                        "name": arg,
                        "value": meta.get("default"),
                        "omitted": True,
                        "probability": noul_confidence(gate_p),
                        "stated": gate_p,
                        "distribution": answer.get("probabilities", {}),
                    }
                )
                continue
            stated_probability = gate_p

        if meta["type"] == "flag":
            probability = float(answer["noul"])
            chosen = probability >= 0.5
            values[arg] = meta["whenTrueValue"] if chosen else meta.get("whenFalseValue")
            detail.append(
                {
                    "name": arg,
                    "value": chosen,
                    "omitted": False,
                    "probability": noul_confidence(probability),
                    "distribution": {"yes": probability, "no": 1.0 - probability},
                    "stated": stated_probability,
                }
            )
            continue

        option = answer["choice"]
        body = meta["options"].get(option)
        if body is None:
            raise JevError(f"TypeSafe chose {option!r} for {qid}, which is not an option")
        values[arg] = body.get("value", option)
        detail.append(
            {
                "name": arg,
                "value": option,
                "omitted": omitted,
                "probability": float(answer.get("confidence", 0.0)),
                "distribution": answer.get("probabilities", {}),
                "stated": stated_probability,
            }
        )

    return values, detail


def build_argv(fn: dict[str, Any], values: dict[str, Any], text: str) -> list[str]:
    """Substitute resolved values into the catalog's argv template.

    ``%name%`` is the placeholder. It is not ``@name@`` because wpctl's own
    arguments are spelled ``@DEFAULT_AUDIO_SINK@`` and a template language has
    no business eating them. A value may be a list, in which
    case the token must be the placeholder alone and expands to several
    arguments; a token whose value is null drops out entirely, which is how an
    optional trailing argument disappears rather than arriving as an empty
    string. The result is an argv list — it never reaches a shell.
    """
    argv: list[str] = []
    for token in fn["argv"]:
        if token == "%text%":
            argv.append(text)
            continue
        if token.startswith("%") and token.endswith("%") and token.count("%") == 2:
            key = token[1:-1]
            if key not in values:
                raise JevError(f"argv references %{key}%, which is not an argument")
            value = values[key]
            if value is None:
                continue
            if isinstance(value, list):
                argv.extend(str(part) for part in value)
            else:
                argv.append(str(value))
            continue

        # `%text:json%` is the escaped spelling, for the tokens that are
        # themselves JSON payloads (runtime-shell's surface options). Guessing
        # at the context instead would mean a typed quotation mark silently
        # producing an unparseable payload.
        rendered = token.replace("%text:json%", json.dumps(text)[1:-1]).replace("%text%", text)
        dropped = False
        for key, value in values.items():
            marker = f"%{key}%"
            if marker not in rendered:
                continue
            if value is None:
                dropped = True
                break
            if isinstance(value, list):
                raise JevError(f"%{key}% expands to a list and cannot sit inside {token!r}")
            rendered = rendered.replace(marker, str(value))
        if not dropped:
            argv.append(rendered)

    if not argv:
        raise JevError("resolved to an empty command")
    return argv


def candidates(route: dict[str, Any], spec: dict[str, Any], limit: int = 8) -> list[dict[str, Any]]:
    """The routing distribution, best first, with each option's own words.

    A confidence number alone says how sure the router was but never what it
    was choosing between. Showing the runners-up is what turns "0.61" into
    something a person can act on: it is usually obvious, once you see the two
    options side by side, which sentence would have separated them.
    """
    functions = spec["functions"]
    rows = sorted(
        (route.get("probabilities") or {}).items(), key=lambda kv: -kv[1]
    )[:limit]
    return [
        {
            "function": name,
            "probability": probability,
            "summary": (
                "no action matches this command"
                if name == NO_MATCH
                else (functions.get(name, {}).get("summary") or name)
            ),
        }
        for name, probability in rows
    ]


def plan(text: str, spec: dict[str, Any]) -> dict[str, Any]:
    text = text.strip()
    if not text:
        raise JevError("nothing to do: the command is empty")

    questions = build_questions(spec)
    response = evaluate(text, questions, spec)
    answers = response.get("answers") or {}

    route = answers.get(ROUTE)
    if route is None:
        raise JevError("TypeSafe did not answer the routing question")
    name = route["choice"]
    route_confidence = float(route.get("confidence", 0.0))

    auto = float(os.environ.get("JEV_AUTO_THRESHOLD") or spec.get("autoThreshold", 0.6))
    reject = float(os.environ.get("JEV_REJECT_THRESHOLD") or spec.get("rejectThreshold", 0.3))

    # Carried on every result, matched or not: the debug view has to be able to
    # explain a *refusal* too, and that is exactly the case where the runner-up
    # list is worth the most.
    trace = {
        "candidates": candidates(route, spec),
        "questions": len(questions),
        "usage": response.get("usage", {}),
        "latencyMs": response.get("latencyMs"),
        "model": response.get("model"),
        "autoThreshold": auto,
        "rejectThreshold": reject,
    }

    if name == NO_MATCH:
        return {
            "status": "unmatched",
            "command": text,
            "display": "no action matches",
            "confidence": route_confidence,
            "routeConfidence": route_confidence,
            "arguments": [],
            "trace": trace,
        }

    fn = spec["functions"].get(name)
    if fn is None:
        raise JevError(f"TypeSafe routed to {name!r}, which is not in the catalog")

    values, detail = resolve_arguments(fn, name, answers)
    argv = build_argv(fn, values, text)

    confidence = min([route_confidence] + [item["probability"] for item in detail])
    needs_confirmation = bool(fn.get("confirm")) or confidence < auto
    status = "rejected" if confidence < reject else ("confirm" if needs_confirmation else "ready")

    return {
        "status": status,
        "command": text,
        "function": name,
        "summary": fn.get("summary") or name,
        "confirm": bool(fn.get("confirm")),
        "argv": argv,
        "display": render(name, detail),
        "arguments": detail,
        "confidence": confidence,
        "routeConfidence": route_confidence,
        "weakest": min(detail, key=lambda item: item["probability"])["name"] if detail else None,
        "trace": trace,
    }


def render(name: str, detail: list[dict[str, Any]]) -> str:
    shown = [
        f"{item['name']}={item['value']}" for item in detail if not item["omitted"]
    ]
    return f"{name}({', '.join(shown)})"


# --------------------------------------------------------------------------
# execution


def execute(argv: list[str], detach: bool) -> dict[str, Any]:
    if detach:
        # The command bar is not a terminal and must not become one app's
        # parent: a launched editor outliving the shell is the point, and a
        # shell restart must not take it down.
        subprocess.Popen(
            argv,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            start_new_session=True,
        )
        return {"executed": True, "detached": True}

    done = subprocess.run(argv, capture_output=True, text=True)
    return {
        "executed": True,
        "detached": False,
        "exitCode": done.returncode,
        "stdout": done.stdout,
        "stderr": done.stderr,
    }


def stash(result: dict[str, Any]) -> str:
    token = secrets.token_hex(8)
    pending = state_dir() / "pending"
    pending.mkdir(parents=True, exist_ok=True, mode=0o700)
    prune(pending)
    (pending / f"{token}.json").write_text(json.dumps(result))
    return token


def prune(pending: Path, max_age: int = 600) -> None:
    now = time.time()
    for entry in pending.glob("*.json"):
        try:
            if now - entry.stat().st_mtime > max_age:
                entry.unlink()
        except OSError:
            pass


def take(token: str) -> dict[str, Any]:
    if not token.isalnum():
        raise JevError("not a pending command")
    entry = state_dir() / "pending" / f"{token}.json"
    try:
        result = json.loads(entry.read_text())
    except (OSError, json.JSONDecodeError):
        raise JevError("that command is no longer pending (it expired or already ran)") from None
    entry.unlink(missing_ok=True)
    return result


# --------------------------------------------------------------------------
# commands


def bar(probability: float, width: int = 22) -> str:
    filled = int(round(max(0.0, min(1.0, probability)) * width))
    return "█" * filled + "·" * (width - filled)


def explain(result: dict[str, Any]) -> None:
    """The whole judgement, printed. This is the terminal half of debug mode."""
    trace = result.get("trace") or {}
    print(f"\ncommand   {result['command']!r}")
    print(f"verdict   {result.get('display')}   confidence {result.get('confidence', 0):.2f}"
          f"   -> {result.get('status')}")
    print(
        f"cost      {trace.get('questions')} questions, "
        f"{(trace.get('usage') or {}).get('input_tokens', '?')} in / "
        f"{(trace.get('usage') or {}).get('output_tokens', '?')} out, "
        f"{trace.get('latencyMs', '?')} ms, model {trace.get('model')}"
    )
    print(f"gate      auto at {trace.get('autoThreshold')}, refuse below {trace.get('rejectThreshold')}")

    print("\nwhich action (the router):")
    for row in trace.get("candidates", []):
        mark = "->" if row["function"] == result.get("function") else "  "
        print(f"  {mark} {bar(row['probability'])} {row['probability']:.2f}  "
              f"{row['function']:<26}{row['summary'][:48]}")

    arguments = result.get("arguments") or []
    if arguments:
        print("\nand its arguments:")
    for item in arguments:
        shown = "omitted, default stands" if item["omitted"] else repr(item["value"])
        print(f"  {item['name']} = {shown}   p {item['probability']:.2f}")
        if item.get("stated") is not None:
            print(f"      mentioned at all? {item['stated']:.2f}")
        ranked = sorted((item.get("distribution") or {}).items(), key=lambda kv: -kv[1])[:5]
        for option, probability in ranked:
            print(f"      {bar(probability, 16)} {probability:.2f}  {option}")

    if result.get("weakest"):
        print(f"\nweakest link: {result['weakest']}")


def emit(result: dict[str, Any], as_json: bool) -> int:
    if as_json:
        print(json.dumps(result))
        return 0 if result.get("status") in ("ready", "confirm", "executed") else 1

    status = result.get("status")
    if status == "unmatched":
        print(f"no action matches: {result['command']!r}", file=sys.stderr)
        return 1
    if status == "rejected":
        print(
            f"too unsure to act: {result['display']} at {result['confidence']:.2f}",
            file=sys.stderr,
        )
        return 1

    print(f"{result['display']}   confidence {result['confidence']:.2f}")
    for item in result.get("arguments", []):
        shown = "omitted, default stands" if item["omitted"] else repr(item["value"])
        print(f"  {item['name']:<14}{shown:<26}p {item['probability']:.2f}")
    if result.get("executed"):
        run = result.get("run") or {}
        if run.get("stdout"):
            print(run["stdout"], end="")
        if run.get("stderr"):
            print(run["stderr"], end="", file=sys.stderr)
        return int(run.get("exitCode") or 0)
    print(f"  not run: {'needs confirmation' if status == 'confirm' else status}")
    return 0


def cmd_plan(args: argparse.Namespace) -> int:
    result = plan(" ".join(args.text), load_spec())
    # A resolved plan is stashed so `jev confirm` can run exactly it. That is
    # what keeps the command bar's debug mode — which previews on every pause
    # in typing — to one paid request per sentence instead of two: the preview
    # is the plan Enter then executes.
    if result["status"] in ("ready", "confirm"):
        result["token"] = stash(result)
    if getattr(args, "explain", False) and not args.json:
        explain(result)
        return 0
    return emit(result, args.json)


def cmd_explain(args: argparse.Namespace) -> int:
    explain(plan(" ".join(args.text), load_spec()))
    return 0


def cmd_watch(args: argparse.Namespace) -> int:
    """Debug mode in a terminal: a line in, the whole judgement out.

    The same trace the command bar's debug pane draws, so a classification can
    be investigated without the desktop in the way — and so the effect of an
    edit to catalog.nix can be seen against a handful of real sentences.
    """
    spec = load_spec()
    print(f"{len(spec['functions'])} functions, "
          f"{len(build_questions(spec))} questions per command. Ctrl-D to stop.")
    while True:
        try:
            line = input("\njev> ").strip()
        except (EOFError, KeyboardInterrupt):
            print()
            return 0
        if not line:
            continue
        try:
            explain(plan(line, spec))
        except JevError as exc:
            print(f"jev: {exc}", file=sys.stderr)


def cmd_run(args: argparse.Namespace) -> int:
    result = plan(" ".join(args.text), load_spec())
    if result["status"] == "ready" and not args.dry_run:
        result["run"] = execute(result["argv"], args.detach)
        result["executed"] = True
        result["status"] = "executed"
    elif result["status"] == "confirm":
        result["token"] = stash(result)
    return emit(result, args.json)


def cmd_confirm(args: argparse.Namespace) -> int:
    result = take(args.token)
    result["run"] = execute(result["argv"], args.detach)
    result["executed"] = True
    result["status"] = "executed"
    return emit(result, args.json)


def cmd_cancel(args: argparse.Namespace) -> int:
    take(args.token)
    return 0


def cmd_functions(args: argparse.Namespace) -> int:
    spec = load_spec()
    if args.json:
        print(json.dumps(spec["functions"], indent=2))
        return 0
    for name, fn in spec["functions"].items():
        arguments = fn.get("arguments") or {}
        shapes = ", ".join(f"{a}:{m['type']}" for a, m in arguments.items())
        flag = " [confirm]" if fn.get("confirm") else ""
        print(f"  {name:<26}{fn.get('summary', '')}{flag}")
        if shapes:
            print(f"  {'':<26}{shapes}")
    total = sum(len(fn.get("arguments") or {}) for fn in spec["functions"].values())
    print(f"\n{len(spec['functions'])} functions, {total} fillable arguments")
    return 0


def cmd_spec(_: argparse.Namespace) -> int:
    print(json.dumps(load_spec(), indent=2))
    return 0


def cmd_doctor(_: argparse.Namespace) -> int:
    """Check the catalog, the binaries, the key and the API — in that order.

    Deliberately cheapest-and-most-local first: a missing binary is still worth
    knowing about on a machine whose 1Password is locked, and it would go
    unreported if the API call came first and failed.
    """
    spec = load_spec()
    questions = build_questions(spec)
    print(f"catalog      {spec_path()}")
    print(f"functions    {len(spec['functions'])}")
    print(f"questions    {len(questions)} per command")
    print(f"model        {os.environ.get('JEV_MODEL') or spec.get('model')}")
    print(f"thresholds   auto {spec.get('autoThreshold')}  reject {spec.get('rejectThreshold')}")

    missing = [
        f"{name}: {fn['argv'][0]}"
        for name, fn in spec["functions"].items()
        if not fn["argv"][0].startswith("%") and not os.access(fn["argv"][0], os.X_OK)
    ]
    if missing:
        print(f"binaries     {len(missing)} NOT executable (their functions will fail):")
        for row in missing:
            print(f"               {row}")
    else:
        print("binaries     all present")

    try:
        key = api_key()
        print(f"api key      ok ({len(key)} chars, …{key[-4:]})")
    except JevError as exc:
        print(f"api key      FAILED: {exc}")
        return 1

    try:
        probe = plan("turn the volume down", spec)
    except JevError as exc:
        print(f"api call     FAILED: {exc}")
        return 1
    usage = (probe.get("trace") or {}).get("usage") or {}
    print(
        f"api call     ok — {probe.get('display')} at {probe.get('confidence', 0):.2f}, "
        f"{usage.get('input_tokens', '?')} input tokens, "
        f"{(probe.get('trace') or {}).get('latencyMs', '?')} ms"
    )
    return 1 if missing else 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="jev",
        description="Turn a sentence into one of this desktop's own commands.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    def with_text(name: str, help_text: str) -> argparse.ArgumentParser:
        node = sub.add_parser(name, help=help_text)
        node.add_argument("text", nargs="+")
        node.add_argument("--json", action="store_true", help="machine-readable result")
        return node

    node = with_text("run", "dispatch a command and run it")
    node.add_argument("--dry-run", action="store_true", help="resolve but do not run")
    node.add_argument("--detach", action="store_true", help="run it in its own session")
    node.set_defaults(func=cmd_run)

    node = with_text("plan", "resolve a command without running it")
    node.add_argument("--explain", action="store_true", help="show the whole judgement")
    node.set_defaults(func=cmd_plan)

    node = with_text("explain", "resolve a command and show every probability behind it")
    node.set_defaults(func=cmd_explain)

    node = sub.add_parser("watch", help="debug mode: type commands, see how each is classified")
    node.set_defaults(func=cmd_watch)

    node = sub.add_parser("confirm", help="run a command that was waiting for confirmation")
    node.add_argument("token")
    node.add_argument("--json", action="store_true")
    node.add_argument("--detach", action="store_true")
    node.set_defaults(func=cmd_confirm)

    node = sub.add_parser("cancel", help="drop a command that was waiting for confirmation")
    node.add_argument("token")
    node.set_defaults(func=cmd_cancel)

    node = sub.add_parser("functions", help="list the catalog")
    node.add_argument("--json", action="store_true")
    node.set_defaults(func=cmd_functions)

    sub.add_parser("spec", help="print the generated question spec").set_defaults(func=cmd_spec)
    sub.add_parser("doctor", help="check the key, the API and the catalog").set_defaults(
        func=cmd_doctor
    )

    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except JevError as exc:
        if getattr(args, "json", False):
            print(json.dumps({"status": "error", "error": str(exc)}))
        else:
            print(f"jev: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
