# i3 Window Manager Configuration Module
# Minimal working version for Phase 2 Foundational
{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.i3wm;
in {
  options.services.i3wm = {
    enable = mkEnableOption "i3 window manager";

    package = mkOption {
      type = types.package;
      default = pkgs.i3;
      description = "i3 package to use";
    };

    extraPackages = mkOption {
      type = types.listOf types.package;
      default = with pkgs; [ dmenu i3status i3lock ];
      description = "Additional packages to install with i3";
    };
  };

  config = mkIf cfg.enable {
    # Enable X11 and i3
    services.xserver = {
      enable = true;
      windowManager.i3 = {
        enable = true;
        package = cfg.package;
        extraPackages = cfg.extraPackages;
      };

      # Configure for headless operation with virtual display
      videoDrivers = mkDefault [ "modesetting" "fbdev" ];
    };

    # Set i3 as default session
    services.displayManager.defaultSession = mkDefault "none+i3";

    # Disable display manager for headless operation
    services.displayManager.sddm.enable = mkForce false;

    # Install i3 and essential tools
    environment.systemPackages = with pkgs; [
      cfg.package
      alacritty  # Terminal
      rofi       # Application launcher (better than dmenu)
      xorg.xsetroot  # For setting background color
    ] ++ cfg.extraPackages;

    # Basic i3 configuration - minimal working config
    environment.etc."i3/config".text = ''
      # i3 configuration file (v4)
      # Generated by NixOS i3wm module

      # Mod key (Mod1=Alt, Mod4=Super/Windows)
      set $mod Mod4

      # Font for window titles and bar
      font pango:monospace 10

      # Color scheme for better visibility
      # class                 border  backgr. text    indicator child_border
      client.focused          #4c7899 #285577 #ffffff #2e9ef4   #285577
      client.focused_inactive #333333 #5f676a #ffffff #484e50   #5f676a
      client.unfocused        #333333 #222222 #888888 #292d2e   #222222
      client.urgent           #2f343a #900000 #ffffff #900000   #900000
      client.placeholder      #000000 #0c0c0c #ffffff #000000   #0c0c0c
      client.background       #ffffff

      # Use Mouse+$mod to drag floating windows
      floating_modifier $mod

      # Start a terminal
      bindsym $mod+Return exec ${pkgs.alacritty}/bin/alacritty

      # Kill focused window
      bindsym $mod+Shift+q kill

      # Start application launcher
      bindsym $mod+d exec ${pkgs.rofi}/bin/rofi -show drun

      # Change focus
      bindsym $mod+Left focus left
      bindsym $mod+Down focus down
      bindsym $mod+Up focus up
      bindsym $mod+Right focus right

      # Move focused window
      bindsym $mod+Shift+Left move left
      bindsym $mod+Shift+Down move down
      bindsym $mod+Shift+Up move up
      bindsym $mod+Shift+Right move right

      # Split orientation
      bindsym $mod+h split h
      bindsym $mod+v split v

      # Fullscreen
      bindsym $mod+f fullscreen toggle

      # Change container layout
      bindsym $mod+s layout stacking
      bindsym $mod+w layout tabbed
      bindsym $mod+e layout toggle split

      # Toggle floating
      bindsym $mod+Shift+space floating toggle

      # Change focus between tiling / floating windows
      bindsym $mod+space focus mode_toggle

      # Workspace switching (Ctrl+1-9)
      bindsym Control+1 workspace number 1
      bindsym Control+2 workspace number 2
      bindsym Control+3 workspace number 3
      bindsym Control+4 workspace number 4
      bindsym Control+5 workspace number 5
      bindsym Control+6 workspace number 6
      bindsym Control+7 workspace number 7
      bindsym Control+8 workspace number 8
      bindsym Control+9 workspace number 9

      # Move container to workspace
      bindsym $mod+Shift+1 move container to workspace number 1
      bindsym $mod+Shift+2 move container to workspace number 2
      bindsym $mod+Shift+3 move container to workspace number 3
      bindsym $mod+Shift+4 move container to workspace number 4
      bindsym $mod+Shift+5 move container to workspace number 5
      bindsym $mod+Shift+6 move container to workspace number 6
      bindsym $mod+Shift+7 move container to workspace number 7
      bindsym $mod+Shift+8 move container to workspace number 8
      bindsym $mod+Shift+9 move container to workspace number 9

      # Reload configuration
      bindsym $mod+Shift+c reload

      # Restart i3
      bindsym $mod+Shift+r restart

      # Exit i3
      bindsym $mod+Shift+e exec "i3-msg exit"

      # Status bar with colors
      bar {
        status_command ${pkgs.i3status}/bin/i3status
        position bottom

        colors {
          background #000000
          statusline #ffffff
          separator  #666666

          # class            border  backgr. text
          focused_workspace  #4c7899 #285577 #ffffff
          active_workspace   #333333 #5f676a #ffffff
          inactive_workspace #333333 #222222 #888888
          urgent_workspace   #2f343a #900000 #ffffff
          binding_mode       #2f343a #900000 #ffffff
        }
      }

      # Set desktop background to solid dark color
      exec --no-startup-id ${pkgs.xorg.xsetroot}/bin/xsetroot -solid "#1a1a1a"
    '';

    # Alacritty configuration for i3 - ensures visible text
    environment.etc."xdg/alacritty/alacritty.toml".text = ''
      [colors.primary]
      background = "#1e1e1e"
      foreground = "#d4d4d4"

      [colors.normal]
      black   = "#000000"
      red     = "#cd3131"
      green   = "#0dbc79"
      yellow  = "#e5e510"
      blue    = "#2472c8"
      magenta = "#bc3fbc"
      cyan    = "#11a8cd"
      white   = "#e5e5e5"

      [colors.bright]
      black   = "#666666"
      red     = "#f14c4c"
      green   = "#23d18b"
      yellow  = "#f5f543"
      blue    = "#3b8eea"
      magenta = "#d670d6"
      cyan    = "#29b8db"
      white   = "#ffffff"

      [font]
      size = 11.0
    '';

    # Set XDG_CONFIG_DIRS to include /etc/xdg
    environment.sessionVariables = {
      XDG_CONFIG_DIRS = "/etc/xdg:$XDG_CONFIG_DIRS";
    };

    # Basic i3status configuration
    environment.etc."i3status.conf".text = ''
      general {
        colors = true
        interval = 5
      }

      order += "disk /"
      order += "memory"
      order += "load"
      order += "tztime local"

      disk "/" {
        format = "💾 %avail"
      }

      memory {
        format = "🧠 %used"
        threshold_degraded = "10%"
        format_degraded = "MEMORY LOW: %free"
      }

      load {
        format = "⚡ %1min"
      }

      tztime local {
        format = "📅 %Y-%m-%d %H:%M"
      }
    '';
  };
}
