# i3 Window Manager Home Manager Configuration
# Works with both xsession and XRDP
{ config, lib, pkgs, ... }:

{
  # Generate i3 config file directly (works with XRDP)
  home.file.".config/i3/config".text = ''
    # i3 config file (v4)
    # Generated by home-manager

    set $mod Mod4
    font pango:monospace 10
    floating_modifier $mod

    # Terminal
    bindsym $mod+Return exec ${pkgs.ghostty}/bin/ghostty
    bindsym $mod+Shift+Return exec ${pkgs.ghostty}/bin/ghostty --class=floating_terminal
    for_window [class="floating_terminal"] floating enable

    # Floating fzf launcher window
    for_window [instance="fzf-launcher"] floating enable

    # Window management
    bindsym $mod+Shift+q kill

    # Application launcher
    bindsym $mod+d exec ${pkgs.rofi}/bin/rofi -show drun -display-drun Applications
    bindsym $mod+Shift+d exec ${pkgs.xterm}/bin/xterm -name fzf-launcher -fa 'Monospace' -fs 12 -e /etc/nixos/scripts/fzf-launcher.sh

    # Keybinding cheatsheet (F1 for help)
    bindsym F1 exec /etc/nixos/scripts/keybindings-cheatsheet.sh

    # Clipboard (using FZF for better tmux integration)
    bindsym $mod+v exec /etc/nixos/scripts/clipcat-fzf.sh
    bindsym $mod+Shift+v exec ${pkgs.clipcat}/bin/clipcatctl clear

    # Screenshots (Spectacle)
    # Full screen to clipboard
    bindsym Print exec ${pkgs.kdePackages.spectacle}/bin/spectacle -bcf
    # Active window to clipboard
    bindsym $mod+Print exec ${pkgs.kdePackages.spectacle}/bin/spectacle -bca
    # Rectangular region to clipboard
    bindsym $mod+Shift+s exec ${pkgs.kdePackages.spectacle}/bin/spectacle -bcr

    # Quick launch
    bindsym $mod+c exec code
    bindsym $mod+b exec firefox
    bindsym $mod+Shift+f exec ${pkgs.xfce.thunar}/bin/thunar

    # Split orientation
    bindsym $mod+h split h
    bindsym $mod+Shift+bar split v

    # Fullscreen
    bindsym $mod+f fullscreen toggle

    # Container layout
    bindsym $mod+s layout stacking
    bindsym $mod+w layout tabbed
    bindsym $mod+e layout toggle split

    # Toggle floating
    bindsym $mod+Shift+space floating toggle
    bindsym $mod+space focus mode_toggle

    # Scratchpad
    bindsym $mod+Shift+minus move scratchpad
    bindsym $mod+minus scratchpad show

    # Focus
    bindsym $mod+Left focus left
    bindsym $mod+Down focus down
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right

    # Move
    bindsym $mod+Shift+Left move left
    bindsym $mod+Shift+Down move down
    bindsym $mod+Shift+Up move up
    bindsym $mod+Shift+Right move right

    # Workspace switching (Ctrl+1-9)
    bindsym Control+1 workspace number 1
    bindsym Control+2 workspace number 2
    bindsym Control+3 workspace number 3
    bindsym Control+4 workspace number 4
    bindsym Control+5 workspace number 5
    bindsym Control+6 workspace number 6
    bindsym Control+7 workspace number 7
    bindsym Control+8 workspace number 8
    bindsym Control+9 workspace number 9

    # Move to workspace
    bindsym $mod+Shift+1 move container to workspace number 1
    bindsym $mod+Shift+2 move container to workspace number 2
    bindsym $mod+Shift+3 move container to workspace number 3
    bindsym $mod+Shift+4 move container to workspace number 4
    bindsym $mod+Shift+5 move container to workspace number 5
    bindsym $mod+Shift+6 move container to workspace number 6
    bindsym $mod+Shift+7 move container to workspace number 7
    bindsym $mod+Shift+8 move container to workspace number 8
    bindsym $mod+Shift+9 move container to workspace number 9

    # Reload/restart
    bindsym $mod+Shift+c reload
    bindsym $mod+Shift+r restart
    bindsym $mod+Shift+e exec "i3-msg exit"

    # Status bar
    bar {
      id bar-0
      status_command ${pkgs.i3status}/bin/i3status
      position bottom
    }

    # Autostart - import environment variables for systemd services
    exec --no-startup-id systemctl --user import-environment DISPLAY XAUTHORITY

    # Web apps configuration
    include ~/.config/i3/web-apps.conf
  '';

  # Also configure via xsession for compatibility
  # Disabled for XRDP - we use home.file instead
  # xsession.windowManager.i3 = {
  #   enable = false;
  #   package = pkgs.i3;

  #   config = rec {
  #     modifier = "Mod4";
  #
  #     fonts = {
  #       names = [ "monospace" ];
  #       size = 10.0;
  #     };
  #
  #     floating.modifier = "Mod4";
  #
  #     keybindings = lib.mkOptionDefault {
  #       # Terminal
  #       "Mod4+Return" = "exec ${pkgs.alacritty}/bin/alacritty";
  #       "Mod4+Shift+Return" = "exec ${pkgs.alacritty}/bin/alacritty --class floating_terminal";
  #
  #       # Window management
  #       "Mod4+Shift+q" = "kill";
  #
  #       # Application launcher
  #       "Mod4+d" = "exec ${pkgs.rofi}/bin/rofi -show drun -display-drun Applications";
  #
  #       # Clipboard
  #       "Mod4+v" = "exec ${pkgs.clipcat}/bin/clipcat-menu";
  #       "Mod4+Shift+v" = "exec ${pkgs.clipcat}/bin/clipctl clear";
  #
  #       # Quick launch
  #       "Mod4+c" = "exec code";
  #       "Mod4+b" = "exec firefox";
  #
  #       # Split orientation
  #       "Mod4+h" = "split h";
  #       "Mod4+Shift+bar" = "split v";
  #
  #       # Scratchpad
  #       "Mod4+Shift+minus" = "move scratchpad";
  #       "Mod4+minus" = "scratchpad show";
  #
  #       # Workspace switching (Ctrl+1-9)
  #       "Control+1" = "workspace number 1";
  #       "Control+2" = "workspace number 2";
  #       "Control+3" = "workspace number 3";
  #       "Control+4" = "workspace number 4";
  #       "Control+5" = "workspace number 5";
  #       "Control+6" = "workspace number 6";
  #       "Control+7" = "workspace number 7";
  #       "Control+8" = "workspace number 8";
  #       "Control+9" = "workspace number 9";
  #
  #       # Move to workspace
  #       "Mod4+Shift+1" = "move container to workspace number 1";
  #       "Mod4+Shift+2" = "move container to workspace number 2";
  #       "Mod4+Shift+3" = "move container to workspace number 3";
  #       "Mod4+Shift+4" = "move container to workspace number 4";
  #       "Mod4+Shift+5" = "move container to workspace number 5";
  #       "Mod4+Shift+6" = "move container to workspace number 6";
  #       "Mod4+Shift+7" = "move container to workspace number 7";
  #       "Mod4+Shift+8" = "move container to workspace number 8";
  #       "Mod4+Shift+9" = "move container to workspace number 9";
  #     };
  #
  #     window.commands = [
  #       {
  #         criteria = { class = "floating_terminal"; };
  #         command = "floating enable";
  #       }
  #     ];
  #
  #     bars = [{
  #       id = "bar-0";
  #       statusCommand = "${pkgs.i3status}/bin/i3status";
  #       position = "bottom";
  #     }];
  #   };
  #
  #   # Include web apps configuration
  #   extraConfig = ''
  #     # Web Applications Configuration
  #     include ~/.config/i3/web-apps.conf
  #   '';
  # };
}
