{ config, pkgs, lib, inputs, ... }:

let
  # Use nixai from the dedicated flake
  nixaiPackage = inputs.nix-ai-help.packages.${pkgs.system}.default or null;

  # 1Password reference for Gemini API key
  # Format: op://vault/item/field
  geminiApiKeyRef = "op://CLI/GEMINI_API_KEY/credential";
in
lib.mkIf (nixaiPackage != null) {
  # Install nixai - AI-powered NixOS assistant
  home.packages = [
    nixaiPackage
  ];

  # Generate nixai configuration with Gemini 3 Flash as default
  home.file.".config/nixai/config.yaml" = {
    text = ''
      # nixai configuration
      # AI-powered NixOS assistant
      # Auto-generated by home-manager

      # Use Google Gemini as the AI provider
      ai_provider: gemini

      # Gemini 3 Flash - Google's latest fast frontier model (Dec 2025)
      ai_model: gemini-3-flash

      # API key is injected via environment variable (GEMINI_API_KEY)
      # using 1Password CLI wrapper
    '';
  };

  # Bash wrapper for nixai with 1Password credential injection
  programs.bash.initExtra = lib.mkAfter ''
    # nixai wrapper with 1Password Gemini API key injection
    nixai() {
      # Create temporary env file for Gemini API key
      local env_file=$(mktemp)
      echo 'GEMINI_API_KEY="${geminiApiKeyRef}"' > "$env_file"

      # Run nixai with injected credentials
      op run --env-file="$env_file" -- ${nixaiPackage}/bin/nixai "$@"
      local exit_code=$?

      # Clean up
      rm -f "$env_file"
      return $exit_code
    }
  '';
}
