'use strict';var aa,ba=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ca=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function da(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ea=da(this);function l(a,b){if(b)a:{var c=ea;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ca(c,a,{configurable:!0,writable:!0,value:b})}}var fa;
if(typeof Object.setPrototypeOf=="function")fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function p(a,b){a.prototype=ba(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.ga=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function q(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function r(){this.F=!1;this.B=null;this.i=void 0;this.h=1;this.u=this.D=0;this.H=this.j=null}function na(a){if(a.F)throw new TypeError("Generator is already running");a.F=!0}
r.prototype.G=function(a){this.i=a};function oa(a,b){a.j={X:b,isException:!0};a.h=a.D||a.u}r.prototype.getNextAddressJsc=function(){return this.h};r.prototype.getYieldResultJsc=function(){return this.i};r.prototype.return=function(a){this.j={return:a};this.h=this.u};r.prototype["return"]=r.prototype.return;r.prototype.K=function(a){this.j={m:a};this.h=this.u};r.prototype.jumpThroughFinallyBlocks=r.prototype.K;r.prototype.g=function(a,b){this.h=b;return{value:a}};r.prototype.yield=r.prototype.g;
r.prototype.N=function(a,b){a=q(a);var c=a.next();ma(c);if(c.done)this.i=c.value,this.h=b;else return this.B=a,this.g(c.value,b)};r.prototype.yieldAll=r.prototype.N;r.prototype.m=function(a){this.h=a};r.prototype.jumpTo=r.prototype.m;r.prototype.C=function(){this.h=0};r.prototype.jumpToEnd=r.prototype.C;r.prototype.A=function(a,b){this.D=a;b!=void 0&&(this.u=b)};r.prototype.setCatchFinallyBlocks=r.prototype.A;r.prototype.M=function(a){this.D=0;this.u=a||0};r.prototype.setFinallyBlock=r.prototype.M;
r.prototype.v=function(a,b){this.h=a;this.D=b||0};r.prototype.leaveTryBlock=r.prototype.v;r.prototype.o=function(a){this.D=a||0;a=this.j.X;this.j=null;return a};r.prototype.enterCatchBlock=r.prototype.o;r.prototype.I=function(a,b,c){c?this.H[c]=this.j:this.H=[this.j];this.D=a||0;this.u=b||0};r.prototype.enterFinallyBlock=r.prototype.I;
r.prototype.L=function(a,b){b=this.H.splice(b||0)[0];(b=this.j=this.j||b)?b.isException?this.h=this.D||this.u:b.m!=void 0&&this.u<b.m?(this.h=b.m,this.j=null):this.h=this.u:this.h=a};r.prototype.leaveFinallyBlock=r.prototype.L;r.prototype.J=function(a){return new pa(a)};r.prototype.forIn=r.prototype.J;function pa(a){this.i=a;this.g=[];for(var b in a)this.g.push(b);this.g.reverse()}pa.prototype.h=function(){for(;this.g.length>0;){var a=this.g.pop();if(a in this.i)return a}return null};
pa.prototype.getNext=pa.prototype.h;function qa(a){this.g=new r;this.h=a}function ra(a,b){na(a.g);var c=a.g.B;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return ta(a)}function sa(a,b,c,d){try{var e=b.call(a.g.B,c);ma(e);if(!e.done)return a.g.F=!1,e;var f=e.value}catch(g){return a.g.B=null,oa(a.g,g),ta(a)}a.g.B=null;d.call(a.g,f);return ta(a)}
function ta(a){for(;a.g.h;)try{var b=a.h(a.g);if(b)return a.g.F=!1,{value:b.value,done:!1}}catch(c){a.g.i=void 0,oa(a.g,c)}a.g.F=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.isException)throw b.X;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ua(a){this.next=function(b){na(a.g);a.g.B?b=sa(a,a.g.B.next,b,a.g.G):(a.g.G(b),b=ta(a));return b};this.throw=function(b){na(a.g);a.g.B?b=sa(a,a.g.B["throw"],b,a.g.G):(oa(a.g,b),b=ta(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function va(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function t(a){return va(new ua(new qa(a)))}l("Reflect.setPrototypeOf",function(a){return a?a:ka?function(b,c){try{return ka(b,c),!0}catch(d){return!1}}:null});
l("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ca(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
l("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ca(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return wa(la(this))}});return a});function wa(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
l("Promise",function(a){function b(g){this.h=0;this.i=void 0;this.g=[];this.v=!1;var h=this.j();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(this.g==null){this.g=[];var h=this;this.i(function(){h.o()})}this.g.push(g)};var e=ea.setTimeout;c.prototype.i=function(g){e(g,0)};c.prototype.o=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(m){this.j(m)}}}this.g=null};c.prototype.j=function(g){this.i(function(){throw g;})};b.prototype.j=function(){function g(m){return function(n){k||(k=!0,m.call(h,n))}}var h=this,k=!1;return{resolve:g(this.F),reject:g(this.o)}};b.prototype.F=function(g){if(g===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.H(g);else{a:switch(typeof g){case "object":var h=g!=null;break a;case "function":h=!0;break a;default:h=!1}h?this.D(g):this.u(g)}};
b.prototype.D=function(g){var h=void 0;try{h=g.then}catch(k){this.o(k);return}typeof h=="function"?this.I(h,g):this.u(g)};b.prototype.o=function(g){this.A(2,g)};b.prototype.u=function(g){this.A(1,g)};b.prototype.A=function(g,h){if(this.h!=0)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.h);this.h=g;this.i=h;this.h===2&&this.G();this.B()};b.prototype.G=function(){var g=this;e(function(){if(g.C()){var h=ea.console;typeof h!=="undefined"&&h.error(g.i)}},1)};b.prototype.C=
function(){if(this.v)return!1;var g=ea.CustomEvent,h=ea.Event,k=ea.dispatchEvent;if(typeof k==="undefined")return!0;typeof g==="function"?g=new g("unhandledrejection",{cancelable:!0}):typeof h==="function"?g=new h("unhandledrejection",{cancelable:!0}):(g=ea.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.i;return k(g)};b.prototype.B=function(){if(this.g!=null){for(var g=0;g<this.g.length;++g)f.h(this.g[g]);this.g=null}};var f=new c;
b.prototype.H=function(g){var h=this.j();g.R(h.resolve,h.reject)};b.prototype.I=function(g,h){var k=this.j();try{g.call(h,k.resolve,k.reject)}catch(m){k.reject(m)}};b.prototype.then=function(g,h){function k(y,A){return typeof y=="function"?function(H){try{m(y(H))}catch(D){n(D)}}:A}var m,n,w=new b(function(y,A){m=y;n=A});this.R(k(g,m),k(h,n));return w};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.R=function(g,h){function k(){switch(m.h){case 1:g(m.i);break;case 2:h(m.i);break;
default:throw Error("Unexpected state: "+m.h);}}var m=this;this.g==null?f.h(k):this.g.push(k);this.v=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var m=q(g),n=m.next();!n.done;n=m.next())d(n.value).R(h,k)})};b.all=function(g){var h=q(g),k=h.next();return k.done?d([]):new b(function(m,n){function w(H){return function(D){y[H]=D;A--;A==0&&m(y)}}var y=[],A=0;do y.push(void 0),A++,d(k.value).R(w(y.length-1),n),k=h.next();while(!k.done)})};
return b});l("Object.setPrototypeOf",function(a){return a||ka});function u(a,b){return Object.prototype.hasOwnProperty.call(a,b)}var xa=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)u(d,e)&&(a[e]=d[e])}return a};l("Object.assign",function(a){return a||xa});
l("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=q(k);for(var m;!(m=k.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(k){var m=typeof k;return m==="object"&&k!==null||m==="function"}function e(k){if(!u(k,g)){var m=new c;ca(k,g,{value:m})}}function f(k){var m=Object[k];m&&(Object[k]=function(n){if(n instanceof c)return n;Object.isExtensible(n)&&e(n);return m(n)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),m=Object.seal({}),
n=new a([[k,2],[m,3]]);if(n.get(k)!=2||n.get(m)!=3)return!1;n.delete(k);n.set(m,4);return!n.has(k)&&n.get(m)==4}catch(w){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,m){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!u(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=m;return this};b.prototype.get=function(k){return d(k)&&u(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&u(k,
g)&&u(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&u(k,g)&&u(k[g],this.g)?delete k[g][this.g]:!1};return b});
l("Map",function(a){function b(){var h={};return h.previous=h.next=h.head=h}function c(h,k){var m=h[1];return wa(function(){if(m){for(;m.head!=h[1];)m=m.previous;for(;m.next!=m.head;)return m=m.next,{done:!1,value:k(m)};m=null}return{done:!0,value:void 0}})}function d(h,k){var m=k&&typeof k;m=="object"||m=="function"?f.has(k)?m=f.get(k):(m=""+ ++g,f.set(k,m)):m="p_"+k;var n=h[0][m];if(n&&u(h[0],m))for(h=0;h<n.length;h++){var w=n[h];if(k!==k&&w.key!==w.key||k===w.key)return{id:m,list:n,index:h,entry:w}}return{id:m,
list:n,index:-1,entry:void 0}}function e(h){this[0]={};this[1]=b();this.size=0;if(h){h=q(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var h=Object.seal({x:4}),k=new a(q([[h,"s"]]));if(k.get(h)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var m=k.entries(),n=m.next();if(n.done||n.value[0]!=h||n.value[1]!="s")return!1;n=m.next();return n.done||n.value[0].x!=
4||n.value[1]!="t"||!m.next().done?!1:!0}catch(w){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=h===0?0:h;var m=d(this,h);m.list||(m.list=this[0][m.id]=[]);m.entry?m.entry.value=k:(m.entry={next:this[1],previous:this[1].previous,head:this[1],key:h,value:k},m.list.push(m.entry),this[1].previous.next=m.entry,this[1].previous=m.entry,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.entry&&h.list?(h.list.splice(h.index,1),h.list.length||delete this[0][h.id],
h.entry.previous.next=h.entry.next,h.entry.next.previous=h.entry.previous,h.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].previous=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).entry};e.prototype.get=function(h){return(h=d(this,h).entry)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,
function(h){return h.value})};e.prototype.forEach=function(h,k){for(var m=this.entries(),n;!(n=m.next()).done;)n=n.value,h.call(k,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
l("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(h){return h};var e=[],f=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof f=="function"){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});l("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)u(b,d)&&c.push([d,b[d]]);return c}});
l("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});l("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});l("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});l("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});l("Number.isSafeInteger",function(a){return a?a:function(b){return Number.isInteger(b)&&Math.abs(b)<=Number.MAX_SAFE_INTEGER}});
l("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});l("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
l("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return this.indexOf(b,c||0)!==-1}});
function ya(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}l("Array.prototype.entries",function(a){return a?a:function(){return ya(this,function(b,c){return[b,c]})}});l("Math.trunc",function(a){return a?a:function(b){b=Number(b);if(isNaN(b)||b===Infinity||b===-Infinity||b===0)return b;var c=Math.floor(Math.abs(b));return b<0?-c:c}});
l("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});l("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var za=this||self;function Aa(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=za,e=0;e<c.length;e++)if(d=d[c[e]],d==null){c=null;break a}c=d}a=c&&c[a];return a!=null?a:b}function Ba(a){return a};var Ca=Aa(610401301,!1),Da=Aa(748402147,!0);function Ea(){return typeof BigInt==="function"};function Fa(a){a.ca=!0;return a};var Ga=Fa(function(a){return typeof a==="number"}),Ha=Fa(function(a){return typeof a==="string"}),Ia=Fa(function(a){return typeof a==="boolean"});var Ja=typeof za.BigInt==="function"&&typeof za.BigInt(0)==="bigint";function Ka(a){var b=a;if(Ha(b)){if(!/^\s*(?:-?[1-9]\d*|0)?\s*$/.test(b))throw Error(String(b));}else if(Ga(b)&&!Number.isSafeInteger(b))throw Error(String(b));return Ja?BigInt(a):a=Ia(a)?a?"1":"0":Ha(a)?a.trim()||"0":String(a)}var Qa=Fa(function(a){return Ja?a>=La&&a<=Ma:a[0]==="-"?Na(a,Oa):Na(a,Pa)}),Oa=Number.MIN_SAFE_INTEGER.toString(),La=Ja?BigInt(Number.MIN_SAFE_INTEGER):void 0,Pa=Number.MAX_SAFE_INTEGER.toString(),Ma=Ja?BigInt(Number.MAX_SAFE_INTEGER):void 0;
function Na(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Ra=typeof Uint8Array.prototype.slice==="function",v=0,x=0,Sa;function Ta(a){var b=a>>>0;v=b;x=(a-b)/4294967296>>>0}function Ua(a){if(a<0){Ta(-a);var b=q(Va(v,x));a=b.next().value;b=b.next().value;v=a>>>0;x=b>>>0}else Ta(a)}function Wa(a){var b=Sa||(Sa=new DataView(new ArrayBuffer(8)));b.setFloat32(0,+a,!0);x=0;v=b.getUint32(0,!0)}function Xa(a){var b=Sa||(Sa=new DataView(new ArrayBuffer(8)));b.setFloat64(0,+a,!0);v=b.getUint32(0,!0);x=b.getUint32(4,!0)}
function Ya(a,b){var c=b*4294967296+(a>>>0);return Number.isSafeInteger(c)?c:Za(a,b)}function $a(a,b){return Ka(Ea()?BigInt.asUintN(64,(BigInt(b>>>0)<<BigInt(32))+BigInt(a>>>0)):Za(a,b))}function ab(a,b){return Ea()?Ka(BigInt.asIntN(64,(BigInt.asUintN(32,BigInt(b))<<BigInt(32))+BigInt.asUintN(32,BigInt(a)))):Ka(bb(a,b))}
function Za(a,b){b>>>=0;a>>>=0;if(b<=2097151)var c=""+(4294967296*b+a);else Ea()?c=""+(BigInt(b)<<BigInt(32)|BigInt(a)):(c=(a>>>24|b<<8)&16777215,b=b>>16&65535,a=(a&16777215)+c*6777216+b*6710656,c+=b*8147497,b*=2,a>=1E7&&(c+=a/1E7>>>0,a%=1E7),c>=1E7&&(b+=c/1E7>>>0,c%=1E7),c=b+cb(c)+cb(a));return c}function cb(a){a=String(a);return"0000000".slice(a.length)+a}
function bb(a,b){b&2147483648?Ea()?a=""+(BigInt(b|0)<<BigInt(32)|BigInt(a>>>0)):(b=q(Va(a,b)),a=b.next().value,b=b.next().value,a="-"+Za(a,b)):a=Za(a,b);return a}
function db(a){if(a.length<16)Ua(Number(a));else if(Ea())a=BigInt(a),v=Number(a&BigInt(4294967295))>>>0,x=Number(a>>BigInt(32)&BigInt(4294967295));else{var b=+(a[0]==="-");x=v=0;for(var c=a.length,d=b,e=(c-b)%6+b;e<=c;d=e,e+=6)d=Number(a.slice(d,e)),x*=1E6,v=v*1E6+d,v>=4294967296&&(x+=Math.trunc(v/4294967296),x>>>=0,v>>>=0);b&&(b=q(Va(v,x)),a=b.next().value,b=b.next().value,v=a,x=b)}}function Va(a,b){b=~b;a?a=~a+1:b+=1;return[a,b]};function eb(a,b){this.h=a>>>0;this.g=b>>>0}function fb(a){return a.h===0?new eb(0,1+~a.g):new eb(~a.h+1,~a.g)}function gb(a){a=BigInt.asUintN(64,a);return new eb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}function hb(a){if(!a)return ib||(ib=new eb(0,0));if(!/^\d+$/.test(a))return null;db(a);return new eb(v,x)}var ib;function jb(a,b){this.h=a>>>0;this.g=b>>>0}function kb(a){a=BigInt.asUintN(64,a);return new jb(Number(a&BigInt(4294967295)),Number(a>>BigInt(32)))}
function lb(a){if(!a)return mb||(mb=new jb(0,0));if(!/^-?\d+$/.test(a))return null;db(a);return new jb(v,x)}var mb;function nb(){throw Error("Invalid UTF8");}function ob(a,b){b=String.fromCharCode.apply(null,b);return a==null?b:a+b}var pb=void 0,qb,rb=typeof TextDecoder!=="undefined",sb,tb=typeof String.prototype.isWellFormed==="function",ub=typeof TextEncoder!=="undefined";
function vb(a){var b=!1;b=b===void 0?!1:b;if(ub){if(b&&(tb?!a.isWellFormed():/(?:[^\uD800-\uDBFF]|^)[\uDC00-\uDFFF]|[\uD800-\uDBFF](?![\uDC00-\uDFFF])/.test(a)))throw Error("Found an unpaired surrogate");a=(sb||(sb=new TextEncoder)).encode(a)}else{for(var c=0,d=new Uint8Array(3*a.length),e=0;e<a.length;e++){var f=a.charCodeAt(e);if(f<128)d[c++]=f;else{if(f<2048)d[c++]=f>>6|192;else{if(f>=55296&&f<=57343){if(f<=56319&&e<a.length){var g=a.charCodeAt(++e);if(g>=56320&&g<=57343){f=(f-55296)*1024+g-56320+
65536;d[c++]=f>>18|240;d[c++]=f>>12&63|128;d[c++]=f>>6&63|128;d[c++]=f&63|128;continue}else e--}if(b)throw Error("Found an unpaired surrogate");f=65533}d[c++]=f>>12|224;d[c++]=f>>6&63|128}d[c++]=f&63|128}}a=c===d.length?d:d.subarray(0,c)}return a};function wb(a){za.setTimeout(function(){throw a;},0)};function xb(){var a=za.navigator;return a&&(a=a.userAgent)?a:""}var yb,zb=za.navigator;yb=zb?zb.userAgentData||null:null;var Ab={},Bb=null;function Cb(a){var b=a.length,c=b*3/4;c%3?c=Math.floor(c):"=.".indexOf(a[b-1])!=-1&&(c="=.".indexOf(a[b-2])!=-1?c-2:c-1);var d=new Uint8Array(c),e=0;Db(a,function(f){d[e++]=f});return e!==c?d.subarray(0,e):d}
function Db(a,b){function c(k){for(;d<a.length;){var m=a.charAt(d++),n=Bb[m];if(n!=null)return n;if(!/^[\s\xa0]*$/.test(m))throw Error("Unknown base64 encoding at char: "+m);}return k}Eb();for(var d=0;;){var e=c(-1),f=c(0),g=c(64),h=c(64);if(h===64&&e===-1)break;b(e<<2|f>>4);g!=64&&(b(f<<4&240|g>>2),h!=64&&b(g<<6&192|h))}}
function Eb(){if(!Bb){Bb={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;c<5;c++){var d=a.concat(b[c].split(""));Ab[c]=d;for(var e=0;e<d.length;e++){var f=d[e];Bb[f]===void 0&&(Bb[f]=e)}}}};var Fb=typeof Uint8Array!=="undefined",Gb=!(Ca&&yb&&yb.brands.length>0?0:xb().indexOf("Trident")!=-1||xb().indexOf("MSIE")!=-1)&&typeof btoa==="function",Hb=/[-_.]/g,Ib={"-":"+",_:"/",".":"="};function Jb(a){return Ib[a]||""}function Kb(a){if(!Gb)return Cb(a);a=Hb.test(a)?a.replace(Hb,Jb):a;a=atob(a);for(var b=new Uint8Array(a.length),c=0;c<a.length;c++)b[c]=a.charCodeAt(c);return b}var Lb={};function Mb(a,b){Nb(b);this.g=a;if(a!=null&&a.length===0)throw Error("ByteString should be constructed with non-empty values");}function Ob(){return Qb||(Qb=new Mb(null,Lb))}function Rb(a){Nb(Lb);var b=a.g;b=b==null||Fb&&b!=null&&b instanceof Uint8Array?b:typeof b==="string"?Kb(b):null;return b==null?b:a.g=b}var Qb;function Nb(a){if(a!==Lb)throw Error("illegal external caller");};function Sb(a,b,c){this.buffer=a;if(c&&!b)throw Error();this.g=b}
function Tb(a,b){if(typeof a==="string")return new Sb(Kb(a),b);if(Array.isArray(a))return new Sb(new Uint8Array(a),b);if(a.constructor===Uint8Array)return new Sb(a,!1);if(a.constructor===ArrayBuffer)return a=new Uint8Array(a),new Sb(a,!1);if(a.constructor===Mb)return b=Rb(a)||new Uint8Array(0),new Sb(b,!0,a);if(a instanceof Uint8Array)return a=a.constructor===Uint8Array?a:new Uint8Array(a.buffer,a.byteOffset,a.byteLength),new Sb(a,!1);throw Error();};function Ub(a,b,c,d){this.h=null;this.o=!1;this.g=this.i=this.j=0;this.init(a,b,c,d)}Ub.prototype.init=function(a,b,c,d){var e=d===void 0?{}:d;d=e.P===void 0?!1:e.P;e=e.S===void 0?!1:e.S;this.P=d;this.S=e;a&&(a=Tb(a,this.S),this.h=a.buffer,this.o=a.g,this.j=b||0,this.i=c!==void 0?this.j+c:this.h.length,this.g=this.j)};Ub.prototype.clear=function(){this.h=null;this.o=!1;this.g=this.i=this.j=0;this.P=!1};
function Vb(a,b){var c=0,d=0,e=0,f=a.h,g=a.g;do{var h=f[g++];c|=(h&127)<<e;e+=7}while(e<32&&h&128);if(e>32)for(d|=(h&127)>>4,e=3;e<32&&h&128;e+=7)h=f[g++],d|=(h&127)<<e;Wb(a,g);if(!(h&128))return b(c>>>0,d>>>0);throw Error();}function Wb(a,b){a.g=b;if(b>a.i)throw Error();}
function Xb(a){var b=a.h,c=a.g,d=b[c++],e=d&127;if(d&128&&(d=b[c++],e|=(d&127)<<7,d&128&&(d=b[c++],e|=(d&127)<<14,d&128&&(d=b[c++],e|=(d&127)<<21,d&128&&(d=b[c++],e|=d<<28,d&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128&&b[c++]&128)))))throw Error();Wb(a,c);return e}function Yb(a){return Xb(a)>>>0}function Zb(a){a=Yb(a);return a>>>1^-(a&1)}function $b(a){return Vb(a,ab)}function ac(a){var b=a.h,c=a.g,d=b[c],e=b[c+1],f=b[c+2];b=b[c+3];Wb(a,a.g+4);return(d<<0|e<<8|f<<16|b<<24)>>>0}
function bc(a){var b=ac(a);a=(b>>31)*2+1;var c=b>>>23&255;b&=8388607;return c==255?b?NaN:a*Infinity:c==0?a*1.401298464324817E-45*b:a*Math.pow(2,c-150)*(b+8388608)}function cc(a){var b=ac(a),c=ac(a);a=(c>>31)*2+1;var d=c>>>20&2047;b=4294967296*(c&1048575)+b;return d==2047?b?NaN:a*Infinity:d==0?a*4.9E-324*b:a*Math.pow(2,d-1075)*(b+4503599627370496)}function dc(a){for(var b=0,c=a.g,d=c+10,e=a.h;c<d;){var f=e[c++];b|=f;if((f&128)===0)return Wb(a,c),!!(b&127)}throw Error();}
function ec(a){return Xb(a)}function fc(a,b){if(b<0)throw Error();var c=a.g;b=c+b;if(b>a.i)throw Error();a.g=b;return c}function hc(a,b){if(b==0)return Ob();var c=fc(a,b);a.P&&a.o?c=a.h.subarray(c,c+b):(a=a.h,b=c+b,c=c===b?new Uint8Array(0):Ra?a.slice(c,b):new Uint8Array(a.subarray(c,b)));return c.length==0?Ob():new Mb(c,Lb)}var ic=[],jc=void 0;function kc(){this.g=[]}kc.prototype.length=function(){return this.g.length};kc.prototype.end=function(){var a=this.g;this.g=[];return a};function lc(a,b,c){for(;c>0||b>127;)a.g.push(b&127|128),b=(b>>>7|c<<25)>>>0,c>>>=7;a.g.push(b)}function mc(a,b){for(;b>127;)a.g.push(b&127|128),b>>>=7;a.g.push(b)}function nc(a,b){if(b>=0)mc(a,b);else{for(var c=0;c<9;c++)a.g.push(b&127|128),b>>=7;a.g.push(1)}}function z(a,b){a.g.push(b>>>0&255);a.g.push(b>>>8&255);a.g.push(b>>>16&255);a.g.push(b>>>24&255)};function oc(a,b,c,d){if(ic.length){var e=ic.pop();e.init(a,b,c,d);a=e}else a=new Ub(a,b,c,d);this.g=a;this.j=this.g.g;this.h=this.i=-1;this.setOptions(d)}oc.prototype.setOptions=function(a){a=a===void 0?{}:a;this.U=a.U===void 0?!1:a.U};function pc(a,b,c,d){if(qc.length){var e=qc.pop();e.setOptions(d);e.g.init(a,b,c,d);return e}return new oc(a,b,c,d)}function rc(a){a.g.clear();a.i=-1;a.h=-1;qc.length<100&&qc.push(a)}
function sc(a){var b=a.g;if(b.g==b.i)return!1;a.j=a.g.g;var c=Yb(a.g);b=c>>>3;c&=7;if(!(c>=0&&c<=5))throw Error();if(b<1)throw Error();a.i=b;a.h=c;return!0}function tc(a){switch(a.h){case 0:a.h!=0?tc(a):dc(a.g);break;case 1:a=a.g;Wb(a,a.g+8);break;case 2:if(a.h!=2)tc(a);else{var b=Yb(a.g);a=a.g;Wb(a,a.g+b)}break;case 5:a=a.g;Wb(a,a.g+4);break;case 3:b=a.i;do{if(!sc(a))throw Error();if(a.h==4){if(a.i!=b)throw Error();break}tc(a)}while(1);break;default:throw Error();}}
function uc(a,b,c){var d=a.g.i,e=Yb(a.g);e=a.g.g+e;var f=e-d;f<=0&&(a.g.i=e,c(b,a,void 0,void 0,void 0),f=e-a.g.g);if(f)throw Error();a.g.g=e;a.g.i=d;return b}
function vc(a){var b=Yb(a.g);a=a.g;var c=fc(a,b);a=a.h;if(rb){var d=a,e;(e=qb)||(e=qb=new TextDecoder("utf-8",{fatal:!0}));b=c+b;d=c===0&&b===d.length?d:d.subarray(c,b);try{var f=e.decode(d)}catch(m){if(pb===void 0){try{e.decode(new Uint8Array([128]))}catch(n){}try{e.decode(new Uint8Array([97])),pb=!0}catch(n){pb=!1}}!pb&&(qb=void 0);throw m;}}else{f=c;b=f+b;c=[];for(var g=null,h,k;f<b;)h=a[f++],h<128?c.push(h):h<224?f>=b?nb():(k=a[f++],h<194||(k&192)!==128?(f--,nb()):c.push((h&31)<<6|k&63)):h<240?
f>=b-1?nb():(k=a[f++],(k&192)!==128||h===224&&k<160||h===237&&k>=160||((e=a[f++])&192)!==128?(f--,nb()):c.push((h&15)<<12|(k&63)<<6|e&63)):h<=244?f>=b-2?nb():(k=a[f++],(k&192)!==128||(h<<28)+(k-144)>>30!==0||((e=a[f++])&192)!==128||((d=a[f++])&192)!==128?(f--,nb()):(h=(h&7)<<18|(k&63)<<12|(e&63)<<6|d&63,h-=65536,c.push((h>>10&1023)+55296,(h&1023)+56320))):nb(),c.length>=8192&&(g=ob(g,c),c.length=0);f=ob(g,c)}return f}function wc(a){var b=Yb(a.g);return hc(a.g,b)}
function xc(a,b,c){var d=Yb(a.g);for(d=a.g.g+d;a.g.g<d;)c.push(b(a.g))}var qc=[];function yc(){this.i=[];this.h=0;this.g=new kc}function zc(a,b){b.length!==0&&(a.i.push(b),a.h+=b.length)}function Ac(a,b){B(a,b,2);b=a.g.end();zc(a,b);b.push(a.h);return b}function Bc(a,b){var c=b.pop();for(c=a.h+a.g.length()-c;c>127;)b.push(c&127|128),c>>>=7,a.h++;b.push(c);a.h++}function B(a,b,c){mc(a.g,b*8+c)}function Cc(a,b,c){c!=null&&(c=parseInt(c,10),B(a,b,0),nc(a.g,c))}function Dc(a,b,c){B(a,b,2);mc(a.g,c.length);zc(a,a.g.end());zc(a,c)}
function Ec(a,b,c,d){c!=null&&(b=Ac(a,b),d(c,a),Bc(a,b))}function Fc(a){switch(typeof a){case "string":a.length&&a[0]==="-"?hb(a.substring(1)):hb(a)}};var Gc=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Hc(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Ic=Hc("jas",void 0,!0),Jc=Hc(void 0,"1oa"),Kc=Hc(void 0,Symbol()),Lc=Hc(void 0,"0ubs"),Mc=Hc(void 0,"0ubsb"),Nc=Hc(void 0,"0actk"),Oc=Hc("m_m","da",!0);var Pc={ba:{value:0,configurable:!0,writable:!0,enumerable:!1}},Qc=Object.defineProperties,C=Gc?Ic:"ba",Rc,Sc=[];E(Sc,7);Rc=Object.freeze(Sc);function Tc(a,b){Gc||C in a||Qc(a,Pc);a[C]|=b}function E(a,b){Gc||C in a||Qc(a,Pc);a[C]=b}function Uc(a){Tc(a,8192);return a};var Vc={};function Wc(a,b){return b===void 0?a.g!==Xc&&!!(2&(a.l[C]|0)):!!(2&b)&&a.g!==Xc}var Xc={};function Yc(a,b,c){var d=b&128?0:-1,e=a.length,f;if(f=!!e)f=a[e-1],f=f!=null&&typeof f==="object"&&f.constructor===Object;var g=e+(f?-1:0);for(b=b&128?1:0;b<g;b++)c(b-d,a[b]);if(f){a=a[e-1];for(var h in a)!isNaN(h)&&c(+h,a[h])}}var Zc={};function $c(a){return a&128?Zc:void 0};function ad(a){return a};var bd=void 0;function hd(a,b){if(a!=null){var c;var d=(c=bd)!=null?c:bd={};c=d[a]||0;c>=b||(d[a]=c+1,a=Error(),a.__closure__error__context__984382||(a.__closure__error__context__984382={}),a.__closure__error__context__984382.severity="incident",wb(a))}};function id(a){return Array.prototype.slice.call(a)};var jd=typeof BigInt==="function"?BigInt.asIntN:void 0,kd=typeof BigInt==="function"?BigInt.asUintN:void 0,ld=Number.isSafeInteger,md=Number.isFinite,nd=Math.trunc;function od(a){if(a!=null&&typeof a!=="number")throw Error("Value of float/double field must be a number, found "+typeof a+": "+a);return a}function pd(a){if(a==null||typeof a==="number")return a;if(a==="NaN"||a==="Infinity"||a==="-Infinity")return Number(a)}
function qd(a){if(a==null||typeof a==="boolean")return a;if(typeof a==="number")return!!a}var rd=/^-?([1-9][0-9]*|0)(\.[0-9]+)?$/;function sd(a){switch(typeof a){case "bigint":return!0;case "number":return md(a);case "string":return rd.test(a);default:return!1}}function td(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return md(a)?a|0:void 0}
function ud(a){if(a==null)return a;if(typeof a==="string"&&a)a=+a;else if(typeof a!=="number")return;return md(a)?a>>>0:void 0}
function vd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(jd(64,a));if(sd(a)){if(b==="string")return b=nd(Number(a)),ld(b)?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),b=a.length,(a[0]==="-"?b<20||b===20&&a<="-9223372036854775808":b<19||b===19&&a<="9223372036854775807")||(db(a),a=bb(v,x))),a;if(b==="number"){a=nd(a);if(!ld(a)){Ua(a);b=v;var c=x;if(a=c&2147483648)b=~b+1>>>0,c=~c>>>0,b==0&&(c=c+1>>>0);b=Ya(b,c);a=typeof b==="number"?a?-b:b:a?"-"+b:b}return a}}}
function wd(a){if(a==null)return a;var b=typeof a;if(b==="bigint")return String(kd(64,a));if(sd(a)){if(b==="string")return b=nd(Number(a)),ld(b)&&b>=0?a=String(b):(b=a.indexOf("."),b!==-1&&(a=a.substring(0,b)),a[0]==="-"?b=!1:(b=a.length,b=b<20?!0:b===20&&a<="18446744073709551615"),b||(db(a),a=Za(v,x))),a;if(b==="number")return a=nd(a),a>=0&&ld(a)||(Ua(a),a=Ya(v,x)),a}}function xd(a){if(a==null||typeof a=="string"||a instanceof Mb)return a}
function yd(a){if(a!=null&&typeof a!=="string")throw Error();return a}function zd(a){return a==null||typeof a==="string"?a:void 0};function Ad(a){var b=Ba(Kc);return b?a[b]:void 0}function Bd(){}function Cd(a,b){for(var c in a)!isNaN(c)&&b(a,+c,a[c])}function Dd(a){var b=new Bd;Cd(a,function(c,d,e){b[d]=id(e)});b.g=a.g;return b}function Ed(a,b){b<100||hd(Lc,1)};function Fd(a,b,c,d){var e=d!==void 0;d=!!d;var f=Ba(Kc),g;!e&&Gc&&f&&(g=a[f])&&Cd(g,Ed);f=[];var h=a.length;g=4294967295;var k=!1,m=!!(b&64),n=m?b&128?0:-1:void 0;if(!(b&1)){var w=h&&a[h-1];w!=null&&typeof w==="object"&&w.constructor===Object?(h--,g=h):w=void 0;if(m&&!(b&128)&&!e){k=!0;var y;g=((y=Gd)!=null?y:ad)(g-n,n,a,w,void 0)+n}}b=void 0;for(y=0;y<h;y++){var A=a[y];if(A!=null&&(A=c(A,d))!=null)if(m&&y>=g){var H=y-n,D=void 0;((D=b)!=null?D:b={})[H]=A}else f[y]=A}if(w)for(var S in w)h=w[S],h!=
null&&(h=c(h,d))!=null&&(y=+S,A=void 0,m&&!Number.isNaN(y)&&(A=y+n)<g?f[A]=h:(y=void 0,((y=b)!=null?y:b={})[S]=h));b&&(k?f.push(b):f[g]=b);e&&Ba(Kc)&&(a=Ad(a))&&a instanceof Bd&&(f[Kc]=Dd(a));return f}
function Hd(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return Qa(a)?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[C]|0;return a.length===0&&b&1?void 0:Fd(a,b,Hd)}if(a!=null&&a[Oc]===Vc)return Id(a);if(a instanceof Mb){b=a.g;if(b==null)a="";else if(typeof b==="string")a=b;else{if(Gb){for(var c="",d=0,e=b.length-10240;d<e;)c+=String.fromCharCode.apply(null,b.subarray(d,d+=10240));c+=String.fromCharCode.apply(null,d?b.subarray(d):
b);b=btoa(c)}else{c===void 0&&(c=0);Eb();c=Ab[c];d=Array(Math.floor(b.length/3));e=c[64]||"";for(var f=0,g=0;f<b.length-2;f+=3){var h=b[f],k=b[f+1],m=b[f+2],n=c[h>>2];h=c[(h&3)<<4|k>>4];k=c[(k&15)<<2|m>>6];m=c[m&63];d[g++]=n+h+k+m}n=0;m=e;switch(b.length-f){case 2:n=b[f+1],m=c[(n&15)<<2]||e;case 1:b=b[f],d[g]=c[b>>2]+c[(b&3)<<4|n>>4]+m+e}b=d.join("")}a=a.g=b}return a}return}return a}var Gd;function Id(a){a=a.l;return Fd(a,a[C]|0,Hd)};var Jd,Kd;function Ld(a){switch(typeof a){case "boolean":return Jd||(Jd=[0,void 0,!0]);case "number":return a>0?void 0:a===0?Kd||(Kd=[0,void 0]):[-a,void 0];case "string":return[0,a];case "object":return a}}function Md(a,b){return F(a,b[0],b[1])}
function F(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[C]|0;if(Da&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&Nd();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&E(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var f=c.length;if(f){var g=f-1,h=c[g];if(h!=null&&typeof h==="object"&&h.constructor===Object){b=e&128?0:-1;g-=b;if(g>=1024)throw Error("pvtlmt");for(var k in h)f=
+k,f<g&&(c[f+b]=h[k],delete h[k]);e=e&-16760833|(g&1023)<<14;break a}}if(b){k=Math.max(b,f-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}E(a,e|64|d);return a}function Nd(){if(Da)throw Error("carr");hd(Nc,5)};function Od(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[C]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=Pd(a,c,!1,b&&!(c&16)):(Tc(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Oc]===Vc)return b=a.l,c=b[C]|0,Wc(a,c)?a:Qd(a,b,c)?Rd(a,b):Pd(b,c);if(a instanceof Mb)return a}function Rd(a,b,c){a=new a.constructor(b);c&&(a.g=Xc);a.h=Xc;return a}function Pd(a,b,c,d){d!=null||(d=!!(34&b));a=Fd(a,b,Od,d);d=32;c&&(d|=2);b=b&16769217|d;E(a,b);return a}
function Sd(a){if(a.g!==Xc)return!1;var b=a.l;b=Pd(b,b[C]|0);Tc(b,2048);a.l=b;a.g=void 0;a.h=void 0;return!0}function Td(a){if(!Sd(a)&&Wc(a,a.l[C]|0))throw Error();}function Ud(a,b){b===void 0&&(b=a[C]|0);b&32&&!(b&4096)&&E(a,b|4096)}function Qd(a,b,c){return c&2?!0:c&32&&!(c&4096)?(E(b,c|2),a.g=Xc,!0):!1};function Vd(a,b,c){a=Wd(a.l,b,void 0,c);if(a!==null)return a}function Wd(a,b,c,d){if(b===-1)return null;var e=b+(c?0:-1),f=a.length-1;if(!(f<1+(c?0:-1))){if(e>=f){var g=a[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){c=g[b];var h=!0}else if(e===f)c=g;else return}else c=a[e];if(d&&c!=null){d=d(c);if(d==null)return d;if(!Object.is(d,c))return h?g[b]=d:a[e]=d,d}return c}}function Xd(a,b,c){Td(a);var d=a.l;G(d,d[C]|0,b,c);return a}
function G(a,b,c,d,e){var f=c+(e?0:-1),g=a.length-1;if(g>=1+(e?0:-1)&&f>=g){var h=a[g];if(h!=null&&typeof h==="object"&&h.constructor===Object)return h[c]=d,b}if(f<=g)return a[f]=d,b;if(d!==void 0){var k;g=((k=b)!=null?k:b=a[C]|0)>>14&1023||536870912;c>=g?d!=null&&(f={},a[g+(e?0:-1)]=(f[c]=d,f)):a[f]=d}return b}function Yd(a,b){return Zd(a,a[C]|0,b)}function $d(a){return!!(2&a)&&!!(4&a)||!!(256&a)}
function ae(a){return a==null?a:typeof a==="string"?a?new Mb(a,Lb):Ob():a.constructor===Mb?a:Fb&&a!=null&&a instanceof Uint8Array?a.length?new Mb(new Uint8Array(a),Lb):Ob():void 0}function Zd(a,b,c){if(b&2)throw Error();var d=$c(b);var e=Wd(a,c,d);e=Array.isArray(e)?e:Rc;var f=e===Rc?7:e[C]|0;var g=f;2&b&&(g|=2);g|=1;if(2&g||$d(g)||16&g)g===f||$d(g)||E(e,g),e=id(e),f=0,g=be(g,b),G(a,b,c,e,d);g&=-13;g!==f&&E(e,g);return e}
function ce(a,b,c,d){Td(a);var e=a.l,f=e[C]|0;if(d==null){var g=de(e);if(ee(g,e,f,c)===b)g.set(c,0);else return a}else f=fe(e,f,c,b);G(e,f,b,d);return a}function ge(a,b,c,d){var e=a[C]|0,f=$c(e);e=fe(a,e,c,b,f);G(a,e,b,d,f)}function de(a){if(Gc){var b;return(b=a[Jc])!=null?b:a[Jc]=new Map}if(Jc in a)return a[Jc];b=new Map;Object.defineProperty(a,Jc,{value:b});return b}function fe(a,b,c,d,e){var f=de(a),g=ee(f,a,b,c,e);g!==d&&(g&&(b=G(a,b,g,void 0,e)),f.set(c,d));return b}
function ee(a,b,c,d,e){var f=a.get(d);if(f!=null)return f;for(var g=f=0;g<d.length;g++){var h=d[g];Wd(b,h,e)!=null&&(f!==0&&(c=G(b,c,f,void 0,e)),f=h)}a.set(d,f);return f}function he(a,b,c){var d=a[C]|0,e=$c(d),f=Wd(a,c,e);if(f!=null&&f[Oc]===Vc){if(!Wc(f))return Sd(f),f.l;var g=f.l}else Array.isArray(f)&&(g=f);if(g){var h=g[C]|0;h&2&&(g=Pd(g,h))}g=Md(g,b);g!==f&&G(a,d,c,g,e);return g}
function ie(a,b){var c=je,d=!1,e=Wd(a,4,void 0,function(f){if(f!=null&&f[Oc]===Vc)var g=f;else if(Array.isArray(f)){g=f[C]|0;var h=g|b&32;h|=b&2;h!==g&&E(f,h);g=new c(f)}else g=void 0;d=g!==f&&g!=null;return g});if(e!=null)return d&&!Wc(e)&&Ud(a,b),e}function ke(a){var b=a.l,c=b[C]|0,d=ie(b,c);if(d==null)return d;c=b[C]|0;if(!Wc(a,c)){var e=d;var f=e.l,g=f[C]|0;e=Wc(e,g)?Qd(e,f,g)?Rd(e,f,!0):new e.constructor(Pd(f,g,!1)):e;e!==d&&(Sd(a)&&(b=a.l,c=b[C]|0),d=e,c=G(b,c,4,d),Ud(b,c))}return d}
function le(a){a==null&&(a=void 0);return a}function me(a,b,c){c=le(c);Xd(a,b,c);c&&!Wc(c)&&Ud(a.l);return a}function ne(a,b){Td(a);var c=a.l,d=c[C]|0;if(b==null)return G(c,d,1),a;for(var e=b===Rc?7:b[C]|0,f=e,g=$d(e),h=g||Object.isFrozen(b),k=!0,m=!0,n=0;n<b.length;n++){var w=b[n];g||(w=Wc(w),k&&(k=!w),m&&(m=w))}g||(e=k?13:5,e=m?e&-4097:e|4096);h&&e===f||(b=id(b),f=0,e=be(e,d));e!==f&&E(b,e);d=G(c,d,1,b);2&e||!(4096&e||16&e)||Ud(c,d);return a}function be(a,b){return a=(2&b?a|2:a&-3)&-273};function I(a,b,c){this.l=F(a,b,c,2048)}I.prototype.toJSON=function(){var a=Id(this);return a};I.prototype[Oc]=Vc;I.prototype.toString=function(){return this.l.toString()};function J(){function a(){throw Error();}Object.setPrototypeOf(a,a.prototype);return a}var oe=J(),pe=J(),qe=J(),re=J(),se=J(),te=J(),ue=J(),ve=J(),we=J(),xe=J();function ye(a,b,c){this.g=a;this.h=b;a=Ba(oe);this.i=!!a&&c===a||!1}function ze(a,b){var c=c===void 0?oe:c;return new ye(a,b,c)}function Ae(a,b,c,d,e){Ec(a,c,Be(b,d),e)}var Ce=ze(function(a,b,c,d,e){if(a.h!==2)return!1;uc(a,he(b,d,c),e);return!0},Ae),De=ze(function(a,b,c,d,e){if(a.h!==2)return!1;uc(a,he(b,d,c),e);return!0},Ae),Ee=Symbol(),Fe=Symbol(),Ge=Symbol(),He=Symbol(),Ie=Symbol(),Je,Ke;
function Le(a,b,c,d){var e=d[a];if(e)return e;e={};e.aa=d;e.O=Ld(d[0]);var f=d[1],g=1;f&&f.constructor===Object&&(e.V=f,f=d[++g],typeof f==="function"&&(e.Y=!0,Je!=null||(Je=f),Ke!=null||(Ke=d[g+1]),f=d[g+=2]));for(var h={};f&&Array.isArray(f)&&f.length&&typeof f[0]==="number"&&f[0]>0;){for(var k=0;k<f.length;k++)h[f[k]]=f;f=d[++g]}for(k=1;f!==void 0;){typeof f==="number"&&(k+=f,f=d[++g]);var m=void 0;if(f instanceof ye)var n=f;else n=Ce,g--;f=void 0;if((f=n)==null?0:f.i){f=d[++g];m=d;var w=g;typeof f===
"function"&&(f=f(),m[w]=f);m=f}f=d[++g];w=k+1;typeof f==="number"&&f<0&&(w-=f,f=d[++g]);for(;k<w;k++){var y=h[k];m?c(e,k,n,m,y):b(e,k,n,y)}}return d[a]=e}function Me(a){return Array.isArray(a)?a[0]instanceof ye?a:[De,a]:[a,void 0]}function Be(a,b){if(a instanceof I)return a.l;if(Array.isArray(a))return Md(a,b)};function Ne(a,b,c,d){var e=c.g;a[b]=d?function(f,g,h){return e(f,g,h,d)}:e}function Oe(a,b,c,d,e){var f=c.g,g,h;a[b]=function(k,m,n){return f(k,m,n,h||(h=Le(Fe,Ne,Oe,d).O),g||(g=Pe(d)),e)}}
function Pe(a){var b=a[Ge];if(b!=null)return b;var c=Le(Fe,Ne,Oe,a);b=c.Y?function(d,e){return Je(d,e,c)}:function(d,e){for(;sc(e)&&e.h!=4;){var f=e.i,g=c[f];if(g==null){var h=c.V;h&&(h=h[f])&&(h=Qe(h),h!=null&&(g=c[f]=h))}if(g==null||!g(e,d,f)){h=e;g=h.j;tc(h);if(h.U)var k=void 0;else{var m=h.g.g-g;h.g.g=g;k=hc(h.g,m)}m=h=g=void 0;var n=d;k&&((g=(h=(m=n[Kc])!=null?m:n[Kc]=new Bd)[f])!=null?g:h[f]=[]).push(k)}}if(d=Ad(d))d.g=c.aa[Ie];return!0};a[Ge]=b;a[Ie]=Re.bind(a);return b}
function Re(a,b,c,d){var e=this[Fe],f=this[Ge],g=Md(void 0,e.O),h=Ad(a);if(h){var k=!1,m=e.V;if(m){e=function(H,D,S){if(S.length!==0)if(m[D])for(H=q(S),D=H.next();!D.done;D=H.next()){D=pc(D.value);try{k=!0,f(g,D)}finally{rc(D)}}else d==null||d(a,D,S)};if(b==null)Cd(h,e);else if(h!=null){var n=h[b];n&&e(h,b,n)}if(k){var w=a[C]|0;if(w&2&&w&2048&&(c==null||!c.fa))throw Error();var y=$c(w),A=function(H,D){if(Wd(a,H,y)!=null)switch(c==null?void 0:c.ea){case 1:return;default:throw Error();}D!=null&&(w=
G(a,w,H,D,y));delete h[H]};b==null?Yc(g,g[C]|0,function(H,D){A(H,D)}):A(b,Wd(g,b,y))}}}}function Qe(a){a=Me(a);var b=a[0].g;if(a=a[1]){var c=Pe(a),d=Le(Fe,Ne,Oe,a).O;return function(e,f,g){return b(e,f,g,d,c)}}return b};function Se(a,b,c){a[b]=c.h}function Te(a,b,c,d){var e,f,g=c.h;a[b]=function(h,k,m){return g(h,k,m,f||(f=Le(Ee,Se,Te,d).O),e||(e=Ue(d)))}}function Ue(a){var b=a[He];if(!b){var c=Le(Ee,Se,Te,a);b=function(d,e){return Ve(d,e,c)};a[He]=b}return b}function Ve(a,b,c){Yc(a,a[C]|0,function(d,e){if(e!=null){var f=We(c,d);f?f(b,e,d):d<500||hd(Mc,3)}});(a=Ad(a))&&Cd(a,function(d,e,f){zc(b,b.g.end());for(d=0;d<f.length;d++)zc(b,Rb(f[d])||new Uint8Array(0))})}
function We(a,b){var c=a[b];if(c)return c;if(c=a.V)if(c=c[b]){c=Me(c);var d=c[0].h;if(c=c[1]){var e=Ue(c),f=Le(Ee,Se,Te,c).O;c=a.Y?Ke(f,e):function(g,h,k){return d(g,h,k,f,e)}}else c=d;return a[b]=c}};function K(a,b,c){if(Array.isArray(b)){var d=b[C]|0;if(d&4)return b;for(var e=0,f=0;e<b.length;e++){var g=a(b[e]);g!=null&&(b[f++]=g)}f<e&&(b.length=f);a=d|1;c&&(a=(a|4)&-1537);a!==d&&E(b,a);c&&a&2&&Object.freeze(b);return b}}function L(a,b,c){return new ye(a,b,c)}function M(a,b,c){return new ye(a,b,c)}function N(a,b,c){G(a,a[C]|0,b,c,$c(a[C]|0))}
var Xe=ze(function(a,b,c,d,e){if(a.h!==2)return!1;a=uc(a,Md([void 0,void 0],d),e);a=id(a);d=b[C]|0;e=$c(d);if(d&2)throw Error();var f=Wd(b,c,e);if(Array.isArray(f)){var g=f[C]|0;g&8192||E(f,g|=8192);if(g&2){f=id(f);for(g=0;g<f.length;g++){var h=f[g]=id(f[g]);if(Array.isArray(h[1])){var k=h[1];Tc(k,34);h[1]=k}}f=Uc(f);G(b,d,c,f,e)}f.push(a)}else G(b,d,c,Uc([a]),e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++){var g=b[f];Array.isArray(g)&&Ec(a,c,Md(g,d),e)}Uc(b)}});
function Ye(a,b,c){b=pd(b);b!=null&&(B(a,c,1),a=a.g,Xa(b),z(a,v),z(a,x))}function Ze(a,b,c){b=pd(b);b!=null&&(B(a,c,5),a=a.g,Wa(b),z(a,v))}function $e(a,b,c){b=vd(b);if(b!=null){switch(typeof b){case "string":lb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Ua(b);lc(a,v,x);break;case "bigint":c=kb(b);lc(a.g,c.h,c.g);break;default:c=lb(b),lc(a.g,c.h,c.g)}}}
function af(a,b,c){b=wd(b);if(b!=null){switch(typeof b){case "string":hb(b)}if(b!=null)switch(B(a,c,0),typeof b){case "number":a=a.g;Ua(b);lc(a,v,x);break;case "bigint":c=gb(b);lc(a.g,c.h,c.g);break;default:c=hb(b),lc(a.g,c.h,c.g)}}}function bf(a,b,c){b=td(b);b!=null&&b!=null&&(B(a,c,0),nc(a.g,b))}function cf(a,b,c){b=qd(b);b!=null&&(B(a,c,0),a.g.g.push(b?1:0))}function df(a,b,c){b=zd(b);b!=null&&Dc(a,c,vb(b))}function ef(a,b,c,d,e){Ec(a,c,Be(b,d),e)}function ff(a,b,c){Cc(a,c,td(b))}
function gf(a,b,c){if(a.h!==5&&a.h!==2)return!1;b=Yd(b,c);a.h==2?xc(a,bc,b):b.push(bc(a.g));return!0}function hf(a,b,c){if(a.h!==0)return!1;N(b,c,Vb(a.g,$a));return!0}function jf(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Yd(b,c);a.h==2?xc(a,Xb,b):b.push(Xb(a.g));return!0}function kf(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Yd(b,c);a.h==2?xc(a,dc,b):b.push(dc(a.g));return!0}
var lf=L(function(a,b,c){if(a.h!==1)return!1;N(b,c,cc(a.g));return!0},Ye,ve),mf=L(function(a,b,c,d){if(a.h!==1)return!1;ge(b,c,d,cc(a.g));return!0},Ye,ve),O=L(function(a,b,c){if(a.h!==5)return!1;N(b,c,bc(a.g));return!0},Ze,ue),nf=M(gf,function(a,b,c){b=K(pd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,5),e=e.g,Wa(g),z(e,v))}},ue),of=M(gf,function(a,b,c){b=K(pd,b,!0);if(b!=null&&b.length)for(B(a,c,2),mc(a.g,b.length*4),c=0;c<b.length;c++){var d=a.g;Wa(b[c]);z(d,v)}},
ue),pf=L(function(a,b,c,d){if(a.h!==5)return!1;ge(b,c,d,bc(a.g));return!0},Ze,ue),qf=L(function(a,b,c){a.h!==0?a=!1:(N(b,c,$b(a.g)),a=!0);return a},$e,se),rf=M(function(a,b,c){a.h!==0&&a.h!==2?a=!1:(b=Yd(b,c),a.h==2?xc(a,$b,b):b.push($b(a.g)),a=!0);return a},function(a,b,c){b=K(vd,b,!1);if(b!=null&&b.length){c=Ac(a,c);for(var d=0;d<b.length;d++){var e=b[d];switch(typeof e){case "number":var f=a.g;Ua(e);lc(f,v,x);break;case "bigint":e=kb(e);lc(a.g,e.h,e.g);break;default:e=lb(e),lc(a.g,e.h,e.g)}}Bc(a,
c)}},se),sf=L(function(a,b,c,d){a.h!==0?a=!1:(ge(b,c,d,$b(a.g)),a=!0);return a},$e,se),tf=L(function(a,b,c){return hf(a,b,c)},af,te),uf=L(function(a,b,c){return hf(a,b,c)},af,te),P=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Xb(a.g));return!0},bf,re),vf=M(jf,function(a,b,c){b=K(td,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),nc(e.g,g))}},re),wf=M(jf,function(a,b,c){b=K(td,b,!0);if(b!=null&&b.length){c=Ac(a,c);for(var d=0;d<b.length;d++)nc(a.g,b[d]);Bc(a,c)}},
re),xf=L(function(a,b,c,d){if(a.h!==0)return!1;ge(b,c,d,Xb(a.g));return!0},bf,re),Q=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,dc(a.g));return!0},cf,pe),yf=M(kf,function(a,b,c){b=K(qd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),e.g.g.push(g?1:0))}},pe),zf=M(kf,function(a,b,c){b=K(qd,b,!0);if(b!=null&&b.length)for(B(a,c,2),mc(a.g,b.length),c=0;c<b.length;c++)a.g.g.push(b[c]?1:0)},pe),Af=L(function(a,b,c,d){if(a.h!==0)return!1;ge(b,c,d,dc(a.g));return!0},cf,pe),
R=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,vc(a));return!0},df,qe),Bf=L(function(a,b,c,d){if(a.h!==2)return!1;ge(b,c,d,vc(a));return!0},df,qe),T=M(function(a,b,c){if(a.h!==2)return!1;a=vc(a);Zd(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(zd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Dc(e,f,vb(g))}},qe),U,Cf=void 0;Cf=Cf===void 0?oe:Cf;
U=new ye(function(a,b,c,d,e){if(a.h!==2)return!1;d=Md(void 0,d);Zd(b,b[C]|0,c).push(d);uc(a,d,e);return!0},function(a,b,c,d,e){if(Array.isArray(b)){for(var f=0;f<b.length;f++)ef(a,b[f],c,d,e);a=b[C]|0;a&1||E(b,a|1)}},Cf);
var V=ze(function(a,b,c,d,e,f){if(a.h!==2)return!1;var g=b[C]|0;fe(b,g,f,c,$c(g));b=he(b,d,c);uc(a,b,e);return!0},ef),Df=L(function(a,b,c){if(a.h!==2)return!1;N(b,c,wc(a));return!0},function(a,b,c){b=xd(b);b!=null&&Dc(a,c,Tb(b,!0).buffer)},we),W=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Yb(a.g));return!0},function(a,b,c){b=ud(b);b!=null&&b!=null&&(B(a,c,0),mc(a.g,b))},J()),X=L(function(a,b,c){if(a.h!==0)return!1;N(b,c,Xb(a.g));return!0},ff,xe),Ef=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=
Yd(b,c);a.h==2?xc(a,ec,b):b.push(Xb(a.g));return!0},function(a,b,c){b=K(td,b,!0);if(b!=null)for(var d=0;d<b.length;d++)Cc(a,c,b[d])},xe),Ff=L(function(a,b,c,d){if(a.h!==0)return!1;ge(b,c,d,Xb(a.g));return!0},ff,xe),Gf=M(function(a,b,c){if(a.h!==0&&a.h!==2)return!1;b=Yd(b,c);a.h==2?xc(a,Zb,b):b.push(Zb(a.g));return!0},function(a,b,c){b=K(td,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&(B(e,f,0),mc(e.g,(g<<1^g>>31)>>>0))}},J()),Hf=[!0,R,P],If=[!0,R,Q],Jf=[!0,R,R];function Kf(a){return function(b){var c=new yc;Ve(b.l,c,Le(Ee,Se,Te,a));zc(c,c.g.end());b=new Uint8Array(c.h);for(var d=c.i,e=d.length,f=0,g=0;g<e;g++){var h=d[g];b.set(h,f);f+=h.length}c.i=[b];return b}};var Lf=[0,L(function(a,b,c){if(a.h!==1)b=!1;else{var d=a.g;a=ac(d);d=ac(d);N(b,c,$a(a,d));b=!0}return b},function(a,b,c){b=wd(b);if(b!=null)switch(Fc(b),B(a,c,1),a=a.g,Fc(b),typeof b){case "number":b<0?(c=-b,c=fb(new eb(c&4294967295,c/4294967296)),b=c.g,z(a,c.h),z(a,b)):(Ta(b),z(a,v),z(a,x));break;case "bigint":c=b<BigInt(0)?fb(gb(-b)):gb(b);b=c.g;z(a,c.h);z(a,b);break;default:c=b.length&&b[0]==="-"?fb(hb(b.substring(1))):hb(b),b=c.g,z(a,c.h),z(a,b)}},J()),-1];var Mf=[0,L(function(a,b,c){if(a.h!==5)return!1;a=a.g;var d=a.h,e=a.g,f=d[e],g=d[e+1],h=d[e+2];d=d[e+3];Wb(a,a.g+4);N(b,c,f<<0|g<<8|h<<16|d<<24);return!0},function(a,b,c){b=td(b);b!=null&&(B(a,c,5),a=a.g,a.g.push(b>>>0&255),a.g.push(b>>>8&255),a.g.push(b>>>16&255),a.g.push(b>>>24&255))},J()),-1];var Nf=[0,X,-1,qf,R,Mf,-1,O,P,X,Lf,R,X,-1,[0,Mf,-1],P,uf,Lf,O,[0,1,P,-4,lf,[0,O,-1,P],R,O,U,[0,X,P],P,-1,X,-2,O,-1,X,O,X,P,[0,3,P,-1,4,M(function(a,b,c){if(a.h!==2)return!1;a=wc(a);Zd(b,b[C]|0,c).push(a);return!0},function(a,b,c){b=K(xd,b,!1);if(b!=null)for(var d=0;d<b.length;d++){var e=a,f=c,g=b[d];g!=null&&Dc(e,f,Tb(g,!0).buffer)}},we)],lf,W,[0,X,-1,R],Q],R,Ef,U,[0,Lf,U,[0,R,X],O,X,-1],1,U,[0,uf,-1,W],X,Lf];var Of=[0,qf,[0,O,R,P,R,P,vf,qf,R,P,R,-1,O,P,O],Df,[0,M(function(a,b,c){if(a.h!==1&&a.h!==2)return!1;b=Yd(b,c);if(a.h==2){c=a.g;a=Yb(a.g)/8;var d=c.g,e=8*a;if(d+e>c.i)throw Error();var f=c.h;d+=f.byteOffset;jc===void 0&&(jc=(new Uint16Array((new Uint8Array([1,2])).buffer))[0]==513);if(jc)for(c.g+=e,c=new Float64Array(f.buffer.slice(d,d+e)),a=0;a<c.length;a++)b.push(c[a]);else for(e=0;e<a;e++)b.push(cc(c))}else b.push(cc(a.g));return!0},function(a,b,c){b=K(pd,b,!0);if(b!=null)for(var d=0;d<b.length;d++){var e=
a,f=c,g=b[d];g!=null&&(B(e,f,1),e=e.g,Xa(g),z(e,v),z(e,x))}},ve),-1]];function je(a){this.l=F(a,void 0,void 0,2048)}p(je,I);function Pf(a){a=Vd(a,1,ae);return a==null?Ob():a}function Qf(a){var b=16E3;b=b===void 0?0:b;a=td(Vd(a,2));return a!=null?a:b};function Rf(a){this.l=F(a,void 0,void 0,2048)}p(Rf,I);function Sf(a){this.l=F(a,void 0,void 0,2048)}p(Sf,I);var Tf=[0,Df,P];var Uf=[0,[1,2,3,4],Bf,Ff,V,[0,R,X],Ff];var Vf=[0,R,-2,3,O,R,T,X,-1,U,Uf,R,-2];var Wf=[0,P,-3];var Yf=[0,[1,2,3,4],Af,-1,Bf,-1];var Zf=[0,R,-1,1,R,-1,6,T,[0,W,R,W,P,W,-4,O,W,O,-1],Q,T,-1];var Y=[0,X,-5];var $f=[0,[0,R,-5,Q,T,Y],R,-7,Q,R,T,Y];var ag=[0,T,1,X,-1,R];var bg=[0,R,-2,Y,R];var cg=[0,R,-1,Q,R,T,Y];var dg=[0,U,[0,R,-1],R,Q,R];var eg=[0,R,-2,Y];var fg=[0,R,-3,P,R,Q,R,-1,Q,R,T,Y,R,-2];var gg=[0,Q,R,-3,P,R,Q,R,T,Y];var hg=[0,R,-3,P,R,-3,Q,R,T,Y];var ig=[0,R,P,X,R];var jg=[0,R,-2,P,R,Q,R,Q,T,Y];var kg=[0,R,-2,Q];var lg=[0,gg,jg,cg,R,P,R,Q,R,T,Y];var mg=[0,gg,qf,R,P,R,Q,R,T,Y,R];var ng=[0,R,-1,Q,R,T,Y,Q];var og=[0,R,P,Q];var pg=[0,R,T,R,P,R,Q,R,T,Y];var qg=[0,P,-2,Q,R,P,R,P,R,Q,R,T,Y,Q];var rg=[0,X,-1];var sg=[0,O,-1];var tg=[0,U,[0,O,-2],O,-1,P,U,[0,P,X,P,X,W,X,-1,U,sg,[0,O,-1],[0,U,sg,O,X],[0,U,sg,X]],O];var ug=[0,O,-2];var vg=[-11,{},Wf,R,[0,zf,wf,of,T,U,[0,of],[0,of]],of,R,-1,[0,ug],R,[0,of,-1,U,[0,X,P]],-1];var wg=[0,Wf,[0,Q,O,of,-1],P,[0,of]];var xg=[0,P,-2];var yg=[0,X,[0,vf,rf]];var zg=[0,X,[0,vf,T]];var Ag=[0,P,-1,X,P];var Bg=[0,of,wf];var Cg=[0,of,wf,R];var Dg=[0,[0,tf,X,Q]];var Eg=[0,P,-2,R];var Fg=[0,X];var Hg=[-15,{},U,[-45,{},[1,3,4,5,6,7,8,9,10,11,12,13,14,15,16,18,19,21,25,32,36,37,41],Bf,R,V,cg,V,ng,V,gg,V,jg,V,qg,V,lg,V,fg,V,$f,V,pg,V,mg,V,hg,V,dg,Bf,-1,U,kg,Bf,-1,tg,pf,[0,Q,-1,X,rg,Q,-1,O,Q,T,Ag,X,-1],Nf,Q,V,[0,R,-1],U,[0,R,-1],[0,T,Q],Y,X,Fg,Q,V,og,R,T,R,V,eg,V,bg,R,-1,Q,V,ig,Q,Eg,R],U,[0,R,U,[0,R,-1,X],U,[0,R,-1],R,X,[0,X,-3],T,Q,R],4,Fg,O,Q,function(){return Gg},R,Dg,Q,[0,Q,-1]],Gg=[0,U,function(){return Hg},-1];var Ig=function(a,b){return function(c,d){var e={S:!0};d&&Object.assign(e,d);c=pc(c,void 0,void 0,e);try{var f=new a,g=f.l;Pe(b)(g,c);var h=f}finally{rc(c)}return h}}(Sf,[0,X,2,Tf,X,[-500,{},uf,R,Hg,-1,1,[0,X,P,-1,O],[0,R,-5,P,R,1,Q,-1,R,X,U,Vf,R],qf,-2,89,[-5,{},U,[-75,{},Wf,W,-1,R,X,R,-2,Q,O,X,R,Q,-1,5,cg,ng,R,gg,jg,qg,lg,gg,fg,$f,pg,mg,hg,R,-1,eg,R,bg,1,dg,ig,[0,R,-1],U,kg,7,Zf,1,R,Q,R,Q,og,R,Q,R,-2,Yf,R,Q,O,T,1,R,Q,1,R,ag,X,Q],U,[-71,{},Wf,X,R,-1,Q,1,R,X,Zf,O,X,Q,Ef,R,rg,1,P,Q,1,R,X,O,[0,[0,O,
-2],[0,O,-2]],[0,X,-2],25,tg,R,3,Q,-1,1,Q,R,2,Q,Yf,R,X,O,R,-1,1,R],U,[-11,{},Wf,R,X,5,[0,P,-3],R],U,[-12,{},Wf,R,Q,O,-1,[0,O,-6,U,[0,R,X,O]],nf,P,-1,R,[0,[0,P,-3],U,[0,R,O]]]],1,[0,3,U,[0,U,xg,xg],Q],3,Ag,X,-1,1,[-12,{},Ag,X,-1,[0,X,2,X,-1],X,-1,R,3,[0,Q,-2]],39,[0,[0,P,-2,wf,-2],zg,-2,yg,zg,-2,yg,-5],49,[-3,{},[0,U,vg,[0,U,[0,R,U,[0,P,O,U,[0,P,O,-1,P],Q],U,[0,P,O],Q,-2]]],U,[0,P,U,[0,Wf,[-10,{},P,-2,W,[0,W,-2,O,-8,nf,-5,Gf,-1],Ef,P,-2],ug,O,-2,U,[0,X,nf]]]],[-3,{},[0,U,vg],U,[-6,{},U,wg,U,ug,vf,
yf,wf]],48,[0,[0,U,wg,Of],[0,O,W,-1,O,W]],49,Tf,599,[-1,{}],Q,[0,O,-2,P],[-3,{},U,[-7,{},W,-1,Q,U,[0,[1,2,3,4],V,[-5,{},X,R,-1,Q],V,[0],V,[0],V,[0]],O,W],W],Bg,U,Cg]]);var Jg=Kf(Vf);function Kg(a){this.l=F(a,void 0,void 0,2048)}p(Kg,I);var Lg=[1,4];function Mg(a){this.l=F(a,11,void 0,2048)}p(Mg,I);var Ng=[0,P,Df,X];var Og=[-11,{},[0,U,[0,X,1,X],Ef,Nf,T,U,[0,R,X,O,X],1,X,-1,Q],[0,R,-3,O,[0,P,R],Ef,-1],[0,Lg,pf,[0,X],[0,2,X],Ff,[0,Q,-1],O,X,-2],[0,1,O,U,[0,R,-1],Ef,Dg,P],ag,[-1,{}],[0,[1,3],V,[0,[3,4],U,Uf,-1,xf,Af,U,Uf],R,Bf],[0,[1,2,3,4,5,6,7,8,9,10,11],Ff,-10],[0,[1,2],[6],[3,4,5],V,Ng,V,Bg,V,Ng,V,Bg,V,[0,of],V,[0,P,-1,Q,O,-1]],[0,[1],V,Bg,U,Cg,Ng]];var Pg=[-3,{},R,Og];function Qg(a){this.l=F(a,void 0,void 0,2048)}p(Qg,I);function Rg(a){this.l=F(a,5,void 0,2048)}p(Rg,I);function Sg(a){this.l=F(a,void 0,void 0,2048)}p(Sg,I);var Tg=[2,3,4];var Ug=[0,R,-2];var Vg=[0,[3,4],R,-1,sf,mf,P,-1,R,-1];var Wg=[0,Tg,P,V,[-5,{},U,[0,[100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],P,R,-1,Og,U,[0,[4,5],P,R,-1,Ff,Bf,R,Og,X],R,-1,Eg,Q,90,Bf,V,[0,R,X,[0,X,O,X]],V,[0,R],V,[0,R,P],V,[0,R,X],V,[0,R,-1],V,[0,R,X],V,Vg,V,[0,1,R],V,Ug,V,[0,T,X],V,[0,[5,6,7],P,-2,R,Ff,-1,xf],V,[0,[5,6],P,-3,Ff,xf],V,[0,[1,2],[4,5,6],V,Vg,V,Ug,R,Ff,-1,xf],V,[0,[3,4],[8,9,10],P,-1,xf,Bf,P,X,R,Ff,-1,xf],V,[0,R,T,R],V,[0,[4,5,6],Vg,R,1,Ff,-1,xf],V,[0,R,-3,P,R,-2],V,[0,R,X],V,[0,U,[0,R,-1],R,
Q],V,[0,R,-1]],Og,U,[0,P,-1,Og],Q],V,Pg,V,[0,[1,2],V,Ng,V,[0,R]]];var Xg=[0,Xe,If,Xe,Hf,Xe,Jf];function Yg(a){this.l=F(a,4,void 0,2048)}p(Yg,I);var Zg=[-4,{},U,Wg,Og,Xg];function $g(a){this.l=F(a,3,void 0,2048)}p($g,I);var ah=Kf([-3,{},U,Hg,Zg]);function bh(a){a=a===void 0?new AudioContext({sampleRate:24E3}):a;this.h=!1;this.u=[];this.T={};this.M={};this.F={};this.N={};this.D={};this.Z=new TextEncoder;this.W="";this.I=null;this.J=0;this.K=[];this.H=this.v=this.B=this.j=!1;this.A=[];this.L=[];this.C=[];this.i=a;this.G=this.i.createGain()}aa=bh.prototype;
aa.init=function(a){var b=this;return t(function(c){switch(c.h){case 1:if(b.h)return c.return();b.h=!0;b.extensionId=a;return c.g(loadWasmTtsBindings(),2);case 2:return b.g=c.i,c.g(ch(b),3);case 3:return c.g(dh(b),4);case 4:return c.return(eh(b))}})};aa.onLanguageStatusRequest=function(a){var b=this,c,d;return t(function(e){return e.h==1?b.h?e.m(2):e.g(b.init(b.extensionId),2):e.h!=4?(c="offscreenLanguageStatusResponse",d=a,e.g(fh(b,a),4)):e.return({type:c,lang:d,status:e.i})})};
aa.onInstallLanguageRequest=function(a){var b=this,c,d;return t(function(e){return e.h==1?b.h?e.m(2):e.g(b.init(b.extensionId),2):e.h!=4?(c="offscreenLanguageStatusResponse",d=a,e.g(gh(b,a),4)):e.return({type:c,lang:d,status:e.i})})};aa.onUninstallLanguageRequest=function(a){var b=this,c;return t(function(d){if(d.h==1)return b.h?d.m(2):d.g(b.init(b.extensionId),2);if(d.h!=4)return d.g(hh(b,a),4);(c=d.i)&&ih(b);return d.return({type:"offscreenLanguageStatusResponse",lang:a,status:"notInstalled"})})};
function hh(a,b){var c,d,e,f,g,h;return t(function(k){switch(k.h){case 1:c=jh(a,b),d=!1,e=q(c),f=e.next();case 2:if(f.done){k.m(4);break}g=f.value;kh(a,g);if(!g.remote||g.unloaded){k.m(3);break}h="/voices/"+g.fileId;k.A(5);return k.g(lh(a,h),7);case 7:d=!0;k.v(3);break;case 5:k.o();case 3:f=e.next();k.m(2);break;case 4:return k.return(d)}})}
aa.onStop=function(a){var b=this,c;return t(function(d){if(!b.h)return d.return();mh(b);b.j=!1;b.B=!1;b.v=a;b.o&&(c={command:"clearBuffers"},b.o.port.postMessage(c),b.o.disconnect());for(nh(b);b.L.length>0;)window.clearTimeout(b.L.pop());b.A=[];b.K.length=0;b.I=null;b.J=0;d.C()})};aa.onPause=function(){var a=this;return t(function(b){if(b.h==1){if(!a.h)return b.return();nh(a);a.v=!0;return b.g(a.i.suspend(),2)}a.j=!1;b.C()})};
aa.onResume=function(){var a=this;return t(function(b){if(b.h==1){if(!a.h||a.j)return b.return();a.v=!1;return a.B?b.g(a.i.resume(),2):(a.C.length===0&&oh(a),b.return(ph(a)))}a.j=!0;qh(a);b.C()})};
aa.onSpeak=function(a,b){var c=this,d,e,f,g,h;return t(function(k){switch(k.h){case 1:return c.v=!1,k.g(c.init(c.extensionId),2);case 2:if(!c.g)throw Error("WASM module not initialized.");return b.voiceName?k.g(c.onStop(!1),3):k.return();case 3:c.utterance=a;d=b.voiceName;if(c.W===d){k.m(4);break}k.A(5);return k.g(rh(c,d,!1),7);case 7:e=c.F[d];if(!e)throw Error("Invalid voice name: "+b.voiceName);f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");if(c.g){var m=sh(c,g);var n=sh(c,f),w=c.g._GoogleTtsInit(m,
n);c.g._free(n);c.g._free(m);m=w===1}else m=!1;if(!m)throw Error("Failed to initialize pipeline "+g);k.v(4);break;case 5:return k.o(),k.return(Promise.reject(Error("Voice is not available")));case 4:c.W=d;var y=b.lang;c.extensionId&&y&&chrome.runtime.sendMessage(c.extensionId,{type:"languageUsed",language:y});try{if(y=d,c.g&&a.length){var A=new Rg,H=new Qg;var D=Xd(H,2,yd(a));var S=ne(A,[D]);var zh=new Kg,Pb=b.rate;var Ah=ce(zh,1,Lg,od(!Pb||Pb<.1||Pb>10?1:Pb));var Xf=b.pitch;m=Xd(Ah,6,od(Xf?Math.pow(2,
(Xf-1)*20/12):1));b.volume!==void 0&&b.volume>=0&&(c.G.gain.value=Math.min(Math.max(b.volume,0),1));n=new Yg;w=new Sg;A=S;A=le(A);ce(w,2,Tg,A);A&&!Wc(A)&&Ud(w.l);var Bh=ne(n,[w]);var Ch=new Mg;var Dh=me(Ch,3,m);var Eh=me(Bh,2,Dh);var Fh=new $g;var Gh=me(Fh,2,Eh);var cd=Array.from(new Uint8Array(ah(Gh))),Hh=c.N[y],Ih=new Rf;var Jh=Xd(Ih,1,yd(Hh));var dd=Jg(Jh),ed=c.g._malloc(cd.length);c.g.HEAPU8.set(cd,ed);var fd=c.g._malloc(dd.length);c.g.HEAPU8.set(dd,fd);var Kh=c.g._GoogleTtsInitBuffered(ed,fd,
cd.length,dd.length);c.g._free(ed);c.g._free(fd);if(!Kh)throw Error("Failed to initialize buffered synthesis.");oh(c)}}catch(gd){throw h=gd instanceof Error?gd.message:String(gd),Error("Synthesis failed: "+h);}k.C()}})};
function eh(a){return a.i.audioWorklet.addModule("../streaming_worklet_processor.js").then(function(){a.o=new AudioWorkletNode(a.i,"streaming-worklet-processor");a.o.port.onmessage=function(b){a.utterance&&!a.H&&b.data.type==="empty"&&(th(a,{type:"end",charIndex:a.utterance.length}),a.onStop(!1))};a.G.connect(a.i.destination)})}function sh(a,b){b=a.Z.encode(b+"\x00");var c=a.g._malloc(b.length);a.g.HEAPU8.set(b,c);return c}
function oh(a){var b=setTimeout(function(){a.H=!0;var c=a.g,d=c._GoogleTtsReadBuffered();if(d===-1)th(a,{type:"error"}),mh(a);else{for(var e=c._GoogleTtsGetTimepointsCount(),f=0;f<e;f++)uh(a,{audioDeltaMillis:c._GoogleTtsGetTimepointsTimeInSecsAtIndex(f)*1E3,charIndex:Number(c._GoogleTtsGetTimepointsCharIndexAtIndex(f)),length:Number(c._GoogleTtsGetTimepointsCharLengthAtIndex(f))});f=c._GoogleTtsGetEventBufferPtr();e=c._GoogleTtsGetEventBufferLen();c=new Uint8Array(c.HEAPU8.buffer,f,e);c=Ig(c.slice(0,
e));d=d===0;e=c.l;ie(e,e[C]|0)!==void 0?vh(a,c,d):wh(a,null);d?mh(a):oh(a)}},0);a.C.push(b)}function mh(a){a.H=!1;a.g._GoogleTtsFinalizeBuffered()}function nh(a){for(;a.C.length>0;)window.clearTimeout(a.C.pop())}function uh(a,b){var c=b.audioDeltaMillis,d=b.charIndex,e=b.length;d<0||c<=0||(a.j?c<-100||(c<2?th(a,{type:"word",charIndex:d,length:e}):(c=window.setTimeout(function(){a.j?th(a,{type:"word",charIndex:d,length:e}):a.A.push(b)},c),a.L.push(c))):a.A.push(b))}
function qh(a){var b=a.A;a.A=[];b=q(b);for(var c=b.next();!c.done;c=b.next())uh(a,c.value)}function vh(a,b,c){if(Qf(ke(b))===24E3){var d;b=(d=Pf(ke(b)))==null?void 0:new Uint8Array(Rb(d)||0);d=new Uint8Array(b);d=new Int16Array(d.buffer);d=Float32Array.from(d,function(e){return e/32768});xh(a,d,c)}}
function xh(a,b,c){for(var d=a.I,e=a.J,f=0,g=b.length;f<g;){var h=Math.min(128-e,g-f);d||(d=new Float32Array(128));d.set(b.subarray(f,f+h),e);f+=h;e+=h;e===128&&(wh(a,d),e=0,d=null)}e!==0&&(c?wh(a,d):(a.I=d,a.J=e))}function wh(a,b){b&&a.K.push(b);if(a.o)for(;b=a.K.shift();)a.o.port.postMessage({command:"addBuffer",buffer:b}),a.B||a.v||ph(a)}function ph(a){return t(function(b){if(b.h==1)return a.o.connect(a.G),b.g(a.i.resume(),2);a.j=!0;a.B=!0;th(a,{type:"start",charIndex:0});qh(a);b.C()})}
function fh(a,b){return t(function(c){return c.return(yh(a,b,!1))})}function gh(a,b){return t(function(c){return c.return(yh(a,b,!0))})}function yh(a,b,c){var d,e,f;return t(function(g){switch(g.h){case 1:return d=jh(a,b),e=d.map(function(h){return rh(a,h.speakers[0].name,c)}),g.A(2),g.g(Promise.all(e),4);case 4:f="installed";c&&ih(a);g.v(3);break;case 2:g.o(),f=c?"failed":"notInstalled";case 3:return g.return(f)}})}
function jh(a,b){var c=b.toLowerCase();return c.includes("-")?a.u.filter(function(d){var e;return((e=d.language)==null?void 0:e.toLowerCase())===c}):a.u.filter(function(d){var e;return((e=d.language)==null?void 0:e.split("-")[0])===c})}
function Lh(a,b,c){var d,e,f,g,h,k,m,n,w,y;return t(function(A){if(!a.D[b])return A.return(Promise.resolve());d=a.D[b];f=q(Object.entries(a.M));for(g=f.next();!g.done;g=f.next())if(h=g.value,k=q(h),m=k.next().value,n=k.next().value,w=m,y=n,d===y){e=w;break}return e?A.return(rh(a,e,c)):A.return(Promise.reject(Error("No multivoice found for: "+b)))})}
function rh(a,b,c){var d,e,f,g,h,k;return t(function(m){switch(m.h){case 1:if(!a.g)return m.return(Promise.reject(Error("WASM module not initialized.")));m.A(2);return m.g(Lh(a,b,c),4);case 4:m.v(3);break;case 2:return d=m.o(),m.return(Promise.reject(Error(""+d)));case 3:e=a.F[b];if(!e)return m.return(Promise.reject(Error("Invalid voice name: "+b)));f=["/voices",e].join("/");g=[f,"pipeline.pb"].join("/");try{if(h=a.g.FS.stat(g))return m.return(Promise.resolve())}catch(n){}k=a.T[b];return c||k.indexOf("http")!==
0?m.return(fetch(k).then(function(n){return n.ok?n.arrayBuffer():Promise.reject(Error("Failed to fetch voice from url: "+k))}).then(function(n){if(!n)return Promise.reject(Error("Failed to fetch voice from url: "+k));if(!Mh(a,e,n))return Promise.reject(Error("Failed to validate voice data: "+e));try{a.g.FS.stat(f)}catch(H){a.g.FS.mkdir(f)}a.g.FS.stat(f);var w=sh(a,f),y=new Uint8Array(n),A=a.g._malloc(y.length);a.g.HEAPU8.set(y,A);n=a.g._GoogleTtsInstallVoice(w,A,n.byteLength);a.g._free(w);a.g._free(A);
return n!==1?Promise.reject(Error("Failed to install voice.")):new Promise(function(H,D){a.g.FS.syncfs(!1,function(S){S?D(S):H()})})})):m.return(Promise.reject(Error("Not downloading remote voice because caller did not request it.")))}})}function th(a,b){a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenTtsEventResponse",event:b})}
function ch(a){var b,c;return t(function(d){if(d.h==1){if((b=a.g)==null||!b.FS)throw Error("WASM FS not ready for IDBFS setup.");try{a.g.FS.stat("/voices")}catch(e){a.g.FS.mkdir("/voices")}d.A(2);return d.g(new Promise(function(e,f){a.g.FS.mount(a.g.IDBFS,{},"/voices");a.g.FS.syncfs(!0,function(g){g?f(g):e()})}),4)}if(d.h!=2)return d.v(0);c=d.o();throw c;})}
function dh(a){var b,c,d;return t(function(e){switch(e.h){case 1:return e.A(2),e.g(fetch("voices.json"),4);case 4:b=e.i;if(!b.ok)throw Error("Failed to fetch voices.json: "+b.statusText+" ("+b.status+")");return e.g(b.json(),5);case 5:c=e.i;a.u=c;ih(a);e.v(0);break;case 2:throw d=e.o(),d;}})}
function ih(a){a.T={};a.M={};a.F={};a.N={};a.D={};for(var b={},c=q(a.u),d=c.next();!d.done;d=c.next()){d=d.value;for(var e=q(d.speakers),f=e.next();!f.done;f=e.next()){f=f.value;a.M[f.name]=d.id;a.F[f.name]=d.fileId;a.N[f.name]=f.speaker;d.dependentVoiceId&&(a.D[f.name]=d.dependentVoiceId);kh(a,d);a.T[f.name]=d.remote&&d.unloaded?d.url:"/"+d.id+".zvoice";var g=d.id.split("-");if(g.length<2)throw Error("Unexpected voice id format: "+d.id);g=g[0]+"-"+g[1].toUpperCase();d.language=g;d.remote&&d.unloaded||
(b[g]||(b[g]=[]),b[g].push(f.name))}}a.extensionId&&chrome.runtime.sendMessage(a.extensionId,{type:"offscreenVoicesResponse",voices:b})}function kh(a,b){try{a.g.FS.stat(["/voices",b.fileId].join("/")),b.unloaded=!1}catch(c){b.unloaded=!0}}
function lh(a,b){if(a.g)try{for(var c=a.g.FS.readdir(b),d=q(c),e=d.next();!e.done;e=d.next()){var f=e.value;f!=="."&&f!==".."&&a.g.FS.unlink(b+"/"+f)}a.g.FS.rmdir(b);return new Promise(function(g,h){a.g.FS.syncfs(!1,function(k){k?h(k):g()})})}catch(g){return Promise.resolve()}}function Mh(a,b,c){var d,e;return t(function(f){if(f.h==1)return f.g(Nh(c),2);d=f.i;e=a.u.find(function(g){return g.fileId===b});return f.return(e!==void 0&&e.sha256Checksum===d&&e.compressedSize===c.byteLength)})}
function Nh(a){var b,c,d,e;return t(function(f){if(f.h==1)return crypto&&crypto.subtle?f.g(crypto.subtle.digest("SHA-256",a),2):f.return("");b=f.i;c="";for(d=0;d<b.byteLength;d++)e=(new Uint8Array(b))[d],c+=Number(e>>4).toString(16),c+=Number(e&15).toString(16);return f.return(c)})}ea.Object.defineProperties(bh.prototype,{voices:{configurable:!0,enumerable:!0,get:function(){return this.u}}});var Z=new bh,Oh=null;function Ph(a){Oh||(Oh=Z.init(a.id));return Oh}
chrome.runtime.onMessage.addListener(function(a,b,c){if(a.type==="speak")return c({result:"Start speaking"}),function(){var d,e;return t(function(f){switch(f.h){case 1:return f.A(2),f.g(Ph(b),4);case 4:return f.g(Z.onSpeak(a.utterance,a.options),5);case 5:f.v(0);break;case 2:d=f.o(),e=d instanceof Error?d.message:String(d),th(Z,{type:"error",errorMessage:e}),f.C()}})}(),!1;(function(){var d,e,f,g,h;return t(function(k){switch(k.h){case 1:return k.A(2),k.g(Ph(b),4);case 4:switch(a.type){case "init":return k.m(5);
case "getLanguageStatus":return k.m(6);case "installLanguage":return k.m(7);case "uninstallLanguage":return k.m(8);case "removeUnusedLanguage":return k.m(9);case "stop":return k.m(10);case "pause":return k.m(11);case "resume":return k.m(12)}k.m(13);break;case 5:return k.g(Z.init(b.id),14);case 14:c({result:"Initialized"});k.m(13);break;case 6:return d=c,k.g(Z.onLanguageStatusRequest(a.lang),15);case 15:d(k.i);k.m(13);break;case 7:return e=c,k.g(Z.onInstallLanguageRequest(a.lang),16);case 16:e(k.i);
k.m(13);break;case 8:return f=c,k.g(Z.onUninstallLanguageRequest(a.lang),17);case 17:f(k.i);k.m(13);break;case 9:return k.g(hh(Z,a.lang),18);case 18:c({result:"Removed "+a.lang});k.m(13);break;case 10:return k.g(Z.onStop(!0),19);case 19:c({result:"Stopped speech"});k.m(13);break;case 11:return k.g(Z.onPause(),20);case 20:c({result:"Paused speech"});k.m(13);break;case 12:return k.g(Z.onResume(),21);case 21:c({result:"Resumed speech"});k.m(13);break;case 13:k.v(0);break;case 2:g=k.o(),h=g instanceof
Error?g.message:String(g),console.error("Error in offscreen message handler: "+h),c({error:h}),k.C()}})})();return!0});
