# i3blocks Status Command Configuration
# Feature 013: Migrated from polybar to i3bar with i3blocks
{ config, lib, pkgs, ... }:

let
  # Script paths directly from nix store
  cpuScript = pkgs.writeShellScript "i3blocks-cpu" (builtins.readFile ./scripts/cpu.sh);
  memoryScript = pkgs.writeShellScript "i3blocks-memory" (builtins.readFile ./scripts/memory.sh);
  networkScript = pkgs.writeShellScript "i3blocks-network" (builtins.readFile ./scripts/network.sh);
  datetimeScript = pkgs.writeShellScript "i3blocks-datetime" (builtins.readFile ./scripts/datetime.sh);
  projectScript = pkgs.writeShellScript "i3blocks-project" (builtins.readFile ./scripts/project.sh);
in
{
  # Install i3blocks package
  home.packages = [ pkgs.i3blocks ];

  # Generate i3blocks configuration file with proper nix store script paths
  xdg.configFile."i3blocks/config".text = ''
    # i3blocks configuration for i3bar
    # Generated by home-manager

    # Global properties
    separator_block_width=15
    markup=pango

    # US2: System information blocks
    [cpu]
    command=${cpuScript}
    interval=5

    [memory]
    command=${memoryScript}
    interval=5

    [network]
    command=${networkScript}
    interval=10

    # US3: Project indicator (signal-based)
    [project]
    command=${projectScript}
    interval=once
    signal=10

    # DateTime
    [datetime]
    command=${datetimeScript}
    interval=60
  '';
}
