# i3blocks Status Command Configuration
# Feature 013: Migrated from polybar to i3bar with i3blocks
{ config, lib, pkgs, ... }:

{
  # Install i3blocks package
  home.packages = [ pkgs.i3blocks ];

  # Generate i3blocks configuration file
  xdg.configFile."i3blocks/config".text = ''
    # i3blocks configuration for i3bar
    # Generated by home-manager

    # Global properties
    separator_block_width=15
    markup=pango

    # US3: Project indicator (signal-based)
    [project]
    command=${config.home.homeDirectory}/.config/i3blocks/scripts/project.sh
    interval=once
    signal=10
    color=#b4befe

    # US2: System information blocks
    [cpu]
    command=${config.home.homeDirectory}/.config/i3blocks/scripts/cpu.sh
    interval=5
    color=#cdd6f4

    [memory]
    command=${config.home.homeDirectory}/.config/i3blocks/scripts/memory.sh
    interval=5
    color=#cdd6f4

    [network]
    command=${config.home.homeDirectory}/.config/i3blocks/scripts/network.sh
    interval=10
    color=#cdd6f4

    [datetime]
    command=${config.home.homeDirectory}/.config/i3blocks/scripts/datetime.sh
    interval=60
    color=#cdd6f4
  '';

  # Make i3blocks scripts executable
  home.file.".config/i3blocks/scripts/cpu.sh".source = ./scripts/cpu.sh;
  home.file.".config/i3blocks/scripts/cpu.sh".executable = true;

  home.file.".config/i3blocks/scripts/memory.sh".source = ./scripts/memory.sh;
  home.file.".config/i3blocks/scripts/memory.sh".executable = true;

  home.file.".config/i3blocks/scripts/network.sh".source = ./scripts/network.sh;
  home.file.".config/i3blocks/scripts/network.sh".executable = true;

  home.file.".config/i3blocks/scripts/datetime.sh".source = ./scripts/datetime.sh;
  home.file.".config/i3blocks/scripts/datetime.sh".executable = true;

  home.file.".config/i3blocks/scripts/project.sh".source = ./scripts/project.sh;
  home.file.".config/i3blocks/scripts/project.sh".executable = true;
}
