#!/usr/bin/env bash
# Setup script for Wayland remote desktop access

echo "Wayland Remote Desktop Setup Guide"
echo "==================================="
echo ""
echo "You have 3 options for remote desktop on your Hetzner VM:"
echo ""
echo "1. KRDP (Native KDE RDP for Wayland) - RECOMMENDED"
echo "   - Best integration with Plasma 6"
echo "   - Uses standard RDP protocol"
echo "   - Setup: System Settings > System > Remote Desktop"
echo "   - Connect: Windows Remote Desktop to <server-ip>:3389"
echo ""
echo "2. KRFB (VNC-based) - MOST STABLE"
echo "   - Rock-solid VNC implementation"
echo "   - Works reliably with Wayland"
echo "   - Setup: Run 'krfb' from terminal or app menu"
echo "   - Connect: Any VNC client to <server-ip>:5900"
echo ""
echo "3. XRDP (Current) - X11 ONLY"
echo "   - Already configured and running"
echo "   - Forces X11 session (not Wayland)"
echo "   - Connect: Windows Remote Desktop to <server-ip>:3389"
echo ""
echo "To enable Wayland remote access:"
echo "1. Login via Hetzner VNC console"
echo "2. Select 'Plasma (Wayland)' at login"
echo "3. Start KRDP or KRFB from within session"
echo "4. Connect from Surface Laptop 2"
echo ""
echo "Current session type:"
echo $XDG_SESSION_TYPE

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    echo ""
    echo "✓ You're running Wayland!"
    echo ""
    echo "Quick start KRFB (VNC):"
    echo "  krfb &"
    echo ""
    echo "Quick start KRDP:"
    echo "  Open System Settings > System > Remote Desktop"
fi