# Package outputs for container images and VM images
# These are built with: nix build .#<package>
#
# Examples:
#   nix build .#container-minimal
#   nix build .#hetzner-sway-qcow2
{ inputs, self, ... }:

let
  inherit (inputs) nixpkgs nixpkgs-bleeding home-manager nixos-generators;
  helpers = import ../lib/helpers.nix { inherit inputs self; };

  # Helper to build container system
  mkContainerSystem = { system, profile }:
    let
      pkgsUnstable = helpers.mkPkgsUnstable system;
    in
    (nixpkgs.lib.nixosSystem {
      inherit system;
      specialArgs = {
        inherit inputs pkgsUnstable;
        containerProfile = profile;
      };
      modules = [
        ../configurations/container.nix
        home-manager.nixosModules.home-manager
        (helpers.mkHomeManagerConfig {
          inherit system;
          user = "code";
          modules = [ ../home-code.nix ];
        })
      ];
    }).config.system.build.toplevel;
in
{
  perSystem = { system, pkgs, ... }:
  let
    incusSwayLiteNixosConfig = (nixpkgs.lib.nixosSystem {
      inherit system;
      specialArgs = { inherit inputs self; };
      modules = [
        ../configurations/incus-sway-lite.nix
        home-manager.nixosModules.home-manager
        (helpers.mkHomeManagerConfig {
          inherit system;
          user = "vpittamp";
          modules = [ ../home-modules/incus-sway-lite.nix ];
        })
      ];
    }).config;

    incusSwayLiteQcow2 = import "${nixpkgs}/nixos/lib/make-disk-image.nix" {
      inherit pkgs;
      lib = pkgs.lib;
      config = incusSwayLiteNixosConfig;
      diskSize = 40 * 1024; # 40GB in MB
      format = "qcow2";
      partitionTableType = "hybrid";
      memSize = 8192;
      # Avoid embedding a full nixpkgs channel tarball in the image;
      # this keeps the image smaller and avoids cptofs memory pressure.
      copyChannel = false;
    };

    incusImageCreationDate = if self ? lastModified then self.lastModified else 0;
    incusImageExpiryDate = incusImageCreationDate + (365 * 24 * 60 * 60);
    incusRelease = "25.11";

    incusSwayLiteMetadata = pkgs.runCommand "incus-sway-lite-incus-metadata" { } ''
      mkdir -p "$out/templates"

      cat > "$out/metadata.yaml" <<EOF
architecture: x86_64
creation_date: ${toString incusImageCreationDate}
expiry_date: ${toString incusImageExpiryDate}
properties:
  architecture: x86_64
  description: NixOS Incus Sway Lite x86_64
  name: nixos-incus-sway-lite
  os: nixos
  release: "${incusRelease}"
  variant: default
templates:
  /etc/nixos/incus.nix:
    when:
    - create
    - copy
    create_only: false
    template: conf-hostname.tpl
    properties: {}
EOF

      cat > "$out/templates/conf-hostname.tpl" <<'EOF'
{
  lib,
  config,
  pkgs,
  ...
}:

# WARNING: THIS CONFIGURATION IS AUTOGENERATED AND WILL BE OVERWRITTEN AUTOMATICALLY

{
  networking.hostName = "{{ instance.name }}";
}
EOF

      ${pkgs.gnutar}/bin/tar -C "$out" -cJf "$out/incus.tar.xz" metadata.yaml templates
    '';

    incusSwayLiteBundle = pkgs.runCommand "incus-sway-lite-incus-bundle" { } ''
      mkdir -p "$out"
      image_path="$(${pkgs.findutils}/bin/find ${incusSwayLiteQcow2} -maxdepth 1 -type f -name '*.qcow2' | ${pkgs.coreutils}/bin/head -n1)"

      if [ -z "$image_path" ]; then
        echo "Could not find qcow2 artifact in ${incusSwayLiteQcow2}" >&2
        exit 1
      fi

      ln -s "$image_path" "$out/disk.qcow2"
      ln -s "${incusSwayLiteMetadata}/incus.tar.xz" "$out/incus.tar.xz"
      ln -s "${incusSwayLiteMetadata}/metadata.yaml" "$out/metadata.yaml"
    '';
  in {
    packages = {
      # KubeVirt Minimal QCOW2 image (Feature 110)
      # Minimal base image for KubeVirt CI/CD testing
      # Uses kubevirt.nix module: cloud-init, QEMU guest agent, SSH, serial console
      # ~500MB compressed, desktop applied via nixos-rebuild
      kubevirt-minimal-qcow2 =
        let
          nixosConfig = (nixpkgs.lib.nixosSystem {
            inherit system;
            modules = [ ../configurations/kubevirt-minimal.nix ];
          }).config;
        in
        import "${nixpkgs}/nixos/lib/make-disk-image.nix" {
          inherit pkgs;
          lib = pkgs.lib;
          config = nixosConfig;
          diskSize = 10 * 1024; # 10GB in MB (minimal base + rebuild space)
          format = "qcow2";
          partitionTableType = "hybrid";
          memSize = 4096; # 4GB QEMU VM memory for build process
        };

      # KubeVirt Sway Desktop QCOW2 image
      # Full Sway desktop with project management, 1Password, dev tools
      # ~2-3GB, no hardware-specific bloat (optimized for KubeVirt)
      kubevirt-sway-qcow2 =
        let
          nixosConfig = (nixpkgs.lib.nixosSystem {
            inherit system;
            specialArgs = { inherit inputs; };
            modules = [
              ../configurations/kubevirt-sway.nix
              home-manager.nixosModules.home-manager
            ];
          }).config;
        in
        import "${nixpkgs}/nixos/lib/make-disk-image.nix" {
          inherit pkgs;
          lib = pkgs.lib;
          config = nixosConfig;
          diskSize = 80 * 1024; # 80GB in MB (full desktop + dev tools)
          format = "qcow2";
          partitionTableType = "hybrid";
          memSize = 8192; # 8GB QEMU VM memory for build process
        };

      # Hetzner Sway QCOW2 image (Feature 007-number-7-short)
      # Wayland/Sway headless VM with WayVNC server
      hetzner-sway-qcow2 =
        let
          # Build the NixOS configuration
          nixosConfig = (nixpkgs.lib.nixosSystem {
            inherit system;
            modules = [ ../configurations/hetzner-sway-minimal.nix ];
          }).config;
        in
        # Call make-disk-image.nix directly with 8GB memSize
        import "${nixpkgs}/nixos/lib/make-disk-image.nix" {
          inherit pkgs;
          lib = pkgs.lib;
          config = nixosConfig;
          diskSize = 50 * 1024; # 50GB in MB
          format = "qcow2";
          partitionTableType = "hybrid";
          memSize = 8192; # 8GB QEMU VM memory for build process
        };

      # Incus Sway Lite QCOW2 image
      # Lightweight headless Sway + i3pm + HM terminal/tmux + local OTEL monitor.
      incus-sway-lite-qcow2 = incusSwayLiteQcow2;

      # Incus VM metadata tarball for image import.
      # Contains metadata.yaml + template(s) in an incus-compatible tarball.
      incus-sway-lite-incus-metadata = incusSwayLiteMetadata;

      # Convenience bundle for one-command build/import workflows.
      # Includes:
      #   - disk.qcow2
      #   - incus.tar.xz
      #   - metadata.yaml
      incus-sway-lite-incus-bundle = incusSwayLiteBundle;

      # Minimal container
      container-minimal = pkgs.dockerTools.buildLayeredImage {
        name = "nixos-container";
        tag = "minimal";
        contents = [ (mkContainerSystem { inherit system; profile = "minimal"; }) ];
        config = {
          Cmd = [ "/bin/bash" ];
          Env = [ "NIXOS_CONTAINER=1" "NIXOS_PACKAGES=minimal" ];
        };
      };

      # Development container
      container-dev = pkgs.dockerTools.buildLayeredImage {
        name = "nixos-container";
        tag = "development";
        contents = [ (mkContainerSystem { inherit system; profile = "development"; }) ];
        config = {
          Cmd = [ "/bin/bash" ];
          Env = [ "NIXOS_CONTAINER=1" "NIXOS_PACKAGES=development" ];
        };
      };

      # Default package
      default = pkgs.dockerTools.buildLayeredImage {
        name = "nixos-container";
        tag = "minimal";
        contents = [ (mkContainerSystem { inherit system; profile = "minimal"; }) ];
        config = {
          Cmd = [ "/bin/bash" ];
          Env = [ "NIXOS_CONTAINER=1" "NIXOS_PACKAGES=minimal" ];
        };
      };

      # Beyla eBPF auto-instrumentation
      beyla = pkgs.callPackage ../pkgs/beyla.nix { };

      # Cachix Deploy specification
      # Build with: nix build .#deploy
      # Used by GitHub Actions to trigger deployments to agents
      deploy =
        let
          cachix-deploy-lib = inputs.cachix-deploy-flake.lib pkgs;
        in
        cachix-deploy-lib.spec {
          agents = {
            thinkpad = self.nixosConfigurations.thinkpad.config.system.build.toplevel;
            ryzen = self.nixosConfigurations.ryzen.config.system.build.toplevel;
          };
        };
    };
  };
}
